### ISSUE TITLE
Unknown command 'public-key-algorithm-name' passed to cert_query

### ISSUE THREAD

**Issue by recalmer** [immauss/openvas#100]
Hi, if i scan some hosts, i get the following massage, in the logs:  "Unknown command 'public-key-algorithm-name' passed to cert_query"... 
![image](https://user-images.githubusercontent.com/45655990/153841841-33ba9e5d-4a41-41f1-8d33-10407de97fb0.png)

**Comment by immauss** [comment]
This looks like an error with an NVT. You should probably ask about this on the community forum. I don't think it has anything to do with the container build.
