### ISSUE TITLE
Container loops over database rollback. 

### ISSUE THREAD

**Issue by TheUntouchable** [immauss/openvas#102]
Hello again ;)

I finally switched to a Raspberry Pi 4 8GB and so I can use the arm64 image (:latest).

Unfortunately, after the first start it tries to rollback the database in an infinite loop and I have to kill the container.

> md manage:  DEBUG:2022-02-17 10h20.39 utc:1892:    sql: ROLLBACK;
> md manage:WARNING:2022-02-17 10h20.39 utc:1892: check_db_trash_report_formats: g_lstat (/var/lib/gvm/gvmd/report_formats_trash) failed: Permission denied
> md manage:  DEBUG:2022-02-17 10h20.39 utc:1892:    sql: UPDATE report_formats SET owner = (SELECT id FROM users              WHERE uuid = '8282ba3d-66e8-4971-859b-745b76a3a65e') WHERE owner is NULL RETURNING uuid;

Please don't ask me why portainer copies the logs in the wrong order..

The file/folder doesn't even exist:

![grafik](https://user-images.githubusercontent.com/2162540/154458622-15bfbfb2-eb85-49e7-949f-465251e8aa0f.png)

Is there anything I can do? I have already removed the entire contents of the volume and tried again with the same result.

Running on Raspberry OS 64 with a NFS volume on a Synology NAS.

**Comment by immauss** [comment]
I don't see why it would be any different, but I've not done any testing with portainer. 

Is docker available?

**Comment by TheUntouchable** [comment]
Sorry, of course docker is running in the background, portainer is only a web gui to manage the docker installation :)

**Comment by immauss** [comment]
Ah. OK

Can you give me a step by step on how you got there?

I’m in the middle of a 2 month move, so I’m not sure where my pi4 is at the moment, but I’ll do my best.

-Scott


G.E. Scott Knauss
***@***.***
Computer Geek
Security Guy
Linux Guru

**Comment by TheUntouchable** [comment]
Sure!

First I have a general docker NFS share created on my synology nas with "no_squash" to get rid of access problems and seperated folders for each container. Then I created the volume directly linked to the nfs share in docker. There are currently 3 other containers running on that share without problems.

After that, I created a new virtuel eth0.60 adapter on the raspberrypi and a MACVLAN eth in docker, so the container will be able to get an ip address of my local lan in the 60. vlan.

Did some firewall rules about nfs and co so the communication is working to the nas and the docker container ;)

After that, I created the docker container:

sudo docker run -d  --name=openvas  -p 9392:9392/tcp        -v NFS_openvas_data:/data       -e PASSWORD='***********'       -e QUIET="true"         -e TZ="Europe/Berlin"   immauss/openvas:latest

In this is were the problems start.. Everything looks fine till the lines I copied in the first post :(


> I’m in the middle of a 2 month move, so I’m not sure where my pi4 is at the moment, but I’ll do my best.

Take your time! ;)

**Comment by TheUntouchable** [comment]
Don't want to bother you, but since the last update of the container in the last days, it won't even start now :D I just wanted to point it out

`standard_init_linux.go:228: exec user process caused: exec format error`

Image: immauss/openvas:latest
Version: 21.4.4-06

**Comment by immauss** [comment]
oof. Looks like the build didn't push the arm64 image ... :(

Thanks. 
I'm about to push a brandy new version. I'll make sure it has both archs. 

Thanks,
Scott

**Comment by immauss** [comment]
There should be a working arm64 image now. Please let me know if not.

**Comment by TheUntouchable** [comment]
Hey immauss!
At least the image is booting again, thanks for that :)
But I have still the problem that the database is rolling back changes when starting it the first time, I have attached the full logs
[_openvas_logs.txt](https://github.com/immauss/openvas/files/8496109/_openvas_logs.txt)
.

**Comment by TheUntouchable** [comment]
Hey @immauss :)
After more than a year I tried again to start a fresh container with your image, but unfortunately I still have the same problem:
`md manage:WARNING:2023-05-06 22h25.35 utc:351: check_db_trash_report_formats: g_lstat (/var/lib/gvm/gvmd/report_formats_trash) failed: Permission denied
md manage:  DEBUG:2023-05-06 22h25.35 utc:351:    sql: ROLLBACK;`
I have attached the full log if it helps, I killed the container after the first rollback  ;)
[openvas_logs.txt](https://github.com/immauss/openvas/files/11413487/openvas_logs.txt)

**Comment by immauss** [comment]
Ouch ... 
Sorry... this got closed and I lost track of it. 

I just read back through everything ... and the one thing I still don't understand is where did the original database come from? 

If you try to start the container in your environment without the database, does it still do the same thing? 

I'll reopen this now as I  have a little. more time on my hands ...

**Comment by TheUntouchable** [comment]
Everything is alright! :)
The folder mounted in the container is completely empty when the container is first started, so I can't tell where the database is coming from :(  I can only see this in the logs:
`########################################
Creating a base DB from /usr/lib/base-db.xz
base data from:
Thu Oct 13 13:07:27 UTC 2022
########################################
NOTICE:  relation "vt_severities" already exists, skipping
Unpacking base feeds data from /usr/lib/var-lib.tar.xz
Checking DB Version
Current GVMd database version is  250`

**Comment by immauss** [comment]
OK ... 
So it's using the included Database. 
That gets rebuilt fairly regularly. Usually once a week. 
Every time it gets updated, there is new latest.
The version number should be at 22.4.13. ( gvmd is crashing in 22.4.14 and I haven't had time to debug) 

Since I know the image works on RPi 4, (I have it scanning my home network from an RPI4 with 4G of RAM using the arm64 image) my current line of though is around the NFS storage. 

First thought, is SELinux enabled? 
if so, disable and try again. 

otherwise

Try starting the container without specifying the storage option.  If this works, we know it's something with the NFS Storage.

**Comment by immauss** [comment]
Instead of using the NFS as a bind mount, you could try setting your docker storage to the NFS.

Check out this:
https://phoenixnap.com/kb/nfs-docker-volumes

I don't have the resources at the moment to test this, but I read through it and seems to be a good option.  Volumes function different from bind mounts, so that could be the issue. 

-Scott

**Comment by TheUntouchable** [comment]
Just a short update regarding the NFS thing, I already use the direct docker storage mounting :)

> rpd_admin@nw-raspdocker:~ $ docker volume inspect NFS_openvas_data
> [
>     {
>         "CreatedAt": "2022-04-09T21:03:39+02:00",
>         "Driver": "local",
>         "Labels": null,
>         "Mountpoint": "/var/lib/docker/volumes/NFS_openvas_data/_data",
>         "Name": "NFS_openvas_data",
>         "Options": {
>             "device": ":/volume1/raspdocker_nfs/openvas/data",
>             "o": "addr=192.168.40.3,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4",
>             "type": "nfs"
>         },
>         "Scope": "local"
>     }
> ]

Regarding the other things I will have a look tomorrow!

**Comment by TheUntouchable** [comment]
Ok, I could not wait till tomorrow and removed everything regarding openvas, the container, the image and all on the NFS share.
This time I used this compose file to create the container:

> version: "3"
> services:
>   openvas:
>     ports:
>       - "8080:9392"
>     environment:
>       - "PASSWORD=admin"
>       - "USERNAME=admin"
>       - "QUIET=false"  # dump feed sync noise to /dev/null
>     volumes:
>       - "NFS_openvas_data:/data"
>     container_name: openvas
>     image: immauss/openvas:latest
> volumes:
>   NFS_openvas_data:
>     external: true

Still the included db is from last year:

> ########################################
> Creating a base DB from /usr/lib/base-db.xz
> base data from:
> Thu Oct 13 13:07:27 UTC 2022
> ########################################

Still the new container has this tag:
> version | 22.4.03

`docker images`
> REPOSITORY                                      TAG         IMAGE ID       CREATED         SIZE
> immauss/openvas                                 latest      7ea06709b766   3 hours ago     1.48GB

But this time I got some access denied errors while the container tried to create files, see here:
[openvas_logs230507.txt](https://github.com/immauss/openvas/files/11416041/openvas_logs230507.txt)

**Comment by immauss** [comment]
OK .. the dates and versions ... my fault ...
Fixed the date ... and the version... but that's  not your problem. 

Try removing the "volumes" section entirely. 
These lines:
```
volumes:
- "NFS_openvas_data:/data"
```

The access denied errors tell me there is definitely something the container doesn't like with the NFS.

-Scott

**Comment by TheUntouchable** [comment]
Okay, I have tried to recreate the container with the lastes images:

```
version: "3"
services:
  openvas:
    ports:
      - "8080:9392"
    environment:
      - "PASSWORD=admin"
      - "USERNAME=admin"
      - "QUIET=false"  # dump feed sync noise to /dev/null
    volumes:
      - "openvas_data:/data"
    container_name: openvas
    image: immauss/openvas:latest
volumes:
  openvas_data:
```

Now something seems not to be ok :D
```
########################################

Creating a base DB from /usr/lib/base-db.xz

base data from:

########################################

ERROR:  syntax error at or near ")"

LINE 1: CREATE AGGREGATE public.group_concat() (

                                             ^

ERROR:  syntax error at or near ")"

LINE 1: ALTER AGGREGATE public.group_concat() OWNER TO gvm;

                                            ^
```

But the tag is now right :)
`version | 22.4.13`

**Comment by TheUntouchable** [comment]
Here are the logs, container exited
[openvas_logs080523.txt](https://github.com/immauss/openvas/files/11424617/openvas_logs080523.txt)

**Comment by immauss** [comment]
You're still getting those permission denied errors. 

Try this. 

set:
DEBUG=true

This will cause the container to pause just before gvmd is started.

You can then go in the container with:
```
docker exec -it  -u gvm <container name> bash
```
This is the first error for the permissions issues.
/usr/local/sbin/greenbone-feed-sync: 337: cannot create /var/lib/gvm/scap-data/feed.xml: Permission denied

From there, you need to check your NFS config until you can write to: /var/lib/gvm/scap-data/ as the gvm user. 

Most of the processes run as gvm not root, hence the "-u gvm". Something in your NFS config is breaking the ability to write to that dir as it is soft linked to /data/var-lib/ which is the volume. 

I hope that helps. 

-Scott

**Comment by TheUntouchable** [comment]
Hey Scott,
sorry for the late response :)

Just a dump question from my side.. Did you read the correct log file..? =/
I can't see any entry in the last log I uploaded here regarding the access denied thing and also I am not using the NFS store anymore but a local one on the docker host :(
Funny thing is that after recreating the container with the lastest image today it seems to work at least for the local storage, will try if its also working with the NFS store now.

**Comment by TheUntouchable** [comment]
Okay, this time it stopped on a different step, but again the access denied thing..
[openvas_logs_100523.txt](https://github.com/immauss/openvas/files/11445515/openvas_logs_100523.txt)

**Comment by immauss** [comment]
Doh. You're right. I downloaded it, then looked at the old one. 
Yeah .. I was actively working on it, and it looks like you got one of the bum images that I pushed. 
The absolute latest, which is now 22.4.15 does not give the errors you showed. 

But the "Permission denied" is still the same problem. Your container cannot write to the volume.  does it start and run if you remove the volume section?

-Scott

**Comment by TheUntouchable** [comment]
What I really don't get is why the container can create a lot of directories and files but then it suddenly fails..

![grafik](https://github.com/immauss/openvas/assets/2162540/4fb732bb-2dd5-422a-b929-90d977849541)

![grafik](https://github.com/immauss/openvas/assets/2162540/a5189179-5471-4db1-bdef-15d85def5a9a)

**Comment by immauss** [comment]
User.
The command run at that time is "gvm-manage-certs", which is run as gvm. Everything before that is run as root. I'm thinking something in the docker config, but unfortunately, I have no idea what ...

**Comment by TheUntouchable** [comment]
I played a little with the nfs squash but then it was not even able to create the files for the database :D

**Comment by immauss** [comment]
but you're seeing the same thing with a local volume, so while there may be something else with NFS, you need to find why it can't write as gvm to a local volume first as that problem likely follows to the NFS volume.

**Comment by immauss** [comment]
Any luck ?

**Comment by TheUntouchable** [comment]
Hey immauss!
I am sorry, but to be honest I did not have the time to look deeper into this topic :(

**Comment by immauss** [comment]
No worries. 
Can we close this then?

**Comment by immauss** [comment]
Hmm ... looks like something went wonky with the builds. All three archs are x86_64 ... 
:/ 

I have to rebuild the whole pile.

-scott

**Comment by immauss** [comment]
DOH! 

Added a bit to my build scripts to only build the x86_64 when build beta to speed things along for testing .... 

I had the logic backwards......

:/ 

Fixed now and rebuilding all the archs on 22.4.26 tag.  Should take an hour or so.

**Comment by TheUntouchable** [comment]
I can now see a new version with the tag 22.4.26-slim, is this the right one? ;)

**Comment by TheUntouchable** [comment]
```
starting container at: Thu Aug 17 16:25:58 UTC 2023
Setting up container filesystem
cp: cannot stat '/usr/local/var/lib/*': No such file or directory
cp: cannot stat '/var/lib/gvm/*': No such file or directory
cp: cannot stat '/var/lib/notus/*': No such file or directory
cp: cannot stat '/var/lib/openvas/*': No such file or directory
Using default gvm logging config
Using default gvm logging config
Using default openvas logging config
Choosing container start method from:

Starting gvmd & openvas in a single container !!
Wait for redis socket to be created...
Testing redis status...
Redis ready.
Creating postgresql.conf and pg_hba.conf
Starting PostgreSQL...
waiting for server to start....2023-08-17 16:26:05.475 UTC [101] LOG:  redirecting log output to logging collector process
2023-08-17 16:26:05.475 UTC [101] HINT:  Future log output will appear in directory "/data/var-log/postgresql".
 done
server started
pg exit with 0 .
Checking for existing DB
Loading Default Database
Running first start configuration...
Generating certs...
Using /tmp/tmp.IMO74WYN9i to temporarily store files.
Creating new certificate infrastructure in automatic mode.
Generating private key.
Generated private key in /tmp/tmp.IMO74WYN9i/cakey.pem.
Generating certificate.
  Generating self signed certificate.
Generated self signed certificate in /tmp/tmp.IMO74WYN9i/cacert.pem.
  CA certificate generated.
Installing certificate and key.
Install destinations do not exist as directories, attempting to create them.
Setting up directories
mkdir: cannot create directory ‘/var/lib/gvm’: Permission denied
ERROR: Failed to create certificate directory (/var/lib/gvm/CA). Aborting.

Something new :D

![grafik](https://github.com/immauss/openvas/assets/2162540/90f25549-402b-4a7b-8f90-9f7e9a1ef0de)

```

**Comment by immauss** [comment]
What are the permissions at: ``` /mnt/openvas/data/var-lib/gvm``` 
 The certificate generation runs as the gvm user. It needs write permissions there to create the directories for the certs.

**Comment by immauss** [comment]
If you want to work on this again, please re-open. I'm closing it for now.
