### ISSUE TITLE
Scan completes properly but error in logs...

### ISSUE THREAD

**Issue by EverWin42O** [immauss/openvas#103]
Docker Image --> immauss/openvas:21.04.06
Host --> Ubuntu 20.04
Host Firewall --> Disabled

When scanned Windows Server -->

lib  misc:MESSAGE:2022-02-23 10h23.01 utc:45493: [gb_log4j_CVE-2021-44228_http_active.nasl] pcap_compile: Filter "tcp and dst port 18905 and src host 192.168.4.249 and (dst host 172.17.0.3 or dst host e80426672b6b)" : ethernet address used in non-ether expression
lib  nasl:MESSAGE:2022-02-23 10h23.01 utc:45493: [45493](/var/lib/openvas/plugins/2021/apache/gb_log4j_CVE-2021-44228_http_active.nasl:205) pcap_next: Could not get a bpf

When scanned Ubuntu system -->

Oops, ksba_cert_get_image failed: imagelen=50  hdr=4 len=734 off=0
lib  nasl:MESSAGE:2022-02-26 02h01.55 utc:137648: Unknown command 'public-key-algorithm-name' passed to cert_query

lib  nasl:MESSAGE:2022-02-26 02h08.15 utc:154116: [154116](/var/lib/openvas/plugins/2021/apache/gb_log4j_CVE-2021-44228_http_active.nasl:205) pcap_next: Could not get a bpf
lib  misc:MESSAGE:2022-02-26 02h08.15 utc:154116: [gb_log4j_CVE-2021-44228_http_active.nasl] pcap_compile: Filter "tcp and dst port 16725 and src host 192.168.4.252 and (dst host 172.17.0.3 or dst host e80426672b6b)" : ethernet address used in non-ether expression

**Comment by immauss** [comment]
You should try the greenbone community for this one. It looks like an error related to a specific NVT, not the container. 

https://community.greenbone.net/
