### ISSUE TITLE
Problem in postgresql.conf

### ISSUE THREAD

**Issue by enricotagliani** [immauss/openvas#104]
Hi! I'm trying the multi-container deployment. 
I noticed thet every time postgres container strarts, the default configuration settings are being appenend to `/data/database/postgresql.conf`.
Something like that:
```ini
listen_addresses = '*'
port = 5432

listen_addresses = '*'
port = 5432

listen_addresses = '*'
port = 5432

listen_addresses = '*'
port = 5432
```
So the configuration file is quickly becoming cluttered.
Also it would be great if it was possible to mount a custom postgres config in the container without it being overwritten or modified (as in such case).

BTW great job with your GVM docker image!

**Comment by immauss** [comment]
DOH !!
Thanks. That I will need to fix. In the single container, that's part of set of commands that only executes the first time the container comes up.

**Comment by immauss** [comment]
The "touch /setup" was missing in the start script for postgresql.

Thanks again!
