### ISSUE TITLE
Pulled latest image -> Openvas-scanner out of date ?

### ISSUE THREAD

**Issue by myhobby2** [immauss/openvas#108]
Thank you for supporting this container version. Using it now for some months, but I ran into this message below, causing a severity 10. 
I recreated the container and pulled the last image, assuming that I needed an upgraded image. But it did not solve it.

Version of installed component:           21.4.3
Latest available openvas-scanner version: 21.4.4

Anyone else running in the same ?

**Comment by LizardNerd** [comment]
You need to use the "21.04.07" tag, this image has the OpenVAS scanner
21.4.4

Il sab 26 mar 2022, 07:47 myhobby2 ***@***.***> ha scritto:

**Comment by myhobby2** [comment]
Thanks for your prompt support. Did use immauss/openvas:21.04.07 to rebuild my container and voila !

**Comment by sjwk** [comment]
Unless there's a reliability or other issue with 21.04.07, could 'latest' be updated to be the latest?  Normally if something is following the latest tag, you'd expect it to get updated when there's a new stable release (at least, that's *my* expectation!), and only use version-specific tags if you want to stick to a given version and not be updated?

**Comment by immauss** [comment]
@sjwk Well ... the 21.04.07 is still in testing really. There are few issues open on it, which is why I hadn't rolled it to the latest yet. It seems 21.04.06 is telling on itself ... so let me see if I can get this knocked out. 

Thanks,
Scott
