### ISSUE TITLE
Log spam since new build

### ISSUE THREAD

**Issue by TheUntouchable** [immauss/openvas#11]
First of all thank you for the quick solution in the last days, it seems that this is working again now! 👍 

Unfortunately, there now seem to be some problems with logging:

```
2020-09-14 12:15:00 | stdout | Updating NVTs...
2020-09-14 12:15:00 | stdout | <28>Sep 14 12:15:00 greenbone-nvt-sync: The log facility is not working as expected. All messages will be written to the standard error stream.
2020-09-14 12:15:00 | stdout | touch: cannot touch '/usr/local/var/run/feed-update.lock': Permission denied
2020-09-14 12:15:00 | stdout | <29>Sep 14 12:15:00 greenbone-nvt-sync: No Greenbone Security Feed access key found, falling back to Greenbone Community Feed
2020-09-14 12:15:00 | stdout | <29>Sep 14 12:15:00 greenbone-nvt-sync: Configured NVT rsync feed: rsync://feed.community.greenbone.net:/nvt-feed
```
The log file is now completely spammed with the download massages for each file :)

**Comment by immauss** [comment]
OK ... so the permissions where wrong on /usr/local/var/lib/run ... I'm forcing them now in start.sh. That fixes the nvt sync not being able to write in the run directory. 
The log facility error is just because it's running in a container. That's normal. 

As for the spammyness ... Are using a volume?  And those should only be there when you first start the container as the only time  the sync is run.  I could look for/create an option to add as a variable at container start to make the sync scripts less verbose. What do you think?

**Comment by immauss** [comment]
OK ... disregard ... I broke it ...

**Comment by immauss** [comment]
OK .... I brilliantly put the fix after the nvt scripts were called. 
Give docker about 10 - 20min to build a new one, and that should work. 

Sorry about that.

**Comment by TheUntouchable** [comment]
All is well! Thanks for the quick solution :D

**Comment by immauss** [comment]
no worries. 
Thank you

**Comment by TheUntouchable** [comment]
Unfortunately I cannot start the container now :( And yes, I use a volume :)

![grafik](https://user-images.githubusercontent.com/2162540/93131363-3a4f5a00-f6d4-11ea-9a8b-14e3da2ab787.png)

**Comment by immauss** [comment]
OK ... my bad..... 
I've fully tested the most recent in my own production environment.  Including running a few scans. So hopefully ...... It will work for you too.

**Comment by TheUntouchable** [comment]
The container is working now again, thanks!
But the logspam on the first time is also back 🤣 But take your time, that is not that important ;)

**Comment by immauss** [comment]
Yes

**Comment by immauss** [comment]
Yes... I need a little more time to work out how to quiet that without breaking anything else. Might be this weekend before I get a chance to poke at it again.

**Comment by TheUntouchable** [comment]
Like I said before, take your time :)

**Comment by immauss** [comment]
The latest 20.08.3 includes the QUIET environment variable.

**Comment by TheUntouchable** [comment]
Thanks a lot for that! :)
