### ISSUE TITLE
ARF reports not able to see when imported

### ISSUE THREAD

**Issue by harshatalele** [immauss/openvas#110]
Hi,

I have imported ARF report format in through report Report formats and also mark the status as active (Refer screen
![openvas](https://user-images.githubusercontent.com/66482175/162387382-6bf09a76-51f8-4ded-b442-d2d065d58aa0.jpg)

Later on I performed an scan to target machine. After scan completed, I wanted to download the report format in ARF, but I am not able to see the ARF report format there. 

<img width="797" alt="openvas ARF report format not shown" src="https://user-images.githubusercontent.com/66482175/162387954-5d13f2cb-b95b-4563-9a20-6aadcec37538.png">

Steps I followed
1. Login to Openvas->Report formats from configurations-> mark status as active and provided the permission of read and write
2. Perform scan,
3. once scan finished, under scan->reports->selected the relevant task-> click on download filtered report and check ARF not present in dropdown.
Kindly help me to sort this out. 
Also ,I assume I am following correct steps here 
Note:- I have restarted docker as well post uploading ARF report format

ARF report format sample

[ARF Report format.zip](https://github.com/immauss/openvas/files/8449700/ARF.Report.format.zip)

Can someone please help here 
Os details:- ubuntu 20.04 
GSA:- 21.4.3

**Comment by immauss** [comment]
If you haven't already seen the response on the community forum, it seems the ARF reports are only functional on the paid products from Greenbone. Sorry.
