### ISSUE TITLE
Scan remain 15 minutes on queued instead of start immediately

### ISSUE THREAD

**Issue by JoseW3b** [immauss/openvas#112]
Hi everybody,

anyone knows if there is some reason why the scan doesn't start immediately??? it runs over last immauss docker. After that 15 minutes it start and ends correctly. docker has enough resources. progress pass from requested to queued (a lot of time).

thanks in advance

**Comment by immauss** [comment]
Are you seeing that delay in the logs, or via the web interface? 
if web, check to see if the logs show the same, it could just be a delay in the web interface updating.  If not, you might want to check on the community forum.

**Comment by immauss** [comment]
Yes. This is normal. Once you have the most recent data from Greenbone, it goes quite a bit faster. I've preloaded relatively recent copies of the data into the base image. If you start the container with -e SKIPSYNC=true , then you should get an operational scanner much quicker.
