### ISSUE TITLE
StartTLS failed, trying to establish ldaps connection

### ISSUE THREAD

**Issue by MrNobody-hub** [immauss/openvas#113]
Hello, first of all thank you for all your hard work and to bring us this container that it has been really helpful for us. 

We are trying to implement the Authentication of the scanner using LDAP, I have uploaded the certificate that we use for LDAP server in the scanner and I have installed ldapsearch also. I have enabled the users to authenticate using LDAP in the scanner and ldapsearch works because I am able to query from the LDAP server. However, when I use my ldap credentials to authenticate against the scanner it does not work. Checking the scanner logs I found the next: 

libgvm util:WARNING:2022-04-19 12h09.49 utc:8373: StartTLS failed, trying to establish ldaps connection.
libgvm util:WARNING:2022-04-19 12h09.49 utc:8373: LDAP authentication failure: Can't contact LDAP server.

I might be doing something wrong, not sure if you can assist me with this issue.

Thanks in advance

**Comment by immauss** [comment]
Sorry, but this way outside my experience and not really container specific. You should probably ask about this on the community forum. 
https://community.greenbone.net.
