### ISSUE TITLE
db insecure

### ISSUE THREAD

**Issue by boesr** [immauss/openvas#116]
Is there a way to secure the database with a password? Did not found one, yet.

**Comment by immauss** [comment]
Not that I'm aware of. 

The standard setup from Greenbone uses local unix sockets. 
It's something I've been meaning to look into myself. They have recently added these options to gvmd:

  -d, --database=<name>                         Use <name> as database for PostgreSQL.
  --db-host=<host>                              Use <host> as database host or socket directory for PostgreSQL.
  --db-port=<port>                              Use <port> as database port or socket extension for PostgreSQL.
  --db-user=<user>                              Use <user> as database user.

 which implies you could use a TCP connection to postgresql, though I've not had time to try it yet, but still no password. 

Maybe ask over on the community forum:
https://community.greenbone.net

-Scott
