### ISSUE TITLE
Databases aren't update correctly

### ISSUE THREAD

**Issue by LizardNerd** [immauss/openvas#118]
Hi there, I'm using the latest immauss OpenVAS image. The DBs are not update correctly after run the container for the very first time or after a container restart. 
Some logs:

![openvas#1](https://user-images.githubusercontent.com/79976861/166211602-2e3f59bc-8a10-447f-9fc7-0c343fd130e5.png)

![openvas#2](https://user-images.githubusercontent.com/79976861/166211630-be5c5fd1-6691-4b08-9286-074a56319dbd.png)

![openvas#3](https://user-images.githubusercontent.com/79976861/166211701-b0dd967c-a47a-41a1-b484-14ad708e9a55.png)

P.S: I'm not using compose file

**Comment by immauss** [comment]
Yep. 

That's normal. 

the GVMD_DATA feed will be that way probably until the next major version from Greenbone. See this thread on the community forums. 

https://community.greenbone.net/t/gvmd-data-too-old-34-days-please-check-the-automatic-synchronization-of-your-system/7565/24
