### ISSUE TITLE
Starting Socket on Mac OSX Monterey Persistent Volume

### ISSUE THREAD

**Issue by phydroxide** [immauss/openvas#119]
Hi, 
I've used immaus/openvas:latest on Linux, but now I'd like to run it from Docker on OSX Monterey. 

For whatever reason it won't login with the admin password I set. I've done a number of things to troubleshoot, which brings me to the issue of focus.

Each time I restart the container to troubleshoot it takes between 20-30 minutes to sync nvt etc. 
This is in spite of me having used `-v /ABS/PATH/data:/data`

I was hoping this would be resolved by using a named volume from Docker, but the image appears not to work on this volume type. 

```
docker run  --publish 9392:9392 -e PASSWORD="<PASSWORD>" --name openvas2022  -v  openvas:/data immauss/openvas:latest
```

```
########################################
Creating a base DB from /usr/lib/base-db.xz
base data from:
Tue Nov 30 19:52:49 UTC 2021
########################################
2022-05-03 19:57:27.985 GMT [153] FATAL:  could not write init file
\connect: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  could not write init file
```

 So a few questions
 1) Is a persistent volume the right way to fix the fact that docker stop/docker start includes a 20 minute sync?
 2) Is using a bind mount preferable over using a named volume from docker? Is changing this going to be the wrong approach to fix my long-sync problem?
 3) Are you familiar enough with docker volumes to know whether they support Postgres sockets the way this image uses them?
 4) Are you familiar with running it on OSX to know why authentication would fail? (Error output pending, I'm still waiting for it to sync)

**Comment by phydroxide** [comment]
```(gsad:1176): gsad  gmp-WARNING **: 23:15:25.457: Authentication failure for 'admin' from 172.17.0.1. Status was 1.```

**Comment by phydroxide** [comment]
```# whoami
root
# /usr/local/sbin/gvmd --user=admin --new-password=new-password```

```md   main:MESSAGE:2022-05-03 23h16.19 utc:1194:    Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
md manage:   INFO:2022-05-03 23h16.19 utc:1194:    Modifying user password.
md manage:WARNING:2022-05-03 23h16.19 utc:1194: sql_open: PQconnectPoll failed
md manage:WARNING:2022-05-03 23h16.19 utc:1194: sql_open: PQerrorMessage (conn): connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "root" does not exist
md manage:WARNING:2022-05-03 23h16.19 utc:1194: init_manage_open_db: sql_open failed```

**Comment by phydroxide** [comment]
```# su postgres
postgres@a1414a02beb4:/$ /usr/local/sbin/gvmd --user=admin --new-password=new-password```

```md   main:MESSAGE:2022-05-03 23h17.21 utc:1201:    Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
md manage:WARNING:2022-05-03 23h17.21 utc:1201: Failed to open lock file '/run/gvmd/gvm-checking': Permission denied
md   main:CRITICAL:2022-05-03 23h17.21 utc:1201: gvmd: Error trying to get checking lock```

**Comment by immauss** [comment]
Odd ... 
First thing to remember: Docker Desktop is a virtual machine running Linux using hyperkit on MacOS. So while you are on a Mac, Docker is still running on linux. The volumes are still created on a Linux host, so it should function exactly the same. 

I just copy/pasted your start command to my Mac running 12.2.1 ( Montery) and the latest Docker desktop and it worked fine. The only thing I can thing of at the moment is to make sure you are starting with a clean empty volume. Using a volume ( either local or docker managed) is the right answer to speeding up your start times. Though if you are in a real hurry, you can also start with "-e SKIPSYNC=true" and it will just not run the feed sync and instead rely on feeds included in the image. At the moment, that data is less than week old. I try to refresh it once a week. 

As for bind vs named(docker managed) volumes, functionally and operationally there is little difference. With a bind mount, it's certainly easier to find the files though. With the DockerDestop, when using docker managed volumes, the data actually resides on the VM filesystem, so the only easy way to get to them is via a container. 

As for the auth failure, it looks like your real problem is postgres not starting. The sockets should function properly regardless. It's possible there is permission problem somewhere. These "should" get fixed on container start, but it wouldn't be the first time. Please try to first start the container with NO volume. You can use the "-e SKIPSYNC=true" to get to operation quicker. If you still have problems with postgresql starting and login failure, then there is something seriously wrong and I need to figure out what. If instead that works, start a new container the same as you did before, but make sure you are using a completely blank volume. (just give it a new name and docker will create it. ) If that fails, delete the volume and try again without specifying the password. I'm pretty sure that code still works, but I've not tested it in a while, so it could be that something recently broke it. 

Thanks,
Scott

**Comment by phydroxide** [comment]
When I run it without a volume:
```
2022-05-04 14:42:59.805 GMT [155] WARNING:  could not create relation-cache initialization file "base/1/pg_internal.init.155": No space left on device
```

That's what started me down this road.  

I'm remembering now something about docker volume size defaults.. haven't tried that. But, I've cleaned that up to the best of my knowledge.  

```docker volume rm ....```
```docker container rm ....```
```docker builder prune ...```

It appears to work if I don't use a persistent volume. 

I'm going to chalk it up to my system being right on the boundary of storage limitations since I'm not picking up on any remarkable errors other than the auth failure. 


```
########################################
Creating a base DB from /usr/lib/base-db.xz
base data from:
Thu Apr 28 11:14:11 UTC 2022
########################################
2022-05-04 15:03:29.643 GMT [163] ERROR:  canceling autovacuum task
2022-05-04 15:03:29.643 GMT [163] CONTEXT:  automatic analyze of table "gvmd.scap.cpes"
NOTICE:  relation "vt_severities" already exists, skipping
Unpacking base feeds data from /usr/lib/var-lib.tar.xz
NOTICE:  relation "vt_severities" already exists, skipping
NOTICE:  relation "vt_severities" already exists, skipping
Migrating the database to the latest version if needed.
Starting Greenbone Vulnerability Manager...
Waiting for gvmd
Waiting for gvmd
admin
Time to fixup the gvm accounts.
Setting admin password
reset
Starting Postfix for report delivery by email
Starting Postfix Mail Transport Agent: postfix.
Starting Open Scanner Protocol daemon for OpenVAS...
Starting Greenbone Security Assistant...
Oops, secure memory pool already initialized
gsad main-Message: 15:18:06.628: Starting GSAD version 21.4.4

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Your GVM/openvas/postgresql container is now ready to use! +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

gvmd --version
Greenbone Vulnerability Manager 21.4.5
Manager DB revision 242
Copyright (C) 2009-2021 Greenbone Networks GmbH
License: AGPL-3.0-or-later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Image DB date:
Thu Apr 28 11:14:11 UTC 2022
Versions:
gvmd=v21.4.5
openvas=v21.4.4
openvas_smb=v21.4.0
gvm_libs=v21.4.4
gsa=v21.4.4
ospd=v21.4.4
ospd_openvas=v21.4.4
gvm_tools=v21.10.0
python_gvm=v21.11.0
++++++++++++++++
+ Tailing logs +
++++++++++++++++
==> /usr/local/var/log/gvm/gvmd.log <==
md   main:MESSAGE:2022-05-04 15h17.52 utc:294:    Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
md   main:WARNING:2022-05-04 15h17.52 utc:294: gvmd: Another process is busy starting up
libgvm util:   INFO:2022-05-04 15h17.52 utc:286: starting key generation ...
libgvm util:WARNING:2022-05-04 15h17.52 utc:286: error creating OpenPGP key 'GVM Credential Encryption': No agent running <GnuPG>
libgvm util:MESSAGE:2022-05-04 15h17.52 utc:286: error searching for OpenPGP key 'GVM Credential Encryption': Not found
md   main:CRITICAL:2022-05-04 15h17.52 utc:286: gvmd: failed to initialise GMP daemon
md   main:MESSAGE:2022-05-04 15h17.53 utc:315:    Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
md manage:   INFO:2022-05-04 15h17.53 utc:315:    Getting users.
md   main:MESSAGE:2022-05-04 15h17.57 utc:320:    Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
md manage:   INFO:2022-05-04 15h17.57 utc:320:    Modifying user password.

==> /usr/local/var/log/gvm/openvas.log <==

==> /usr/local/var/log/gvm/ospd-openvas.log <==
OSPD[962] 2022-05-04 15:18:05,597: INFO: (ospd.main) Starting OSPd OpenVAS version 21.4.5.dev1.

==> /usr/local/var/log/gvm/redis-server.log <==
75:C 04 May 2022 14:59:02.811 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
75:C 04 May 2022 14:59:02.812 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=75, just started
75:C 04 May 2022 14:59:02.814 # Configuration loaded
75:M 04 May 2022 14:59:02.817 # Server initialized

==> /usr/local/var/log/gvm/openvas.log <==
libgvm util:MESSAGE:2022-05-04 15h23.35 utc:988: Updated NVT cache from version 0 to 202204281000
2022-05-04 15:24:07.253 GMT [1017] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted
2022-05-04 15:30:45.855 GMT [92] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted
2022-05-04 15:31:45.858 GMT [92] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted
2022-05-04 16:06:46.539 GMT [1181] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted
2022-05-04 16:20:46.785 GMT [1242] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted

(gsad:979): libgvm util-WARNING **: 16:26:27.910: Failed to connect to server

(gsad:979): gsad  gmp-WARNING **: 16:26:27.911: Authentication failure for 'admin' from 172.17.0.1. Status was 1.
2022-05-04 16:26:46.869 GMT [1263] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted
```

The SKIPSYNC=true was something I missed before and was super helpful in working faster through the failures. I had been trying to dig through the individual scripts, to circumvent those,  and this is what I needed.  

THANKS!

**Comment by immauss** [comment]
You could also use : 
```
docker image purge
```
To clear out unused blobs from your container registry. 

-Scott

**Comment by phydroxide** [comment]
Did that. Still having some trouble logging in when I use persistent volumes. I've been playing around with /start.sh, launching pieces one by one and this is what I've come up with:

Login fails with:

> The Greenbone Vulnerability Manager service is not responding. This could be due to system maintenance. Please try again later, check the system status, or contact your system administrator.

![image](https://user-images.githubusercontent.com/31145228/167185776-9c420b5e-549e-4289-86dd-d52799b9aec2.png)

gsad says:
```(gsad:5086): libgvm util-WARNING **: 17:40:01.829: Failed to connect to server

(gsad:5086): gsad  gmp-WARNING **: 17:40:01.829: Authentication failure for 'admin' from 172.17.0.1. Status was 1.```


![image](https://user-images.githubusercontent.com/31145228/167185933-368ba646-ca31-43a6-9f01-4d46c826b601.png)

gvmd is not running on 9390

![image](https://user-images.githubusercontent.com/31145228/167186978-d7955f24-6bce-43ca-a19d-30b7510f8c75.png)

```Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      4359/postgres
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      5063/master
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      4348/redis-server 1
tcp6       0      0 :::9392                 :::*                    LISTEN      5086/gsad
tcp6       0      0 :::5432                 :::*                    LISTEN      4359/postgres
tcp6       0      0 :::25                   :::*                    LISTEN      5063/master
tcp6       0      0 172.17.0.2:9392         172.17.0.1:58816        ESTABLISHED 5086/gsad
tcp6       0      0 172.17.0.2:9392         172.17.0.1:58820        ESTABLISHED 5086/gsad
tcp6       0      0 172.17.0.2:9392         172.17.0.1:58818        ESTABLISHED 5086/gsad
udp        0      0 127.0.0.1:41719         127.0.0.1:41719         ESTABLISHED 4359/postgres
Active UNIX domain sockets (servers and established)```

On the container without persistant storage it does:
```tcp        0      0 0.0.0.0:9390            0.0.0.0:*               LISTEN      162/gvmd: Waiting f```
```gvm        162  0.4  0.0 292380   868 ?        S    17:49   0:00 gvmd: Waiting for incoming connections
gvm        193 10.5 31.1 853012 632648 ?       R    17:49   0:11 gvmd: Syncing SCAP: Updating CVEs```

Running it manually on the container with persistent volume

```su -c "gvmd  -a 0.0.0.0 -p 9390 --listen-group=gvm  --osp-vt-update=/var/run/ospd/ospd.sock --max-email-attachment-size=64000000 --max-email-include-size=64000000 --max-email-message-size=64000000" gvm``

 emits that PGP error:
 
```
md   main:MESSAGE:2022-05-06 17h46.51 utc:5193:    Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
libgvm util:   INFO:2022-05-06 17h46.52 utc:5194: starting key generation ...
libgvm util:WARNING:2022-05-06 17h46.52 utc:5194: error creating OpenPGP key 'GVM Credential Encryption': No agent running <GnuPG>
libgvm util:MESSAGE:2022-05-06 17h46.52 utc:5194: error searching for OpenPGP key 'GVM Credential Encryption': Not found
md   main:CRITICAL:2022-05-06 17h46.52 utc:5194: gvmd: failed to initialise GMP daemon```

Compared to 

```==> /usr/local/var/log/gvm/gvmd.log <==
md   main:MESSAGE:2022-05-06 17h55.55 utc:1059:    Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
md manage:   INFO:2022-05-06 17h55.55 UTC:1083: OSP service has different VT status (version 202205061016) from database (version 0, 0 VTs). Starting update ...
md manage:   INFO:2022-05-06 17h55.56 UTC:1082: update_scap: Updating data from feed
md manage:   INFO:2022-05-06 17h55.56 UTC:1082: Updating CPEs
libgvm util:WARNING:2022-05-06 17h55.56 UTC:1082: gvm_file_copy: g_file_copy(/var/lib/gvm/scap-data/official-cpe-dictionary_v2.2.xml, split.xml) failed - Error splicing file: No space left on device
md manage:WARNING:2022-05-06 17h55.56 UTC:1082: update_scap_cpes: Failed to split CPEs, attempting with full file```

**Comment by phydroxide** [comment]
Excuse the spam. Adding some hard-won notes. 
Container launched without persistent volume:

```
docker run  --publish 9392:9392  -e PASSWORD="<PASSWORD>" --name openvastemp    --mount type=tmpfs,destination=/tmp   -e DEBUG=true -e SKIPSYNC=true  -v /Users/philip.waters/persist:/data immauss/openvas:latest
```

```
root       426  0.0  0.0   5204   700 pts/0    S+   22:42   0:00      \_ grep gpg-agent
Here is where gvmd starts
Starting Greenbone Vulnerability Manager...
root       434  0.0  0.0   5204   644 pts/0    S+   22:42   0:00      \_ grep gpg-agent
admin
Time to fixup the gvm accounts.
Setting admin password
reset
root       474  0.0  0.0   5204   640 pts/0    S+   22:42   0:00      \_ grep gpg-agent
gvm        453  3.7  0.0  79952  1488 ?        Ss   22:42   0:00 gpg-agent --homedir /var/lib/gvm/gvmd/gnupg --use-standard-socket --daemon
```

Started with Persistence:

```
docker run --user root --privileged  --publish 9392:9392  -e PASSWORD="<PASSWORD>" --name openvasdebug    --mount type=tmpfs,destination=/tmp  -v /Users/<user>/openvas_persist:/data -e DEBUG=true   immauss/openvas:latest
```
```
Here is where gvmd starts
Starting Greenbone Vulnerability Manager...
Before Account Fixup
root       854  0.0  0.0   5204   700 pts/0    S+   23:20   0:00          \_ grep gpg-agent
admin
Time to fixup the gvm accounts.
Setting admin password
reset
After Account Fixup
root       886  0.0  0.0   5204   708 pts/0    S+   23:21   0:00          \_ grep gpg-agent
```

```
# su -c "gpg-agent --homedir /var/lib/gvm/gvmd/gnupg --use-standard-socket --daemon" gvm
gpg-agent[1559]: WARNING: "--use-standard-socket" is an obsolete option - it has no effect
gpg-agent[1559]: error binding socket to '/var/lib/gvm/gvmd/gnupg/S.gpg-agent': Invalid argument
# gpg-agent --homedir /var/lib/gvm/gvmd/gnupg --use-standard-socket --daemon
gpg-agent[1560]: WARNING: "--use-standard-socket" is an obsolete option - it has no effect
gpg-agent[1560]: error binding socket to '/var/lib/gvm/gvmd/gnupg/S.gpg-agent': Invalid argument
```

```
gpg-agent[772]: error binding socket to '/var/lib/gvm/gvmd/gnupg/S.gpg-agent': Invalid argument
```

**Comment by immauss** [comment]
So ... my apologies for missing this earlier. If you are starting with the DEBUG=true, gvmd does not start.  That option came about when I was having problems with gvmd starting. It owuld fail tos tart, and the container would die. That option pauses just before gvmd starts so I could get into the container and troubleshoot why gvmd was not starting. Without gvmd to perform the authentication, you can't login to gsad. I should make that clearer somewhere, or maybe look at a different "DEBUG" option . . . .

Thanks,
-Scott

**Comment by phydroxide** [comment]
Yes. I knew that. I should have been more clear this happens with or without DEBUG.
With DEBUG I run /start.sh manually after stopping most of the process except tail. 

My next step is to see if I can duplicate the open PGP issue with a similar raw base container. I know I’m missing something basic, likely unrelated to the gvm software.

**Comment by immauss** [comment]
Have you had any luck ? 

I'm still not able to reproduce your errors. 

Thanks,
Scott

**Comment by phydroxide** [comment]
In order to make this work I have to specify a specific mount for the gpg home directory the script calls, and then overwrite the seeded key collateral that the mount clobbers:

``` 
--mount type=tmpfs,destination=/var/lib/gvm/gvmd/gnupg
#pwd
/data/var-lib/gvm/gvmd/gnupg
# cp -r * /var/lib/gvm/gvmd/gnupg
# chown gvm.gvm /var/lib/gvm/gvmd/gnupg
#su -c "gvmd  -a 0.0.0.0 -p 9390 --listen-group=gvm  --osp-vt-update=/var/run/ospd/ospd.sock --max-email-attachment-size=64000000 --max-email-include-size=64000000 --max-email-message-size=64000000" gvm

```
Otherwise gnugpg doesn't start. 

```
 gpg-agent --homedir ./ --daemon
gpg-agent[901]: error binding socket to '/data/var-lib/gvm/gvmd/gnupg/S.gpg-agent': Invalid argument
```
```
root@f47d2d3eb1e0:/var/lib/gvm/gvmd/gnupg# gpg-agent --homedir /tmp --daemon
gpg-agent[1997]: directory '/tmp/private-keys-v1.d' created
gpg-agent[1998]: gpg-agent (GnuPG) 2.2.27 started
```

I cannot tell why, though I suspect it has something to do with docker mount types not allowing sockets. 

I'm not familiar enough with mounting persistent volumes with docker client to know the right mount options to specify to make it "just work (r)" I suspect I'm missing something simple, if you have a sample you can provide that you know works on the newest Mac OS that might help.

```
docker run --user root --privileged  --publish 9392:9392 -e SKIPSYNC=true -e PASSWORD=foo --name openvas2022    --mount type=tmpfs,destination=/var/lib/gvm/gvmd/gnupg --mount type=tmpfs,destination=/tmp   -v /full/data/path/data:/data  immauss/openvas:latest

``` 
As part of my hack, I had to move some things around like the paths for certificates etc. I haven't looked into why, I'm just following the errors and hacking fixes as they come to try to get the server to start, which it does. 
 

```
libgvm util:   INFO:2022-06-20 17h38.49 utc:839: starting key generation ...
libgvm util:WARNING:2022-06-20 17h38.49 utc:839: error creating OpenPGP key 'GVM Credential Encryption': Permission denied <GnuPG>
libgvm util:MESSAGE:2022-06-20 17h38.49 utc:839: error searching for OpenPGP key 'GVM Credential Encryption': Not found
md   main:CRITICAL:2022-06-20 17h38.49 utc:839: gvmd: failed to initialise GMP daemon
```

```
root@d2389b4a5152:/var/lib/gvm/gvmd/gnupg# chown gvm.gvm ./
```


```
libgvm util:   INFO:2022-06-20 17h49.15 utc:1695: starting key generation ...
libgvm util:WARNING:2022-06-20 17h49.15 utc:1695: error creating OpenPGP key 'GVM Credential Encryption': Permission denied <GnuPG>
libgvm util:MESSAGE:2022-06-20 17h49.15 utc:1695: error searching for OpenPGP key 'GVM Credential Encryption': Not found
```

```
root@d2389b4a5152:/var/lib/gvm/gvmd/gnupg# chown gvm.gvm ./
```

```
libgvm util:WARNING:2022-06-20 18h03.29 utc:1817: server_new_internal: failed to set credentials key file: Error while reading file.
libgvm util:WARNING:2022-06-20 18h03.29 utc:1817: server_new_internal:   cert file: /var/lib/gvm/CA/servercert.pem
libgvm util:WARNING:2022-06-20 18h03.29 utc:1817: server_new_internal:   key file : /var/lib/gvm/private/CA/serverkey.pem
```

```
root@d2389b4a5152:/var/lib/gvm# pwd
/var/lib/gvm
root@d2389b4a5152:/var/lib/gvm# ln -s gvm/private/ private
root@d2389b4a5152:/var/lib/gvm# ln -s gvm/CA/ CA
```

**Comment by immauss** [comment]
I still don't understand what lead you down this path. My Mac OS Montery with Docker Desktop runs the container fine with just:
```
docker run -d -v $(pwd)/data:/data --name openvas -p 9392:9392 -e SKIPSYNC=true immauss/openvas
```

And it works fine with named volumes as well. 

```
docker run -d -v openvas:/data --name openvas -p 9392:9392 -e SKIPSYNC=true immauss/openvas
```

No problems with socket creation on either one and it was up in about 34 minutes.  Are you using something other than the default file systems on your Mac? Even so, if it were a MacOS file system problem, using the named volume would eliminate that as an issue. Maybe something in your Docker Desktop config that's out of the ordinary? 

-Scott

**Comment by immauss** [comment]
How much memory/cpu do you have allocated for your Docker desktop VM in the "Resources" section? 
Mine is 8 cores & 8 GB of RAM. 

-Scott

**Comment by immauss** [comment]
Thanks for the follow up. Please let me know if you have any other issues, or if you work out what happened here. 

Thanks,
Scott
