### ISSUE TITLE
Failed to connect to server at /usr/local/var/run/gvmd.sock: Too many levels of symbolic links

### ISSUE THREAD

**Issue by felimwhiteley** [immauss/openvas#12]
https://github.com/immauss/openvas/blob/facbd0d8e7d1c5085686e3077a468c8c4c789e63/scripts/start.sh#L172

/var/run -> /run
/usr/local/var/run -> /run

The symlink is causing an error

gsad  gmp:WARNING:2020-09-15 11h38.30 utc:555: Failed to connect to server at /usr/local/var/run/gvmd.sock: Too many levels of symbolic links
gsad  gmp:WARNING:2020-09-15 11h38.30 utc:555: Authentication failure for 'admin' from 172.16.12.102. Status was 1.

As the various run dirs are pointing back to /run anyway  the whole stanza should be removable, no?

**Comment by immauss** [comment]
Sorry about that. That one got out to docker before it was fully tested. 
I've updated, and the image on docker should be good now as well as what is here on Github. 
In short, I had to change permissions of /usr/local/var/run to 777 to prevent other errors. 
This is an ugly fix, but it gets everything in the container working in production for now while I find a better fix.

**Comment by felimwhiteley** [comment]
Yeah no worries, makes sense alright
