### ISSUE TITLE
Automating through gvm-cli

### ISSUE THREAD

**Issue by Simon-Davies** [immauss/openvas#122]
Hi mate,

Yesterday I got a shell on the docker container and realised that the Unix Socket: gdvm.sock is not present. How do I connect, authenticate and start scans using gvm-cli using your docker version of OpenVAS?

**Comment by Simon-Davies** [comment]
As far as I can see I am using the single container docker image. I used the below command to get it up and running:

`docker run --detach --publish 8080:9392 -e PASSWORD="Testing123!" --volume openvas:/data --name openvas immauss/openvas`

**Comment by immauss** [comment]
I’ve not done much with this yet, but you can connect to gvmd via port 9390. I ‘think’ it’s the ssl option for the cli. I might have some time to try this out early next week. It’s been really busy around here lately. Sorry.

**Comment by prbond** [comment]
Hi,

I am interessed about this subjet too, and thanks for information.

I tested and it's works :

`gvm-cli --gmp-username admin --gmp-password "PASSWORD" tls --xml "<get_version/>"`

Bye
