### ISSUE TITLE
Pull error 'GetADUsers.py: no such file or directory'

### ISSUE THREAD

**Issue by tpaiii3** [immauss/openvas#123]
I got the error as below

========================

 sudo docker pull immauss/openvas:latest
Trying to pull repository docker.io/immauss/openvas ...
latest: Pulling from docker.io/immauss/openvas
dbba69284b27: Pull complete
cbfbd3b2833c: Pull complete
5719d8336228: Extracting [==================================================>] 433.7 MB/433.7 MB
5a12d969a3b0: Download complete
e2ad1309e6a2: Download complete
d297c6168911: Download complete
aa4656d13d25: Download complete
e860f1cc4295: Download complete
9dff7f55ce2e: Download complete
e2de974a2906: Download complete
11239a22177d: Download complete
1be30d130568: Download complete
15bad981ed26: Download complete
63fc874713bc: Download complete
c4d0b20a7815: Download complete
1aec80dec0cd: Download complete
74ecf4c50788: Download complete
71b9b6431a2d: Download complete
4f4fb700ef54: Download complete
ed8aef9aa1a1: Download complete
**failed to register layer: Error processing tar file(exit status 1): lchown /usr/share/doc/python3-impacket/examples/GetADUsers.py: no such file or directory**

**Comment by immauss** [comment]
This looks like you might need to free up some disk space. I just deleted and re-pulled the image from Docker Hub with no issue, so the image there is good. 

try:
docker image prune 

and make sure you don't have a ton of unused images/volumes. 

Please let me know if that resolves the issue. 

Thanks,
Scott

**Comment by tpaiii3** [comment]
This file was quarantined by anti-malware. It's working now after including it in whitelist file into the anti-malware configuration.

**Comment by immauss** [comment]
Thanks for the update! And I'm glad you worked it out.
