### ISSUE TITLE
Time zone ?

### ISSUE THREAD

**Issue by LeoNidas54** [immauss/openvas#124]
Hello, first of all I wanted to congratulate the work done for this image and the openvas community! 
I would like to know if there is a way to change the time zone ? (utc+2 for me)
Thanks !

**Comment by kjake** [comment]
I define an environment variable in my docker compose, which I think has been working

TZ="America/New_York"

**Comment by immauss** [comment]
by default, containers will run with the time zone set as UTC. 
To change it, You can either use:

```
-e TZ=“time zone name”
```

On the command line. 

Or in docker-compose.yml

```
environment:
  - TZ=America/Denver
 ```

Please let me know if that works for you.
