### ISSUE TITLE
issue with openVAS scanner

### ISSUE THREAD

**Issue by farzadha2** [immauss/openvas#126]
HI i was wondering if someone else has had this issue before,
Currently it was working fine, i restarted the docker and on the logs it keeps saying

`md manage:   INFO:2022-06-17 04h04.22 UTC:1891: osp_scanner_feed_version: failed to get scanner_feed_version. OSPd OpenVAS is still starting`

Thank you

**Comment by rdtm443** [comment]
Hello there!

Unfortunately I can't help you right away. But just to let you know, I have exactly the same issue. Might be due to a missing link I think. But no idea...

**Comment by immauss** [comment]
In my xp, this message stops repeating after everything is updated, and everything works fine. Mske sure  you are giving gvmd enough time to update. 

For some reason, even with a preloaded DB, the latest versions are take 20+  minutes to be ready. I haven't been able to work out whey. It seems to be somethign with ospd loading the NVTs ....

-Scott

**Comment by rdtm443** [comment]
> In my xp, this message stops repeating after everything is updated, and everything works fine. Mske sure  you are giving gvmd enough time to update. 
> 
> For some reason, even with a preloaded DB, the latest versions are take 20+  minutes to be ready. I haven't been able to work out whey. It seems to be somethign with ospd loading the NVTs ....
> 
> -Scott
> 

Hey Scott. Many thanks for your reply!

Actually I have waited quite a lot more than 20min for everything to be synced. Still got stuck at 0%. Running it in a Kali VM, 10GB of memory assigned. 

But I will give it another try, as I really would love to get that thing up and running.

So basically only these following two commands are needed after having docker.io installed, right?

docker volume create openvas

docker run --detach --publish 8080:9392 -e PASSWORD="admin" --volume openvas:/data --name openvas immauss/openvas

This will pull by default the image with ":latest" tag, which was updated two months ago. There is one with ":21.04.09", updated 16 days ago. 

What is now the better, more stable version? Can we go with latest, as per command above?

Sorry, reply got quite lengthy.. Thanks very much!

Best

**Comment by farzadha2** [comment]
hi again, so it seems that it does take a while around half an hour it starts working agani

**Comment by rdtm443** [comment]
..just to close the loop: for me it is working as well (with above commands, :latest). Just had to be super patient :)Thanks again for this super docker image, Scott !!

Best

**Comment by immauss** [comment]
:) 

Thanks. Glad it's working for you!
