### ISSUE TITLE
Latest docker image doesn't start on Centos 7.9

### ISSUE THREAD

**Issue by infestdead** [immauss/openvas#130]
I tried updating the docker image, after that it didn't ran, so I tried deleting everything and running clean, no volumes, no extra options, still doesn't want to start up.

CentOS Linux release 7.9.2009 (Core)

```
[root@openvas ~]# docker pull immauss/openvas
Using default tag: latest
Trying to pull repository docker.io/immauss/openvas ... 
latest: Pulling from docker.io/immauss/openvas
Digest: sha256:7f7cdbc050115b33ddd04c2a5af7fb9607c214c5a1b12fafbe5a04112c7fc558
Status: Image is up to date for docker.io/immauss/openvas:latest

[root@openvas ~]# docker inspect immauss/openvas| grep version
                "version": "21.04.09"

[root@openvas ~]# docker rm openvas
Error response from daemon: No such container: openvas

[root@openvas ~]# docker run immauss/openvas
Setting up contianer filesystem
cp: cannot stat '/usr/local/var/lib/*': No such file or directory
cp: cannot stat '/var/lib/gvm/*': No such file or directory
cp: cannot stat '/var/lib/openvas/*': No such file or directory
Using default gvm logging config
Using default gvm logging config
Using default openvas logging config
Choosing container start method from:

Starting gvmd & openvas in a single container !!
find: ‘/proc/1/map_files’: Operation not permitted
find: ‘/proc/74/map_files’: Operation not permitted

[root@openvas ~]# 
```

**Comment by Hezk** [comment]
Hi! Same problem here With Centos 7 too.

Docker latest version: docker-ce.x86_64 3:20.10.17-3.el7

Docker logs openvas container:

Setting up contianer filesystem
cp: cannot stat '/usr/local/var/lib/*': No such file or directory
cp: cannot stat '/var/lib/gvm/*': No such file or directory
cp: cannot stat '/var/lib/openvas/*': No such file or directory
Using default gvm logging config
Using default gvm logging config
Using default openvas logging config
Choosing container start method from:

Starting gvmd & openvas in a single container !!
find: ‘/proc/1/map_files’: Operation not permitted
find: ‘/proc/74/map_files’: Operation not permitted

**Comment by immauss** [comment]
OK. That’s odd.

Just for clarity, did you start with a clean 7.9 install or upgrade to it ?

I’ll try to spin up a centos vm this weekend and see if I can work it out.

**Comment by Hezk** [comment]
Hi immauss, in my case: centos-release-7-9.2009.1.el7.centos.x86_64, upgraded from previous version.

Thanks for your work.

**Comment by immauss** [comment]
Really odd that it was only showing in CentOS 7, but there was a second call to the fs-setup in single.sh. Since's it's already called in starts.sh, I removed it. Seems to be working now. 

I'm running a refresh to pull the latest feeds from Greenbone. That will rebuild all the imgaes and push the chagnes to :latest. 

Thanks!
-Scott

**Comment by infestdead** [comment]
Can confirm it's fixed! Thanks a lot for you work.
