### ISSUE TITLE
running for a couple of days, the container filled up all storage 

### ISSUE THREAD

**Issue by twobombs** [immauss/openvas#131]
Leaving the openvas GVM all-in-one container image running for a couple of days it seems the /tmp filled up all avaliable storage with  definitions. Anyone else noticed that phenomenon also or am I the only one ( leaving pentest containers on for 24/7 )

**Comment by immauss** [comment]
How much space are talking here?
I’ve had it running for months on my production server. 
which tag?

**Comment by twobombs** [comment]
Thank you for your reply. We found it used up 36Gb of storage on /tmp on the 26th of june. The files looked like this:
![Screenshot 2022-07-11 at 09 48 56](https://user-images.githubusercontent.com/12692227/178214889-ccb40074-426e-4742-805e-58bd074e983f.png)
we used openvas:lastes at that time. I'll look into using the latest from now to see if this returns.

**Comment by immauss** [comment]
You might want to ask about this over at the community forum. I don't even have any files named liked that on my prod system. 

What were you doing with it at the time? 

-Scott
