### ISSUE TITLE
Database not fully updated/updating

### ISSUE THREAD

**Issue by LoZio** [immauss/openvas#140]
Running 9c256233210a (latest as of today)
No matter what you set with SKIPSYNC environment variable (or if you set it at all), it always starts and syncs (taking a lot of time of course)

**Comment by immauss** [comment]
That's odd .... The most recent push .... tagged as 22.4-beta has the following hashes according to hub.docker.com:

c3ebd808700f
linux/amd64
---
5a82047531f8
linux/arm/v7
---
e3f5171f8245
linux/arm64


The "latest" tag has:

2d2001b425ae
linux/amd64
---
df1001a8cf8d
linux/arm/v7
---
f2ff42eab444
linux/arm64

None of those match that hash ... 

The "latest" tag is still on the 21.04 branch and should be working fine. The other ... well ... it's beta, but I've not seen any issues with the processing of that flag. It's having issues with upgrading from 21.4 DB, but otherwise works fine with a new DB. 


Let me know.

-Scott

**Comment by LoZio** [comment]
![image](https://user-images.githubusercontent.com/869890/185780500-ae5c2aba-8e53-48bc-9e30-b183cb7f0b14.png)

**Comment by immauss** [comment]
Hmmm .... My Bad.

I had it in my head that the Image ID was the first characters from the Digest. But that does not appear to be corect. 

So ... 
That's the same image I'm running in my prod, which is how I realized my error. 

I've just tested, and it seems to work properly. Can you share the start commands and logs... maybe that will give me an idea of what's going on .. 

Thanks,
-Scott

**Comment by LoZio** [comment]
Where can I find them easily?

**Comment by LoZio** [comment]
Adding to the initial issue: I know it is syncing because the first processes starting are rsync, the web interface comes up late and when I go to feed they are always in updating state for some 10/15 minutes.

**Comment by immauss** [comment]
Are you starting with docker-compose or just on the command line?

**Comment by immauss** [comment]
if command line, the command you are using, if compose, your docker-compose.yaml will help. 

-Scott

**Comment by LoZio** [comment]
Command line docker
`docker run --detach --publish 8087:9392 -e PASSWORD=xxxxxxx -e HTTPS=true -e GSATIMEOUT=60 -e SKIPSYNC=true --volume openvas:/data --name openvas-2022-08-21 immauss/openvas:latest`
Just to be clear I'm using SKIPSYNC since you added it and always worked fine untile methinks last update.

**Comment by immauss** [comment]
I have a theory ..... 
It's still skipping the actual download of the data from Greenbone, but for some reason, the data on disc and the what's in the DB are not in sync. This causes gvmd to go through the whole process of reading every NVT and pushing it to the database. I'm testing now, but also running a new refresh. 

I'll let you know.

Thanks,
Scott

**Comment by immauss** [comment]
OK ... so the timeout in my script to refresh the database was too short. So the feeds themselves were getting updated, but gvmd didn't have enough time to actually update the database ....  Looks like it's taking around 45 minutes now. 
So ... I've upped the time from 40m to 60.  It's running again now, so hopefully in an hour or so (depending on the rebuild time), it should be a good fresh latest image uploaded.

**Comment by immauss** [comment]
@LoZio Thanks. This is resolved now and hopefully will not reoccur. 

latest was DB updated in <5m and ready to scan in <15m 

-Scott

**Comment by LoZio** [comment]
I updated and can confirm it started quite fast. When I manually sync'ed it took a lot to finish the process (expected) but not all the parts were updated. This is strange because 2 days ago, with the previous version, I created a brand new VM + containers and after update it was all up to date.
![image](https://user-images.githubusercontent.com/869890/186598797-882f9233-e560-466a-80a3-8c1a226cc895.png)

Of course I keep the data when I create a new container.
Stats from this run (I know t's not related to your containers), on a 4 core Intel/ 8 Gb RAM / SSD dedicated VM (debian 11):
- feed update (rsync): about 2 minutes (previous was 2 days ago)
- "Update in progress..." phase on feeds page: 38 minutes

Thanks @immauss

**Comment by immauss** [comment]
That's odd .... sounds like something didn't finish on the sync. 
You can run it manually even if you started with SKIPSYNC:

```
docker exec -it <container-name> /scripts/sync.sh
```

If that completes with no errors, and it's still off, let me know. 


-Scott

**Comment by LoZio** [comment]
I did exactly that, launched the manual sync with the script.

**Comment by immauss** [comment]
So that looks normal.
Is it still out of sync?

**Comment by LoZio** [comment]
Yes it is, sorry I was not clear from the beginning. I can sync it any time I want, always out of sync.
A clean installation syncs everything instead. I mean, if using the same image I create a new docker volume bound to the data dir, it says all is up to date. Using my old data it does not seem to sync CERT and GVMDATA.

**Comment by immauss** [comment]
Very odd this .... And I don't see anything in the logs to suggest a problem. 

Have you tried any of the "--optimize". or --rebuild options with gvmd ? 


-Scott

**Comment by LoZio** [comment]
Today I did this:
1. updated the image, now I got 
```
REPOSITORY        TAG       IMAGE ID       CREATED      SIZE
immauss/openvas   latest    0246e1badd0f   2 days ago   1.5GB
```
2. created a new instance with same docker command as above
3. waited 10 minutes after start to settle. Correctly it told me it was out of date but this time CERT and GVMD data were shown at the same date as other feeds. With previous image it was not.
![ov0](https://user-images.githubusercontent.com/869890/187846554-10534628-c4d8-4f27-83d9-40c5589b886e.JPG)
4. Started the sync script. All went updating
![ov1](https://user-images.githubusercontent.com/869890/187846722-93c25e8e-9002-4004-9245-9020f96dc306.JPG)
5. GVMD data was pulled correctly
![ov2](https://user-images.githubusercontent.com/869890/187846801-a5045b82-af9b-4999-b7a2-a07929e73ff6.JPG)
6. 20 minutes were spent here
![ov3](https://user-images.githubusercontent.com/869890/187846879-8635008c-1ed9-460e-a356-0d827e09bc61.jpg)
7. It ended up with all up to date
![ov4](https://user-images.githubusercontent.com/869890/187846938-1bdf8875-cc78-4edd-aa15-854f3c543bcc.JPG)

I dont' know what changed with last build, but starting from pic at 3. I suppose there is some visualization mismatch between loaded feeds and the interface, or the feeds update cycle do not finish correctly some times.
When last week I was out of sync with gvmd anc CERT I restarted the container several times, and always was out of sync as in the pic in my previous message.
To answer your precise question: no I didn't use --rebuild/--optimize, I discovered they exist right now ;-)

**Comment by immauss** [comment]
Well, I'm glad it's working now. If you ever figure out what the true cause was, please let me know. I really haven't made any changes other than content updates to the 21.4 image in a while. . . . .
