### ISSUE TITLE
How to export a full report when result more than 1000

### ISSUE THREAD

**Issue by tpaiii3** [immauss/openvas#143]
My scan result have 9000 items. I try to export in csv/xml format. But it can export just 1000 items.

**Comment by lokalhorstkme** [comment]
Scott,

great work ...

found the stuff to get huge reports: (**_https://forum.greenbone.net/t/export-all-scan-results-from-a-single-report-or-multiple-when-then-are-more-than-1000-results/12383_**)

To make a long story short: 

**gvm-cli** is needed to get the reports. But unfortunately in the actual docker, it is not creating the necessary /var/run/gvmd.sock. Could you please modify the /scripts/gvmd.sh in that way:

-------- CUT --------
su -c "exec gvmd   **--unix-socket=/var/run/gvmd.sock**  -f $GMP .....
-------- CUT --------

you could test if the socket (/var/run/gvmd.sock) is exsting :
_docker exec -it -u gvm openvas bash
gvm-cli socket --xml "<get_version/>"_

Hope this works / helps ..
Best regards
-Kay

**Comment by immauss** [comment]
Kay,
       You "should" be able to make this work with the 'ssh' connection option. GMP is enabled in the container and gvmd is listening on port 9390 for connections.  I know this should work, but have not had the opportunity (or need) to do much with it other than verify the port is listening. I'll try to do some tests with it, but it might be a few days. If you work it out, please let me know. 

       I disabled the sockets to allow for easier inter-container communications. Re-enabling the sockets breaks the network connections (gvmd will only do one or the other, not both). 

Let me know. 

-Scott

**Comment by immauss** [comment]
Correction ... it's 'tls' not 'ssh'

scott@XXXX ~ $ 
scott@XXXX ~ $ docker exec -t -u gvm openvas-prod /usr/local/bin/gvm-cli  --gmp-username admin --gmp-password XXXXXXXXX tls  --xml "<get_version/>" 
<get_version_response status="200" status_text="OK"><version>21.4</version></get_version_response>

**Comment by lokalhorstkme** [comment]
Scott,

awesome! You're my man! TLS makes sense, otherwise communication via socks over containers is a nightmare ;-).
 It is also very useful for scripting /controlling openvas. If you know what I mean...

Works like charming.
Thanx lot 
Best regards Kay

**Comment by immauss** [comment]
Awesome! Glad you worked it out.
