### ISSUE TITLE
Running scans from CLI

### ISSUE THREAD

**Issue by noire-x** [immauss/openvas#148]
Hi guys thanks for your effort to make this up and running for us.
Was wondering if there is the chance of running scans from directly from CLI?
How would it be possible?
Thanks ahead!

**Comment by immauss** [comment]
You can look into gvm-cli. It works with the containers, but I'm not familiar with the XML syntax to do anything with. You can start with:

scott@XXXX ~ $
scott@XXXX ~ $ docker exec -t -u gvm openvas-prod /usr/local/bin/gvm-cli --gmp-username admin --gmp-password XXXXXXXXX tls --xml "<get_version/>"

<get_version_response status="200" status_text="OK">21.4</get_version_response>
