### ISSUE TITLE
How to update From Version 21.4.3 to Version 22.4

### ISSUE THREAD

**Issue by s0vandey** [immauss/openvas#151]
Dear team currently i am using Version 21.4.3 and i want to update the image From Version 21.4.3 to Version 22.4 can any one share the stapes

**Comment by immauss** [comment]
For a single container, it should be automatci, just pull the new version and rerun.

For multi-container, make sure you get the latest docker-compose from github and tweak to your needs. 


-Scott

**Comment by immauss** [comment]
I'm going to close this. If you still need help, please open a new issue.

**Comment by s0vandey** [comment]
Please share me SOP
