### ISSUE TITLE
[Question] How to change sync source

### ISSUE THREAD

**Issue by AjaCoder** [immauss/openvas#152]
Hello,

I'm trying to use the docker and want to understand how can I change the source of the sync to a private sync server.
Do setting the following environment variables will work?
COMMUNITY_GVMD_DATA_RSYNC_FEED
COMMUNITY_SCAP_RSYNC_FEED
COMMUNITY_CERT_RSYNC_FEED
COMMUNITY_NVT_RSYNC_FEED

Thanks and amazing work here, will do my best to provide support in maintaining the repo.

**Comment by immauss** [comment]
Hmm ... I've not done anything with those before. If they work as regular environment variables, then you could try setting them with -e COMMUNITY_GVMD_DATA_RSYNC_FEED="value" .

-Scott
