### ISSUE TITLE
The report format is not correct  And Host name not showing 

### ISSUE THREAD

**Issue by s0vandey** [immauss/openvas#158]
Dear Team 
After complete my scan when i download the report i notice that host name not pickup properly and some host name not pickup and some host name showing wrong IP address below attached screenshot for your reference      

![image](https://user-images.githubusercontent.com/114781307/200118663-bd6bc8ff-a1d6-4790-a0ff-07abf9c05904.png)

**Comment by s0vandey** [comment]
> i am witting for your update.. please provide the solution

**Comment by immauss** [comment]
Sorry for the delay. This sounds like a configuration issue. Check you have the DNS setup properly on the host running the container and set the DNS options on the scan config. If you have more questions around this topic, it's best to ask on the community forum. I try to keep things here focused on the container development and issues directly related to the container. 

Thanks,
Scott
