### ISSUE TITLE
just restart but the last NVT's  is 09/28/2022

### ISSUE THREAD

**Issue by manuel-cestaro-personal** [immauss/openvas#159]
Good morning,
i have just restart the container as explain the documentation to reload the NVT's, but the last day shows in the dashboard is 09/28/2022. This is normal? 2 days ago I receved the 11/11/2022 nvt...

The following is the log about the version:
```
==> /usr/local/var/log/gvm/openvas.log <==
libgvm util:MESSAGE:2022-11-13 09h05.38 utc:693: Updated NVT cache from version 0 to 202211111012
```

Thanks for help and for the container =)

**Comment by immauss** [comment]
Sorry for the delay. I've been moving into a new house ..... 

Greenbone doesn't always update things every day, so if you saw that message, then that is most likely the most recent version available.

**Comment by manuel-cestaro-personal** [comment]
Ok, thank you very much!
Best wishes for the new home =)
