### ISSUE TITLE
No Redis DB Available

### ISSUE THREAD

**Issue by gooseleggs** [immauss/openvas#16]
I have been running increasing bigger scans, and run into this occasionally.  There is a formula for the number of Redis DBs that should be configured:

```
You need at least

one db for the main data
one db for the nvt cache
one db for every scan
one db for every target host of a scan
So it is 2 + n * m dbs where n is the number of concurrent scans and m the number of hosts per scan.
```

However, the start.sh script sets this at 128.  Can this be a configurable number through an environment variable, and probably make it a larger number than 128?

I haven't got to create a pull request yet, but putting it here in case you get to it before I do.

**Comment by immauss** [comment]
I don't see what it couldn't be added in as a runtime .... 
Just moved to a new house, so I haven't had time to even think about looking at it though.

**Comment by immauss** [comment]
I'm adding this to 20.08. 
The new environment variable is REDISDBS with a default of 128. 
20.08 should be live in the next 24 hours or so.

**Comment by immauss** [comment]
Let me know if you are having any issues with this. I also made the new default 512. 

And I need to document this too.... 

Thanks.
