### ISSUE TITLE
Failed to find user.

### ISSUE THREAD

**Issue by andreasc1** [immauss/openvas#161]
hi, latest version fails to start with this error:

`
..
All transactions are logged.

If you have any questions, please use the Greenbone community portal.

See https://community.greenbone.net for details.

By using this service you agree to our terms and conditions.

Only one sync per time, otherwise the source ip will be temporarily blocked.

receiving incremental file list



timestamp

13 100% 12.70kB/s 0:00:00 (xfr#1, to-chk=0/1)

sent 71 bytes received 111 bytes 121.33 bytes/sec

total size is 13 speedup is 0.07

Feed is already current, skipping synchronization.

Starting Greenbone Vulnerability Manager...

Waiting for gvmd

Time to fixup the gvm accounts.

Setting admin password

Failed to find user.
`

**Comment by immauss** [comment]
Can you give me a little more detail? 
- command you used to start 
- environment used (Host OS, docker version etc.)
- Is this a restart of an older container environment, or a fresh new container & volume ?

Thanks,
Scott

**Comment by andreasc1** [comment]
Hi @immauss  i used:
docker run --detach --publish 8080:9392 -e PASSWORD=passs --volume openvas:/data --name openvas immauss/openvas

my environment is mac, Docker version 19.03.13, build 4484c46d9d
fresh new container, just got it from your repository by following the commands you provided.

**Comment by immauss** [comment]
Yes. There is a problem with the "-e PASSWORD=" option. I've not had a chance to debug it yet. Unless you are using it in some sort of automated environment, it is better to set the password after the container has started via the GUI. And ... this method should work now....  If not, please let me know. Otherwise, please keep an eye on issue #157. 

Thanks,
Scott

**Comment by andreasc1** [comment]
> Yes. There is a problem with the "-e PASSWORD=" option. I've not had a chance to debug it yet. Unless you are using it in some sort of automated environment, it is better to set the password after the container has started via the GUI. And ... this method should work now.... If not, please let me know. Otherwise, please keep an eye on issue #157.
> 
> Thanks, Scott

Thanks Scott, and the defaults are admin/admin ?
