### ISSUE TITLE
No have GVMD Unix Socket problem

### ISSUE THREAD

**Issue by hanlihub** [immauss/openvas#166]
gvm.errors.GvmError: Socket /run/gvmd/gvmd.sock does not exist

**Comment by immauss** [comment]
Can you please provide more detail for the problem? 

How did you start the container?
What container environment and version are you using?
Please provide the full log output from :
docker logs < container name > 

Did you get this message on the initial container start, or after it had run for some time? 


This error usually resolves as a permission error or other conditions that cause gvmd to die. Make sure you have at least 512MB of memory available in the container. 


Thanks,
Scott

**Comment by hanlihub** [comment]
expose the GVM port by adding to the docker run command.--publish 9390:9390, to use TLSConnection can be solved。 
Refer to this link，https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/issues/46

**Comment by kun823** [comment]
i need use UNIXSOCKETCONNECTION of python ,but i cannot find gvmd.sock

**Comment by immauss** [comment]
added a section on scripting to the docs.
