### ISSUE TITLE
Master / Sensor setup with the Source Edition

### ISSUE THREAD

**Issue by mttgarcia** [immauss/openvas#167]
Hello,

I am looking to know if it is possible to have a Master/Sensors architecture through the Source Edition pulled through the immauss/openvas docker? I tried to add a scanner in GSA but I can't change the scanner type so I get an error.
Do you know if there are resources that correspond to the GSA 22.4 version?

Maybe I should ask my question somewhere else but I don't know where to look.

Thank you in advance!

**Comment by immauss** [comment]
I've not done this with the containerized version, but I don't see why it couldn't be done. You'll need to make sure you are mapping the proper ports into the container assuming the scanner is running on another machine though. 

-Scott

**Comment by immauss** [comment]
Oh ... an you could check the greenbone forums for tips on setting up the extra scanners. I seem to recall something about the processing changing a bit with 22.4 from 21.4 ...

-Scott

**Comment by mttgarcia** [comment]
Thanks for your feedback.

Sorry, maybe these are noob questions. I'm trying to build on this docs:
https://docs.greenbone.net/GSM-Manual/gos-21.04/en/master-sensor-setup.html

But is it possible to access Greenbone OS with the containerized version? I'm stuck at this stage and I don't know where to look because on the documentation you have to connect to the appliance.

**Comment by immauss** [comment]
Greenbone OS is a "paid" piece from Greenbone. So not all of what you read about it works with the OpenSource bits. 

It do think what you want to do is possible with the container, unfortunately, I'm time constrained at the moment, so not sure when I'll have a chance to try and tackle it. 


-Scott

**Comment by immauss** [comment]
Closing this as if I ever get time to work it out, it's already a request in #109
