### ISSUE TITLE
issue after updating 

### ISSUE THREAD

**Issue by killmasta93** [immauss/openvas#168]
Hi
I was wondering if someone could shed some light on the issue im having
Currently updated from version 21 to 22 
Currently the docker container shows unhealthy and looking at the logs
`
md    gmp:WARNING:2023-02-12 22h42.21 UTC:2525: get_feed_info: Failed to read '/var/lib/gvm/data-objects/gvmd/22.04/feed.xml': Failed to open file “/var/lib/gvm/data-objects/gvmd/22.04/feed.xml”: No such file or directory`

![image](https://user-images.githubusercontent.com/13953629/218341723-4b546c01-b648-4342-b0fc-98dd8fef428f.png)

Thank you

**Comment by immauss** [comment]
can you share how you are starting the container and a bit more about your setup? 

It looks like the feeds are not synching ... So you could try:

docker exec -it <containername> /scripts/sync.sh 

IF that fails out, then please report any error messages here and I'll try to help you figure out what is going on. 

-Scott

**Comment by killmasta93** [comment]
Hi @immauss Thank you so much for the reply,
So after running it seems in the logs seems to be ok 
Whats odd it shows the container unhealthy and the other container shows as stopped

This is my docker compose

```
version: "3"
services:
  openvas:
    ports:
      - "8080:9392"
    environment:
      - "PASSWORD=thepassword"
      - "USERNAME=admin"
      - "RELAYHOST=172.17.0.1"
      - "SMTPPORT=27"
      - "REDISDBS=512" # number of Redis DBs to use
      - "QUIET=false"  # dump feed sync noise to /dev/null
      - "NEWDB=false"  # only use this for creating a blank DB
      - "SKIPSYNC=true" # Skips the feed sync on startup.
      - "RESTORE=false"  # This probably not be used from compose... see docs.
      - "DEBUG=false"  # This will cause the container to stop and not actually start gvmd
      - "HTTPS=false"  # wether to use HTTPS or not
      - "GMP=9390"    # to enable see docs
    volumes:
      - "/openvas:/data"
    container_name: openvas
    image: immauss/openvas:latest
  scannable:
    image: immauss/scannable
    container_name: scannable
volumes:
  openvas:
```


![image](https://user-images.githubusercontent.com/13953629/219223576-77c5da76-77d5-407a-bd6c-8f877fdd9b67.png)


```

![image](https://user-images.githubusercontent.com/13953629/219223279-8e8a3abf-a2b6-4ca6-9e50-7fb84eeccf39.png)


md   main:MESSAGE:2023-02-16 00h04.10 utc:1097400:    Greenbone Vulnerability Manager version 22.4.2 (DB revision 250)

md manage:   INFO:2023-02-16 00h04.10 utc:1097400:    Getting scanners.

md   main:MESSAGE:2023-02-16 00h04.15 utc:1097410:    Greenbone Vulnerability Manager version 22.4.2 (DB revision 250)

md manage:   INFO:2023-02-16 00h04.15 utc:1097410:    Verifying scanner.

==> /usr/local/var/log/gvm/healthchecks.log <==

 Healthchecks completed with no issues.

==> /usr/local/var/log/gvm/gvmd.log <==

md   main:MESSAGE:2023-02-16 00h05.13 utc:1097489:    Greenbone Vulnerability Manager version 22.4.2 (DB revision 250)

md manage:   INFO:2023-02-16 00h05.13 utc:1097489:    Getting scanners.

md   main:MESSAGE:2023-02-16 00h05.17 utc:1097498:    Greenbone Vulnerability Manager version 22.4.2 (DB revision 250)

md manage:   INFO:2023-02-16 00h05.17 utc:1097498:    Verifying scanner.

==> /usr/local/var/log/gvm/healthchecks.log <==

 Healthchecks completed with no issues.
```
Thank you again

**Comment by immauss** [comment]
AH! The key here is in your compose file. 
Change:
- "SKIPSYNC=true"
to
- "SKIPSYNC=false"

when set to true, the container starts faster, but you will need to sync the new content that comes with 22.4.


-Scott

**Comment by immauss** [comment]
If this didn't resolve your problem, please re-open this or start a new issues. 

Thanks,
Scott

**Comment by killmasta93** [comment]
Hi @immauss sorry i thought i replied weeks ago must been that it was saved on draft and did not go though,
Forgot to mention it worked, but it keeps showing me like this

![image](https://user-images.githubusercontent.com/13953629/222929265-f2802535-941f-4d7a-b15d-9c1a733ed66d.png)


Thank you again
