### ISSUE TITLE
Unable to build the dockerfile

### ISSUE THREAD

**Issue by richardklein** [immauss/openvas#169]
While building the dockerfile I am getting an issue with:
RUN curl -L --url https://www.immauss.com/openvas/latest.base.sql.xz -o /usr/lib/base.sql.xz && \
    curl -L --url https://www.immauss.com/openvas/latest.var-lib.tar.xz -o /usr/lib/var-lib.tar.xz

The files cannot be downloaded anymore.

**Comment by immauss** [comment]
Ugh ... Looks like a webserver issue ...... again .... 
Sorry ... 
I'll try to get on it later today and see if I can work out the issue. 

-Scott

**Comment by immauss** [comment]
Thanks!!
Had to restart apache ... 
It should work now. 
Please let me know.


-Scott

**Comment by richardklein** [comment]
its working again, thanks
