### ISSUE TITLE
The SCAP database is required

### ISSUE THREAD

**Issue by MarksenDE** [immauss/openvas#17]
Hi immauss,
great App running on docker. I'm not a specialist concerning docker but seems that everything is running except SECInfos.I get on SecInfo WebUI this message "The SCAP database is required"
Running docker logs brings me:
md manage:WARNING:2020-10-21 16h34.09 utc:1378: open_secinfo_lockfile: failed to open lock file '/tmp/gvm-sync-scap': Permission denied
md manage:WARNING:2020-10-21 16h34.09 utc:1379: open_secinfo_lockfile: failed to open lock file '/tmp/gvm-sync-cert': Permission denied
md manage:WARNING:2020-10-21 16h34.19 utc:1382: open_secinfo_lockfile: failed to open lock file '/tmp/gvm-sync-scap': Permission denied
md manage:WARNING:2020-10-21 16h34.19 utc:1385: open_secinfo_lockfile: failed to open lock file '/tmp/gvm-sync-cert': Permission denied

and yes,after first start i'm waiting about 1 hour after finishing sync feeds.

Any idea/hint?

Thanks in advance 
Mark

**Comment by immauss** [comment]
Sorry for the long delay. Been painfully busy of late. 

if you run docker logs <container name or ID> 

do you see an entry like:


update_scap: Updating SCAP info succeeded  

??

**Comment by immauss** [comment]
20.08 should resolve this. It should be live in the next 24 hours or so.

**Comment by MarksenDE** [comment]
Thanks a lot for your investigation, i'll give it a try (and sent update)

**Comment by immauss** [comment]
You may see this error earlier on with 20.08. It take some time for the DB to be populated and gvmd to get everything lined up. The best bet is to waint unitl the scan configs are populated. Once you see that in the logs, everything should be ready to go.
