### ISSUE TITLE
Change the amount of results exported

### ISSUE THREAD

**Issue by gooseleggs** [immauss/openvas#170]
So I was searching around for how to have the ability to export more than 1000 rows of data.  Seems this has already been cracked by this project: https://github.com/jurrKodi/gvm-scanner/blob/master/scripts/reportFix.sh.  I have tried it and seems to work.  Perhaps you could use this (haven't checked license state) and make it an environment variable?

**Comment by immauss** [comment]
Good idea!

I'll see if I can add that in with the next release. Should be pretty simple. 

Thanks,
Scott

**Comment by immauss** [comment]
Check out 22.4.11 !

You should be able to use "-e REPORT_LINES=<some integer>

-Scott
