### ISSUE TITLE
Image no longer works without internet access

### ISSUE THREAD

**Issue by gaby** [immauss/openvas#173]
Recently I tried updating to the latest image on a fresh install. The environment where I have this container doesnt have access to internet. The following code makes deploying a new container impossible:

```bash
if ! [ -f tmp/GBCommunitySigningKey.asc ]; then
	echo " Get the Greenbone public Key"
	curl -f -L https://www.greenbone.net/GBCommunitySigningKey.asc -o /tmp/GBCommunitySigningKey.asc
	echo "8AE4BE429B60A59B311C2E739823FAA60ED1E580:6:" > /tmp/ownertrust.txt
	echo "Setup environment"
	mkdir -m 0600 -p $GNUPGHOME $OPENVAS_GNUPG_HOME
	echo "Import the key "
	gpg --import /tmp/GBCommunitySigningKey.asc
	gpg --import-ownertrust < /tmp/ownertrust.txt
	echo "Setup key for openvas .."
	cp -r /tmp/openvas-gnupg/* $OPENVAS_GNUPG_HOME/
	chown -R gvm:gvm $OPENVAS_GNUPG_HOME
fi
```

Stuff like this should be avoided during a docker run, it should be backed into the image.

**Comment by immauss** [comment]
gaby,
       That has been there for quite a while, have you used it before in an isolated environment ? 
 
       Regardless .... I'll work on moving this bit into the build processes. 

       The only thing that key is used for (that I'm aware of) is validating the downloads from GB, so in an isolated environment, it should not be needed. You could safely comment this out on the container in your isolated environment. 

       Thanks. This is a good find!

-Scott

**Comment by gaby** [comment]
I have been using this image since early last year, we started using a different tool for while and now wanted to go back to greenbones. That's when i ran into this issue.

Thanks!

**Comment by gaby** [comment]
@immauss Test locally and it worked using the `gaby` tag!

cmd:
```bash
docker run --publish 8080:9392 -e SKIPSYNC=true -e PASSWORD="TestPassword" --name openvas immauss/openvas:gaby
```

Results:
![image](https://user-images.githubusercontent.com/835733/225809408-23e62951-9e90-4b83-ab36-1eb11fc32b2d.png)

**Comment by immauss** [comment]
Outstanding! I'm moving this into latest now. 

Thanks!

**Comment by gaby** [comment]
Thank you!
