### ISSUE TITLE
How to config Send mail Alert

### ISSUE THREAD

**Issue by copph33** [immauss/openvas#174]
Hi Boss and everyone,  Can you help me config mail to send mail alert and add ssl

**Comment by copph33** [comment]
> Please provide info how to configure gvm with SSL certificate

You can setup Nginx reverse proxy, it worked

**Comment by sergeymeleschenko** [comment]
> > Please provide info how to configure gvm with SSL certificate
> 
> You can setup Nginx reverse proxy, it worked

Did you have manual how to do it ?

**Comment by immauss** [comment]
For SSL ... you can also use this:
https://github.com/immauss/rev-prox
There should be a better way, but I haven't had time to work it out, and this works well. 


For email, assuming you have a working RELAY to send through (beyond the scope of here), you should be able to set the options for email from the docs, and it will just work. 

from:
https://immauss.github.io/openvas/

RELAYHOST : The IP address or hostname of the email relay to send emails through. Default = 172.17.01 (This is default for the docker host. If you are running the mail relay on your docker host, this should work, but you will need to make sure you allow the conections through the host's firewall/iptables)

`-e RELAYHOST=mail.example.com `

SMTPPORT : The TCP port for the RELAYHOST. Default = 25

`-e SMTPPORT=25`

**Comment by sergeymeleschenko** [comment]
> For SSL ... you can also use this: https://github.com/immauss/rev-prox There should be a better way, but I haven't had time to work it out, and this works well.
> 
> For email, assuming you have a working RELAY to send through (beyond the scope of here), you should be able to set the options for email from the docs, and it will just work.
> 
> from: https://immauss.github.io/openvas/
> 
> RELAYHOST : The IP address or hostname of the email relay to send emails through. Default = 172.17.01 (This is default for the docker host. If you are running the mail relay on your docker host, this should work, but you will need to make sure you allow the conections through the host's firewall/iptables)
> 
> `-e RELAYHOST=mail.example.com `
> 
> SMTPPORT : The TCP port for the RELAYHOST. Default = 25
> 
> `-e SMTPPORT=25`

Thanks for your help.
