### ISSUE TITLE
 manage_cleanup_process_error: Error exit, setting running task to Interrupted

### ISSUE THREAD

**Issue by boesr** [immauss/openvas#176]
Hey,

I just updated the openvas docker image from 21.4.4 to 22.4.09 and now I am getting the message `manage_cleanup_process_error: Error exit, setting running task to Interrupted` when a task reaches 100% (no error before). It is changed to done and then to interrupted.

```
OSPD[573] 2023-03-20 08:59:18,451: INFO: (ospd.ospd) (some-hash): Host scan finished.
OSPD[573] 2023-03-20 08:59:18,452: INFO: (ospd.ospd) (some-hash): Scan finished.
==> /usr/local/var/log/gvm/gvmd.log <==
event task:MESSAGE:2023-03-20 08h59.23 UTC:45352: Status of task Immediate scan of IP my.host.domain.com (some-hash) has changed to Done
md manage:WARNING:2023-03-20 08h59.23 UTC:45352: manage_cleanup_process_error: Error exit, setting running task to Interrupted
event task:MESSAGE:2023-03-20 08h59.23 UTC:45352: Status of task Immediate scan of IP my.host.domain.com (some-hash) has changed to Interrupted
```

A restart did fix that problem, but the next restart (one daily to update nvts) did bring it up again. 

Would be grateful for any hint.

Many thanks

**Comment by immauss** [comment]
That is odd. I've not seen this anywhere before. I'd suggest asking over on the greenbone forums as this doesn't seem to be a container-specific issue. 

https://forum.greenbone.net
