### ISSUE TITLE
Container shows unhealthy

### ISSUE THREAD

**Issue by farzadha2** [immauss/openvas#179]
Hi @immauss 
Wanted to first thank you for an amazing container
currently im having an issue the docker container keeps showing unhealthy
i try to restart the scannable docker container but it later turns off

![image](https://user-images.githubusercontent.com/62571297/228972152-b8c1addf-cef6-4920-a6b7-bdeef96a0208.png)

this is my docker compose 
```

version: "3"
services:
  openvas:
    ports:
      - "8080:9392"
    environment:
      - "PASSWORD=pwdpass"
      - "USERNAME=admin"
      - "RELAYHOST=172.17.0.1"
      - "SMTPPORT=27"
      - "REDISDBS=512" # number of Redis DBs to use
      - "QUIET=false"  # dump feed sync noise to /dev/null
      - "NEWDB=false"  # only use this for creating a blank DB
      - "SKIPSYNC=false" # Skips the feed sync on startup.
      - "RESTORE=false"  # This probably not be used from compose... see docs.
      - "DEBUG=false"  # This will cause the container to stop and not actually start gvmd
      - "HTTPS=false"  # wether to use HTTPS or not
      - "GMP=9390"    # to enable see docs
    volumes:
      - "/openvas:/data"
    container_name: openvas
    image: immauss/openvas:latest
  scannable:
    image: immauss/scannable
    container_name: scannable
volumes:
  openvas:
```

Thank you

**Comment by immauss** [comment]
If it's just the scannable container, you can remove that from the compose. It's really just there to give you a test target for the scanner.  Since it has a number of vulnerabilities, it is setup to only run for a few hours, then shutdown.  

Now that I think about it, I'll remove it from the default docker-compose. I really shouldn't be there for just that reason. 

Thanks,
-Scott

**Comment by farzadha2** [comment]
Hi @immauss Thank you so much for the reply, so i deleted the container and restart the openVAS container but keeps showing unhealthy whats even more odd i check the logs and shows correctly 

![image](https://user-images.githubusercontent.com/62571297/229383374-930a16c0-d762-4779-a2c1-2b8ebe322c51.png)

![image](https://user-images.githubusercontent.com/62571297/229383382-e00e9bdb-6c46-458f-aadc-33225031c09c.png)

**Comment by immauss** [comment]
Let me know if that takes care of it. 

-Scott

**Comment by farzadha2** [comment]
Thank you so much that did the trick
