### ISSUE TITLE
HEALTHCHECK FAILED when running in RHEL docker / podamn

### ISSUE THREAD

**Issue by deajan** [immauss/openvas#181]
Hello,

Tried your docker a couple of days ago on a RHEL9 / podman setup.

So far everything starts, but I get the following errors:
```
 HEALTHECHECK FAILED !
 These services failed
  gvmd postgresql
 HEALTHECHECK FAILED !
 These services failed
  gvmd postgresql
 HEALTHECHECK FAILED !
 These services failed
  gvmd postgresql
 HEALTHECHECK FAILED !
 These services failed
  gvmd postgresql
```

Having poked around in `/scripts/healhcheck.sh`, I checked manually that I could launch `nmap`.

`nmap -p 9390 localhost| grep -qs "9390.*open"`  resulted in `Failed to create socket: Operation not permitted`

After having installed `setcap cap_net_raw,cap_net_admin=eip /usr/bin/nmap`, I still got `bash: /usr/bin/nmap: Operation not permitted`.

I had to run podman with `--cap-add=IPC_LOCK --cap-add=NET_RAW` in order to get things to work.

Actually, after fidling around, I realised I didn't have to run `setcap` inside the container. Using the podman/docker arguments was sufficient.

Just wanted to report back so other people might find this fix.
Thanks for your work.

**Comment by immauss** [comment]
Sounds like I need to do some testing with podman as I've never had this issue with running it on docker.  

Thanks for the follow up.

**Comment by immauss** [comment]
I've done some testing with podman recently, and had no issues. The latest image 'should' for you, if not, please open a new issue. 

Thanks,
-Scott
