### ISSUE TITLE
fs-setup.sh error

### ISSUE THREAD

**Issue by shandshellin** [immauss/openvas#183]
had to run this manually with the correct spelling of the folder /run/postgresql can you update the script in the image?

arm:latest

# Fix ownership and permissions
chown -R postgres:postgres /data/database /data/var-log/postgresql /run/postgres      ****************/run/postgresql
chmod 750 /data/database
chmod 770 /run/gvm /run/ospd /var/lib/gvm/gvmd/gnupg /run/gsad
chown -R gvm:gvm  /data/var-lib/openvas /data/local-share/gvm /data/var-log/gvm /data/var-lib/gvm /run/gvm* /run/ospd /run/gsad /etc/openvas/gnupg
chmod 777 /run 
chmod 740 /run/mosquitto /var/log/mosquitto
chown mosquitto /run/mosquitto /var/log/mosquitto 
chown -R postfix:postfix /var/lib/postfix
chown -R gvm:gvm /data/var-lib/notus

**Comment by shandshellin** [comment]
Also this folder appears to be empty

/var/lib/notus/* for the cp

**Comment by immauss** [comment]
Thank you. I've made those changes in my base. I don't think it was causing any issues with the container, so it will push out with the next release. 

Thanks,
Scott
