### ISSUE TITLE
stuck at 99%

### ISSUE THREAD

**Issue by noire-x** [immauss/openvas#185]
Hi there Scott,
we having isses when scanning networks, scan hangs 99% for a very long time, say almost a day so then we stop the task.  Instead, when scanning a single host the task gets completed.
Are you aware of any bug that GB have recently implemented? (ironic :)
ty as usual

**Comment by jvictors-tp** [comment]
To those in the future coming in from a search: check out https://forum.greenbone.net/t/why-the-scan-becomes-slower-when-its-progress-reaches-to-99/14810
