### ISSUE TITLE
Failed to update NASL

### ISSUE THREAD

**Issue by gooseleggs** [immauss/openvas#187]
When trying to start the new 22.4.13 container, it is failing to update the NVTs.  It is giving this in the logs

```
<29>May 15 04:45:45 greenbone-nvt-sync: Loading NASL data to /var/lib/openvas/plugins
Greenbone community feed server - http://feed.community.greenbone.net/
This service is hosted by Greenbone Networks - http://www.greenbone.net/

All transactions are logged.

If you have any questions, please use the Greenbone community portal.
See https://community.greenbone.net for details.

By using this service you agree to our terms and conditions.

Only one sync per time, otherwise the source ip will be temporarily blocked.

receiving incremental file list
rsync: [sender] change_dir "/vulnerability-feed/22.05/vt-data/nasl" (in community) failed: No such file or directory (2)

sent 48 bytes  received 141 bytes  54.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1819) [Receiver=3.2.3]
<27>May 15 04:45:48 greenbone-nvt-sync: rsync for nasl failed.
```

As can be seen, it is failing with a directory not found.  I have tried to create it manually, but not there.

Is this a me problem or a them problem?  The container is starting up healthy, and using the 'all-in-one container'

**Comment by gooseleggs** [comment]
I found one comment about this: https://forum.greenbone.net/t/rsync-sender-change-dir-vulnerability-feed-22-05-vt-data-nasl-in-community-failed-no-such-file-or-directory-2/14629 

However that did not seem to resolve my problem.

**Comment by immauss** [comment]
I found out late last week, GB has a new and separate repo for the sync script. 22.4.16 has the new script and the latest updates from GB.

**Comment by gooseleggs** [comment]
Updated to latest version (didn't pull as it wasn't on your documentation page, so thought it was beta).  Seems to be working now.

**Comment by immauss** [comment]
Awesome ... yeah ... I think the readme still needs to be pushed. 

Thanks,
Scott
