### ISSUE TITLE
Interrupted at 0 %

### ISSUE THREAD

**Issue by xaled1** [immauss/openvas#188]
Hi,

when running wizard test task I'm getting the error message [Interrupted at 0 %]

==> /usr/local/var/log/gvm/gvmd.log <==
event target:MESSAGE:2023-05-16 11h43.28 UTC:2526: Target Target for immediate scan of IP 192.168.234.160 - 2023-05-16 11:43:28 (87385e7f-7229-4bc0-89a8-e62b95179c89) has been created by admin
event task:MESSAGE:2023-05-16 11h43.28 UTC:2526: Status of task  (50aad276-732a-417d-8d5e-d6ea0a09a2e3) has changed to New
event task:MESSAGE:2023-05-16 11h43.28 UTC:2526: Task Immediate scan of IP 192.168.234.160 (50aad276-732a-417d-8d5e-d6ea0a09a2e3) has been created by admin
event task:MESSAGE:2023-05-16 11h43.28 UTC:2526: Status of task Immediate scan of IP 192.168.234.160 (50aad276-732a-417d-8d5e-d6ea0a09a2e3) has changed to Requested
event task:MESSAGE:2023-05-16 11h43.28 UTC:2526: Task Immediate scan of IP 192.168.234.160 (50aad276-732a-417d-8d5e-d6ea0a09a2e3) has been requested to start by admin
md manage:WARNING:2023-05-16 11h43.28 UTC:2537: OSP start_scan 5e3a68cf-797d-4e34-81c2-f22d7bc857e1: VTs list is empty
event wizard:MESSAGE:2023-05-16 11h43.28 UTC:2526: Wizard quick_first_scan has been run by admin
event task:MESSAGE:2023-05-16 11h43.28 UTC:2537: Status of task Immediate scan of IP 192.168.234.160 (50aad276-732a-417d-8d5e-d6ea0a09a2e3) has changed to Done
event task:MESSAGE:2023-05-16 11h43.28 UTC:2537: Status of task Immediate scan of IP 192.168.234.160 (50aad276-732a-417d-8d5e-d6ea0a09a2e3) has changed to Interrupted

**Comment by immauss** [comment]
```
md manage:WARNING:2023-05-16 11h43.28 UTC:2537: OSP start_scan 5e3a68cf-797d-4e34-81c2-f22d7bc857e1: VTs list is empty
```

Looks like you might be starting this scan a little early as you have no VTs available. 

How did you start the container and which tag are you running? 

If you start it without the "SKIPSYNC=true" option, then it can take some time before the DB is ready. With that option set, it only takes about 5 minutes normally for everything to sync-up and be ready. 

-Scott

**Comment by xaled1** [comment]
Hi Scot,

Thank you it seam to be indeed a timing issue. Was a bit impatient :)

==> /usr/local/var/log/gvm/openvas.log <==
sd   main:MESSAGE:2023-05-16 16h00.12 utc:20077:98f65ccb-5494-4a8a-936b-d5d67df3dfe3: openvas 22.6.2 started
sd   main:MESSAGE:2023-05-16 16h00.14 utc:20077:98f65ccb-5494-4a8a-936b-d5d67df3dfe3: Vulnerability scan 98f65ccb-5494-4a8a-936b-d5d67df3dfe3 started: Target has 1 hosts: 192.168.234.160, with max_hosts = 20 and max_checks = 4
libgvm boreas:MESSAGE:2023-05-16 16h00.14 utc:20077:98f65ccb-5494-4a8a-936b-d5d67df3dfe3: Alive scan 98f65ccb-5494-4a8a-936b-d5d67df3dfe3 started: Target has 1 hosts
libgvm boreas:MESSAGE:2023-05-16 16h00.15 utc:20077:98f65ccb-5494-4a8a-936b-d5d67df3dfe3: Alive scan 98f65ccb-5494-4a8a-936b-d5d67df3dfe3 finished in 1 seconds: 1 alive hosts of 1.
sd   main:MESSAGE:2023-05-16 16h00.16 utc:20095:98f65ccb-5494-4a8a-936b-d5d67df3dfe3: Vulnerability scan 98f65ccb-5494-4a8a-936b-d5d67df3dfe3 started for host: 192.168.234.160

**Comment by xaled1** [comment]
Issue closed
