### ISSUE TITLE
Enterprise License

### ISSUE THREAD

**Issue by sn-mm** [immauss/openvas#189]
Docker-compose with latest version (22.4.16)
I tried putting the enterprise key in /etc/gvm/ and it was recogized.

Found Greenbone Enterprise Feed access key, trying to synchronize with Greenbone CERT data Repository ...

But seems to remain with community feeds. 
![image](https://github.com/immauss/openvas/assets/135227228/39488bfb-5781-494c-836f-94ec21e58df1)

Can the container work with enterprise feeds?

**Comment by sn-mm** [comment]
I simply asked here: https://www.greenbone.net/en/testnow/
It's a Trial, i could use it in their VM. 
I'm not even sure if I can buy their commercial products and use anyway a simple container for doing my activities, in different networks.
If you need for the license, I can share it with you.
Thanks for the help.
Marco

**Comment by immauss** [comment]
When I get a few spare cycles, I'm going to give this a try. 

Thanks,
Scott

**Comment by sn-mm** [comment]
I'm not sure since a bit of time has passed, but I remember that I created
a file exactly where it was expected, and pasted it without any
modification, as you would do with any other license. It worked smoothly.
Marco

**Comment by sn-mm** [comment]
Hi Scott,
this is really exciting news! I found this command really useful:

docker exec -it <container name> /scripts/synch.sh

Previously I had to launch each sync job manually. (I don't know if you
added it recently to the docs)
Thank you!
Marco

**Comment by immauss** [comment]
Glad that helped. 

Just double checked .... It's in the docs. :) 

-Scott

**Comment by bjoernricks** [comment]
Hey, just for your information, distributing a trial key and sharing it on several machines at the same time is **not** allowed. Also distributing the content of the enterprise feed is considered a license violation.

**Comment by immauss** [comment]
@bjoernricks 

Of course. 

To be clear, I have never, nor would I ever, violate or condone the violation of Greenbone's or anyone else's license agreements through the distribution of this container or any other means. I have in fact, quite recently, had my operations here reviewed by a lawyer to ensure I was not violating any published licenses involved in the creation of this container image. This thread, as can be clearly seen, is about the feasibility of using the trial enterprise key or any key from Greenbone in this container distribution.  My testing was conducted in an isolated environment, and the enterprise feed data pulled during testing have not, nor will they ever, be included in the distribution of this container or any other product from Immauss Cybersecurity. 

-Scott

**Comment by bjoernricks** [comment]
I didn't assume you were violating our licenses. It just wanted to be clear about our enterprise feed usage.

**Comment by immauss** [comment]
@bjoernricks all good. 
I realized the title of this particular thread could be misleading, and I just wanted to make sure anyone reading this in future understood our position on such things. 

-Scott

**Comment by immauss** [comment]
For anyone interested, this does work with the container. However, as of 9 May 2024, it is not cost-effective unless you are scanning thousands of machines, to purchase access to the Enterprise Feeds.
