### ISSUE TITLE
GVM 22.5

### ISSUE THREAD

**Issue by mgoeppl** [immauss/openvas#193]
Hi,
Just wanted to ask if there’s an upgrade planned for the latest release of GVM? If yes, do you know when it will be released, and do you need help?
Cheers!

**Comment by immauss** [comment]
@mgoeppl Yes.
I'll have some time in the next few days. Unless there are major build changes, it usually doesn't take me too long to get the build updated. Stay tuned here for testing and possible requests for assistance. 

Thanks,
Scott

**Comment by immauss** [comment]
So there a 22.4.17-beta ... 
It should be running the 22.5 gvmd ...
Or maybe it will end up as 22.5.01 ... not sure yet.

**Comment by immauss** [comment]
OK ... It's 22.4.18

:)
