### ISSUE TITLE
Accessing the web interface

### ISSUE THREAD

**Issue by NeikaDragon** [immauss/openvas#194]
I run this command 

```shell
docker run --detach --publish 8080:9392 -e PASSWORD="admin" -e HTTPS=true --volume openvas:/data --name openvas immauss/openvas
``` 
and it appears the container starts fine, but I can not access the web interface at all. For reference, I am in an environment where Ubuntu is on a virtual machine with an IP of 10.100.21.21 and I am ssh'd into the server from 10.100.0.108.

Am I missing a step in the documentation found here: https://immauss.github.io/openvas/ ?
What command do I need to run to tail logs?

**Comment by immauss** [comment]
You can check the logs with:
`docker logs -f openvas`

You should be able to access the website, based on the info you gave, at:
https://10.100.21.21:8080

If not, please attache contents of:
`docker logs openvas `
and I'll see if I can spot a problem.

**Comment by immauss** [comment]
If you're still having issues with this, please open a new issue. 

Thanks,
Scott
