### ISSUE TITLE
[multi-container] overriding environment variables

### ISSUE THREAD

**Issue by matchaxnb** [immauss/openvas#195]
Hey there,

The way environment variables are managed in docker-compose.yml in the multi-container setup is wrong. It leaves me under the impression that .env values will be carried over to the docker containers but they are not. See https://docs.docker.com/compose/environment-variables/env-file/ for details.

I will propose changes in a pull request, will link it here. The solution I'm going to propose is as follows:

1/ set all variables in .env to their default values
2/ set "KEY=$KEY" for each variable where relevant in `docker-compose.yml`.

Cheers.

**Comment by immauss** [comment]
Just merged. I'll do some building and testing and hopefully have new images pushed soon .

Thanks,
-Scott
