### ISSUE TITLE
Error in path prevents feed update

### ISSUE THREAD

**Issue by LoZio** [immauss/openvas#198]
Using latest docker from today (immauss/openvas       latest    8e199e22e674   4 days ago)
/scripts/sync.sh only grabs NOTUS and NASL plugins.
SCAP, CERT and GVMD_DATA fail, not finding `greenbone-feed-sync`
The script searches it in `/usr/local/sbin/greenbone-feed-sync` while it is in `/usr/local/bin/greenbone-feed-sync`.

Manually patching the script removing the "s" runs the update

**Comment by LoZio** [comment]
Welp, just notices pull request #197 for this ...

**Comment by immauss** [comment]
Yup.... I just merged it ... 
doing the rebuilds now. Should have the updated imaged pushed later ... 

Thanks,
Scott
