### ISSUE TITLE
Redis healtcheck fail

### ISSUE THREAD

**Issue by ciclonite** [immauss/openvas#200]
Hi,
on ubuntu 22.04 with docker, when i start the latest release the healtcheck fails to redis:
==> /usr/local/var/log/gvm/healthchecks.log <==
 HEALTHECHECK FAILED ! 
 These services failed
 openvas redis

But when i launch manually the check : 
root@e0ff1cba700e:/# redis-cli -s /run/redis/redis.sock ping
PONG
The redis seems to be ok.
Thanks.

**Comment by immauss** [comment]
Yes... this is curious. I've run in to this once or twice in my  setup, but have not been able to replicate consitently. A container restart will usually resolve it. 

Can you please provide more details on how you started the container?  

Thanks,
-Scott

**Comment by ciclonite** [comment]
Sure!
Thanks, for your GREAT JOB!
I've created the new volume for the image version : 
docker volume create ovas-230713
after that the first time i've launched : 
docker run --detach --publish 8080:9392 -e PASSWORD="xxx" --volume ovas-230713:/data --name openvas-230713 immauss/openvas:22.4.19 
and when the error appear i've stopped the container with : 
docker stop containerID
and restarted with : 
docker start containerID

The log show that redis start successfully, and after some time the healthcheck fails:
tarting gvmd & openvas in a single container !!
Wait for redis socket to be created...
Testing redis status...
Redis ready.
Starting PostgreSQL...
waiting for server to start....2023-07-13 08:39:12.918 UTC [31] LOG:  redirecting log output to logging collector process
2023-07-13 08:39:12.918 UTC [31] HINT:  Future log output will appear in directory "/data/var-log/postgresql".
 done

.....
.....
....

==> /usr/local/var/log/gvm/redis-server.log <==
20:C 13 Jul 2023 08:29:40.504 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
20:C 13 Jul 2023 08:29:40.504 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=20, just started
20:C 13 Jul 2023 08:29:40.504 # Configuration loaded
20:M 13 Jul 2023 08:29:40.507 # Server initialized
20:M 13 Jul 2023 08:29:40.507 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
20:C 13 Jul 2023 08:39:11.860 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
20:C 13 Jul 2023 08:39:11.860 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=20, just started
20:C 13 Jul 2023 08:39:11.860 # Configuration loaded
20:M 13 Jul 2023 08:39:11.862 # Server initialized
20:M 13 Jul 2023 08:39:11.862 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

==> /usr/local/var/log/gvm/ospd-openvas.log <==
OSPD[533] 2023-07-13 08:39:48,675: INFO: (ospd_openvas.daemon) Loading VTs. Scans will be [requested|queued] until VTs are loaded. This may take a few minutes, please wait...

==> /usr/local/var/log/gvm/gvmd.log <==
md   main:MESSAGE:2023-07-13 08h40.11 utc:594:    Greenbone Vulnerability Manager version 22.5.3 (DB revision 255)
md manage:   INFO:2023-07-13 08h40.11 utc:594:    Getting scanners.
md   main:MESSAGE:2023-07-13 08h40.14 utc:601:    Greenbone Vulnerability Manager version 22.5.3 (DB revision 255)
md manage:   INFO:2023-07-13 08h40.14 utc:601:    Verifying scanner.

==> /usr/local/var/log/gvm/healthchecks.log <==
 Healthchecks completed with no issues.

after some times : 

==> /usr/local/var/log/gvm/gvmd.log <==
md   main:MESSAGE:2023-07-13 08h41.17 utc:655:    Greenbone Vulnerability Manager version 22.5.3 (DB revision 255)
md manage:   INFO:2023-07-13 08h41.17 utc:655:    Getting scanners.
md   main:MESSAGE:2023-07-13 08h41.19 utc:663:    Greenbone Vulnerability Manager version 22.5.3 (DB revision 255)
md manage:   INFO:2023-07-13 08h41.19 utc:663:    Verifying scanner.

==> /usr/local/var/log/gvm/healthchecks.log <==
 Healthchecks completed with no issues.

==> /usr/local/var/log/gvm/gvmd.log <==
md   main:MESSAGE:2023-07-13 08h42.22 utc:747:    Greenbone Vulnerability Manager version 22.5.3 (DB revision 255)
md manage:   INFO:2023-07-13 08h42.22 utc:747:    Getting scanners.
md   main:MESSAGE:2023-07-13 08h42.25 utc:753:    Greenbone Vulnerability Manager version 22.5.3 (DB revision 255)
md manage:   INFO:2023-07-13 08h42.25 utc:753:    Verifying scanner.

==> /usr/local/var/log/gvm/healthchecks.log <==
 Healthchecks completed with no issues.
gsad  gmp-Message: 08:42:30.956: Authentication success for 'admin' from 172.17.0.1

==> /usr/local/var/log/gvm/gvmd.log <==
md   main:MESSAGE:2023-07-13 08h43.29 utc:937:    Greenbone Vulnerability Manager version 22.5.3 (DB revision 255)
md manage:   INFO:2023-07-13 08h43.29 utc:937:    Getting scanners.
md   main:MESSAGE:2023-07-13 08h43.54 utc:956:    Greenbone Vulnerability Manager version 22.5.3 (DB revision 255)
md manage:   INFO:2023-07-13 08h43.54 utc:956:    Verifying scanner.

==> /usr/local/var/log/gvm/healthchecks.log <==
 HEALTHECHECK FAILED ! 
 These services failed
 openvas redis

==> /usr/local/var/log/gvm/gvmd.log <==
md   main:MESSAGE:2023-07-13 08h44.39 utc:1010:    Greenbone Vulnerability Manager version 22.5.3 (DB revision 255)
md manage:   INFO:2023-07-13 08h44.39 utc:1010:    Getting scanners.


After this point and after already restarted the container the error persist.

Thanks.

**Comment by immauss** [comment]
OK .. there is an issue with gmvf 22.5.3, so yesterday, I pushed tag 22.4.20 with gvm 22.4.20. This 'might' be your problem. Can you try with either the latest tag or 22.4.20 ? 

Thanks,
Scott

**Comment by cybernecromancy** [comment]
hi @immauss : with the new version all works flawless! Thank you.

**Comment by immauss** [comment]
Glad it worked out ! 

Thanks,
-Scott
