### ISSUE TITLE
Upgrade scanner?

### ISSUE THREAD

**Issue by nickdtong** [immauss/openvas#207]
Is there a method of easily upgrading the scanner? rather than backing up the data and then restoring it to a new container? I looked around, but I didn't see any of note of upgrade in the documentation. Might have missed it

**Comment by Remy541** [comment]
I update without any issues whenever I can, without having to backup and restore anything. By your description it might be the case you are not using any persistent volumemapping?

**Comment by immauss** [comment]
@nickdtong, @Remy541 is 100% correct. As long as you are using a persistent volume, you need only pull the latest image tag and then start a new container with the same volume. 

You are also right though. I'll add something to the documentation to make this more clear.

Thank you,
-Scott

**Comment by Remy541** [comment]
If it helps (documentation), here's a working docker-compose.yaml:

`
version: "2"
services:
  openvas:
    image: immauss/openvas:22.4.21
    container_name: openvas
    environment:
      - PASSWORD=AVerySecretPassword123!!11
    ports:
      - 9500:9392
    volumes:
      - /data/openvas/:/data
    restart: always
`

Change the first number in the ports definition to have the web interface available at that port. 

When updating, just edit this file, change the image tag (change 22.4.21 for the newest one available), and go for a 

`
docker compose down && docker compose up -d
`

Hope it helps anyone :)

-Remy

**Comment by immauss** [comment]
You can also use the "latest" tag in the docker-compose. Then you would only need run:
```
docker-compose pull
docker-compose up -d 
```

-Scott

**Comment by Remy541** [comment]
Yes, that's true, although I personally don't use it that often because I want to have a grip on what versions I'm running. Maybe not too relevant in this case but anyway, if you'd want to go that route, it would be a good habit to have a cronjob in place that periodically does the pulling of a new image and restarting it. 

Good stuff Scott, thanks for this repo!

**Comment by immauss** [comment]
@nickdtong Does that answer your questions?
