### ISSUE TITLE
Changing "max-ips-per-target" in gvmd

### ISSUE THREAD

**Issue by EvilCookie25** [immauss/openvas#210]
Hi guys,

since the command "gvmd --max-ips-per-target=70000" its not working because GVM launches at start and can't update it in real time, and if I see the processes, I can see this service already has multiples arguments:

_gvmd -a 0.0.0.0 -p 9390 --listen-group=gvm --osp-vt-update=/var/run/ospd/ospd-openvas.sock --max-email-attachment-size=64000000 --max-email-include-size=64000000 --max-email-message-size=64000000 etc_

How can I update/add this command to the launch start of the GVM?

Thank you so much!!

**Comment by immauss** [comment]
You can add custom arguments to GVMD with -e GVMD_ARGS="You new arguments here as if on command line" 

So ...  in your case:
```
-e GVMD_ARGS="--max-ips-per-target=70000"
```

Make sure you have plenty of memory available. The container will do weird things when it runs out of memory. I don' tknow of anyone ever scanning that many targets with the container. Usually things die from OOM Killer. 

If you have the time, I'd really appreciate any feedback you could give me on running with this many targets in the container. 

Thanks,
-Scott

**Comment by EvilCookie25** [comment]
Thank you for the quick response immauss!!!

I'm building the new container right now, so I'll update you tomorrow morning when it finished and I test this new setting. I have 32GB RAM for this container only, I hope should be enough within the test I've done with multiples tasks running at the same time.

The new scans should start the next week so I can update you with some real productivity usage on the network.

**Comment by immauss** [comment]
That's outstanding!

Thank you,
-Scott

**Comment by EvilCookie25** [comment]
Hi immauss!!

I already deployed all the vnets successfully, all went smooth with no errors. We can close this topic and if you don't mind I can reach you when our scans start with some performance statistics and behaviors.

Thank you so so much for the help!!

**Comment by immauss** [comment]
Outstanding!!

Thank you
-Scott

**Comment by EvilCookie25** [comment]
@immauss Some time has past but I was doing deep testing and I can confirm no problem at all working with almost 50k in a unique task. No delays, without RAM or stability problems, all went smooth and successfull!!

**Comment by immauss** [comment]
That is great news. 
Can you tell me how much RAM is available to the container? 
And what version of the container you are running? 

Thanks,
Scott

**Comment by EvilCookie25** [comment]
The host has 8 vCPUs and 32GB RAM. It has only 2 containers, a "portainer" with minimal resources and OpenVAS which is set to use 7 vCPUs and total amount of RAM. I'm using the latest version (docker.io/immauss/openvas:latest | 1.6 GB | 2023-07-31 20:10:24)

This is an example of resources used on a current scan (percentaje like 55% of the task) of unique target with 22k IPs:

![image](https://github.com/immauss/openvas/assets/124726916/df4a2f88-d42e-4df3-8ca8-1400c42de2ba)

Thank you so much!!
