### ISSUE TITLE
sql_exec_internal: PQexec failed: ERROR:  extension "pg-gvm" has no update path

### ISSUE THREAD

**Issue by brandonctaylor67** [immauss/openvas#212]
Greetings,

On the latest docker image, I am getting the following error:

Docker Image Info:
https://hub.docker.com/layers/immauss/openvas/latest/images/sha256-c4558d666167ba552f67ece999e8f58a859eb5acc2199762a07d9cf56af2c8ba?context=explore

```
(gvmd:57): md manage-WARNING **: 05:19:32.788: sql_exec_internal: PQexec failed: ERROR:  extension "pg-gvm" has no update path from version "22.6" to version "22.5"(7)
``` 

I believe I had a similar issue on the one of the last updates and a patch seemed to fix it.

Any help is appreciated!

**Comment by immauss** [comment]
Yes, this should have been fixed a week or so ago. Are you certain you are on the latest? Can you please paste the output from:
```
docker exec -it  <container name> cat /gvm-versions
```

**Comment by timscotland** [comment]
We patched a box this morning and are seeing the same.
```

PQexec failed: ERROR:  extension \"pg-gvm\" has no update path from version \"22.6\" to version \"22.5\"\n","stream":"stderr","time":"2023-08-07T08:46:11.039596249Z"}
{"log":" (7)\n","stream":"stderr","time":"2023-08-07T08:46:11.039605265Z"}
```

**Comment by frawmazh** [comment]
Just pulled and restarted and got the same behavior.
--
[root@scanse01 ~]# docker exec -it openvas cat /gvm-versions
pg_gvm=v22.5.1
notus_scanner=v22.5.0
gvmd=v22.5.5
openvas=v22.7.3
openvas_smb=v22.5.3
gvm_libs=v22.6.3
openvas_scanner=v22.7.3
gsa=v22.5.0
gsad=v22.5.1
ospd=v21.4.4
ospd_openvas=v22.5.3
python_gvm=v23.5.1
gvm_tools=v23.4.0
greenbone_feed_sync=v23.7.0

**Comment by dustinbird** [comment]
I ran the latest Docker image this morning and received the same issue.  The versions are showing as follows:

pg_gvm=v22.5.1
notus_scanner=v22.5.0
gvmd=v22.5.5
openvas=v22.7.3
openvas_smb=v22.5.3
gvm_libs=v22.6.3
openvas_scanner=v22.7.3
gsa=v22.5.0
gsad=v22.5.1
ospd=v21.4.4
ospd_openvas=v22.5.3
python_gvm=v23.5.1
gvm_tools=v23.4.0
greenbone_feed_sync=v23.7.0

**Comment by immauss** [comment]
Thanks.

Looks like there was a regression some how.
Pg_gvm should be > 22.6. I’ll have to rebuild it. I’ll try to get it scheduled this morning as soon as I can get to my desk.


-Scott

**Comment by immauss** [comment]
OK ... looks like the buildrc didn't get commited to github, so when the weekly rebuild ran to update the DB, it used the older version. 

There is a new latest with the correct versions and I'm running the DB update again. 

Thanks for the note and keeping me on my toes! 


-Scott

**Comment by immauss** [comment]
As an additional follow up, I modified the refresh process to always build from latest-slim. This 'should' prevent this from happening in the future and greatly speed up the refresh process.

**Comment by timscotland** [comment]
Just because I know it's good to have, that build did resolve the issue and it's now running on 2 of our 3 openVAS instances.  Thank you!
