### ISSUE TITLE
Problems starting a 22.4.28 container

### ISSUE THREAD

**Issue by sgaravat** [immauss/openvas#219]
I issued:

docker volume create openvas-22.4.28
docker run --detach --publish 443:9392 -e PASSWORD="xxx" --volume openvas-22.4.28:/data --name openvas -e HTTPS=true -e  USERNAME="admin" immauss/openvas:22.4.28

but the container doesn't start
I copied below [*] the container log
Are those "relation xxx already exists" error messages expected ?

Thanks, Massimo

[*]
root@vnode-0:~# docker logs openvas 
starting container at: Sun Aug 27 13:47:22 UTC 2023
Setting up container filesystem
cp: cannot stat '/usr/local/var/lib/*': No such file or directory
cp: cannot stat '/var/lib/gvm/*': No such file or directory
cp: cannot stat '/var/lib/notus/*': No such file or directory
cp: cannot stat '/var/lib/openvas/*': No such file or directory
Using default gvm logging config
Using default gvm logging config
Using default openvas logging config
Choosing container start method from:

Starting gvmd & openvas in a single container !!
Wait for redis socket to be created...
Testing redis status...
Redis ready.
Creating postgresql.conf and pg_hba.conf
Starting PostgreSQL...
waiting for server to start....2023-08-27 13:47:25.903 UTC [100] LOG:  redirecting log output to logging collector process
2023-08-27 13:47:25.903 UTC [100] HINT:  Future log output will appear in directory "/data/var-log/postgresql".
 done
server started
pg exit with 0 .
Checking for existing DB
Loading Default Database
Running first start configuration...
Generating certs...
Using /tmp/tmp.fgVvlOwVzM to temporarily store files.
Creating new certificate infrastructure in automatic mode.
Generating private key.
Generated private key in /tmp/tmp.fgVvlOwVzM/cakey.pem.
Generating certificate.
  Generating self signed certificate.
Generated self signed certificate in /tmp/tmp.fgVvlOwVzM/cacert.pem.
  CA certificate generated.
Installing certificate and key.
Install destinations do not exist as directories, attempting to create them.
Setting up directories
Installed private key to /var/lib/gvm/private/CA/cakey.pem.
Installed certificate to /var/lib/gvm/CA/cacert.pem.
  CA certificate and key installed.
Generating private key.
Generated private key in /tmp/tmp.fgVvlOwVzM/serverkey.pem.
Generating certificate.
  Generating certificate request.
Generated certificate request in /tmp/tmp.fgVvlOwVzM/serverrequest.pem.
Signing certificate request.
Signed certificate request in /tmp/tmp.fgVvlOwVzM/serverrequest.pem with CA certificate in /var/lib/gvm/CA/cacert.pem to generate certificate in /tmp/tmp.fgVvlOwVzM/servercert.pem
  Server certificate generated.
Installing certificate and key.
Installed private key to /var/lib/gvm/private/CA/serverkey.pem.
Installed certificate to /var/lib/gvm/CA/servercert.pem.
  Server certificate and key installed.
Generating private key.
Generated private key in /tmp/tmp.fgVvlOwVzM/clientkey.pem.
Generating certificate.
  Generating certificate request.
Generated certificate request in /tmp/tmp.fgVvlOwVzM/clientrequest.pem.
Signing certificate request.
Signed certificate request in /tmp/tmp.fgVvlOwVzM/clientrequest.pem with CA certificate in /var/lib/gvm/CA/cacert.pem to generate certificate in /tmp/tmp.fgVvlOwVzM/clientcert.pem
  Client certificate generated.
Installing certificate and key.
Installed private key to /var/lib/gvm/private/CA/clientkey.pem.
Installed certificate to /var/lib/gvm/CA/clientcert.pem.
  Client certificate and key installed.
Removing temporary directory /tmp/tmp.fgVvlOwVzM.
NEWDB=false
LOADDEFAULT=true
########################################
Creating a base DB from /usr/lib/base-db.xz
########################################
ERROR:  relation "host_details_by_host" already exists
ERROR:  relation "host_identifiers_by_host" already exists
ERROR:  relation "host_identifiers_by_value" already exists
ERROR:  relation "host_max_severities_by_host" already exists
ERROR:  relation "host_oss_by_host" already exists
ERROR:  relation "nvt_selectors_by_family_or_nvt" already exists
ERROR:  relation "nvt_selectors_by_name" already exists
ERROR:  relation "nvts_by_creation_time" already exists
ERROR:  relation "nvts_by_cvss_base" already exists
ERROR:  relation "nvts_by_family" already exists
ERROR:  relation "nvts_by_modification_time" already exists
ERROR:  relation "nvts_by_name" already exists
ERROR:  relation "nvts_by_solution_type" already exists
ERROR:  relation "permissions_by_name" already exists
ERROR:  relation "permissions_by_resource" already exists
ERROR:  relation "report_counts_by_report_and_override" already exists
ERROR:  relation "report_host_details_by_report_host_and_name" already exists
ERROR:  relation "report_hosts_by_report_and_host" already exists
ERROR:  relation "reports_by_task" already exists
ERROR:  relation "result_nvt_reports_by_report" already exists
ERROR:  relation "results_by_date" already exists
ERROR:  relation "results_by_host_and_qod" already exists
ERROR:  relation "results_by_nvt" already exists
ERROR:  relation "results_by_report" already exists
ERROR:  relation "results_by_task" already exists
ERROR:  relation "tag_resources_by_resource" already exists
ERROR:  relation "tag_resources_by_resource_uuid" already exists
ERROR:  relation "tag_resources_by_tag" already exists
ERROR:  relation "tag_resources_trash_by_tag" already exists
ERROR:  relation "tls_certificate_locations_by_host_ip" already exists
ERROR:  relation "tls_certificate_origins_by_origin_id_and_type" already exists
ERROR:  relation "vt_refs_by_vt_oid" already exists
ERROR:  relation "vt_severities_by_vt_oid" already exists
NOTICE:  relation "vt_severities" already exists, skipping
Unpacking base feeds data from /usr/lib/var-lib.tar.xz
Base DB and feeds collected on:
Sun Aug 13 03:01:06 UTC 2023
Checking DB Version
Current GVMd database version is  255
NOTICE:  relation "vt_severities" already exists, skipping
NOTICE:  relation "vt_severities" already exists, skipping
Migrate the database if needed.
Updating NVTs and other data
This could take a while if you are not using persistent storage for your NVTs
 or this is the first time pulling to your persistent storage.
 the time will be mostly dependent on your available bandwidth.
 We sleep for 2 seconds between sync command to make sure everything closes
 and it doesnt' look like we are connecting more than once.
-rw-r--r-- 1 root root 96935364 Aug 25 23:11 /usr/lib/var-lib.tar.xz
Checking age of current data feeds from Greenbone.
ImageFeeds=1693005113
InstalledFeeds=1693145133
Updating local feeds with newer image feeds.
Syncing all feeds from GB
Trying to acquire lock on /var/lib/openvas/feed-update.lock
Acquired lock on /var/lib/openvas/feed-update.lock
⠋ Downloading Notus files from 
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/vt-data/
notus/ to /var/lib/notus⠋ Downloading NASL files from 
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/vt-data/
nasl/ to /var/lib/openvas/pluginsReleasing lock on /var/lib/openvas/feed-update.lock

Trying to acquire lock on /var/lib/gvm/feed-update.lock
Acquired lock on /var/lib/gvm/feed-update.lock
⠋ Downloading SCAP data from 
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/scap-dat
a/ to /var/lib/gvm/scap-data⠋ Downloading CERT-Bund data from 
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/cert-dat
a/ to /var/lib/gvm/cert-data⠋ Downloading gvmd data from 
rsync://feed.community.greenbone.net/community/data-feed/22.04/ to 
/var/lib/gvm/data-objects/gvmd/22.04Releasing lock on /var/lib/gvm/feed-update.lock

Starting Greenbone Vulnerability Manager...
root@vnode-0:~#

**Comment by immauss** [comment]
Hmmm .....
I'm unable to consistently reproduce this. 
So ... 
The first time I tried, I copied and pasted your commands to my Mac with Docker desktop, and it failed as yours did. 
I repeated it on my dev box, and it ran fine ... Though I did see this once previously, made a change that I thought fixed it because I did not see it happen again. Apparently, that didn't actually fix it. 

In the end, I can't make this happen more than once on a host, so I have no idea how to figure it out. Does it work on your system if you run it a second time? Make sure you delete the volume before you try the second time. 

Thanks,
Scott

**Comment by sgaravat** [comment]
Thanks Scott for the prompt feedback
I deleted the volume and retried. 
This is the output of docker logs:

root@vnode-0:~# docker logs openvas
starting container at: Sun Aug 27 18:03:16 UTC 2023
Setting up container filesystem
cp: cannot stat '/usr/local/var/lib/*': No such file or directory
cp: cannot stat '/var/lib/gvm/*': No such file or directory
cp: cannot stat '/var/lib/notus/*': No such file or directory
cp: cannot stat '/var/lib/openvas/*': No such file or directory
Using default gvm logging config
Using default gvm logging config
Using default openvas logging config
Choosing container start method from:

Starting gvmd & openvas in a single container !!
Wait for redis socket to be created...
Testing redis status...
Redis ready.
Creating postgresql.conf and pg_hba.conf
Starting PostgreSQL...
waiting for server to start....2023-08-27 18:03:25.641 UTC [100] LOG:  redirecting log output to logging collector process
2023-08-27 18:03:25.641 UTC [100] HINT:  Future log output will appear in directory "/data/var-log/postgresql".
 done
server started
pg exit with 0 .
Checking for existing DB
Loading Default Database
Running first start configuration...
Generating certs...
Using /tmp/tmp.fz1FINxNu0 to temporarily store files.
Creating new certificate infrastructure in automatic mode.
Generating private key.
Generated private key in /tmp/tmp.fz1FINxNu0/cakey.pem.
Generating certificate.
  Generating self signed certificate.
Generated self signed certificate in /tmp/tmp.fz1FINxNu0/cacert.pem.
  CA certificate generated.
Installing certificate and key.
Install destinations do not exist as directories, attempting to create them.
Setting up directories
Installed private key to /var/lib/gvm/private/CA/cakey.pem.
Installed certificate to /var/lib/gvm/CA/cacert.pem.
  CA certificate and key installed.
Generating private key.
Generated private key in /tmp/tmp.fz1FINxNu0/serverkey.pem.
Generating certificate.
  Generating certificate request.
Generated certificate request in /tmp/tmp.fz1FINxNu0/serverrequest.pem.
Signing certificate request.
Signed certificate request in /tmp/tmp.fz1FINxNu0/serverrequest.pem with CA certificate in /var/lib/gvm/CA/cacert.pem to generate certificate in /tmp/tmp.fz1FINxNu0/servercert.pem
  Server certificate generated.
Installing certificate and key.
Installed private key to /var/lib/gvm/private/CA/serverkey.pem.
Installed certificate to /var/lib/gvm/CA/servercert.pem.
  Server certificate and key installed.
Generating private key.
Generated private key in /tmp/tmp.fz1FINxNu0/clientkey.pem.
Generating certificate.
  Generating certificate request.
Generated certificate request in /tmp/tmp.fz1FINxNu0/clientrequest.pem.
Signing certificate request.
Signed certificate request in /tmp/tmp.fz1FINxNu0/clientrequest.pem with CA certificate in /var/lib/gvm/CA/cacert.pem to generate certificate in /tmp/tmp.fz1FINxNu0/clientcert.pem
  Client certificate generated.
Installing certificate and key.
Installed private key to /var/lib/gvm/private/CA/clientkey.pem.
Installed certificate to /var/lib/gvm/CA/clientcert.pem.
  Client certificate and key installed.
Removing temporary directory /tmp/tmp.fz1FINxNu0.
NEWDB=false
LOADDEFAULT=true
########################################
Creating a base DB from /usr/lib/base-db.xz
########################################
ERROR:  could not create unique index "meta_name_key"
DETAIL:  Key (name)=(update_nvti_cache) is duplicated.
ERROR:  could not create unique index "meta_pkey"
DETAIL:  Key (id)=(2) is duplicated.
ERROR:  could not create unique index "nvt_selectors_pkey"
DETAIL:  Key (id)=(1) is duplicated.
ERROR:  could not create unique index "permissions_pkey"
DETAIL:  Key (id)=(74) is duplicated.
ERROR:  could not create unique index "permissions_uuid_key"
DETAIL:  Key (uuid)=(b3b56a8c-c2fd-11e2-a135-406186ea4fc5) is duplicated.
ERROR:  could not create unique index "roles_pkey"
DETAIL:  Key (id)=(1) is duplicated.
ERROR:  could not create unique index "roles_uuid_key"
DETAIL:  Key (uuid)=(7a8cb5b4-b74d-11e2-8187-406186ea4fc5) is duplicated.
ERROR:  could not create unique index "scanners_pkey"
DETAIL:  Key (id)=(1) is duplicated.
ERROR:  could not create unique index "scanners_uuid_key"
DETAIL:  Key (uuid)=(08b69003-5fc2-4037-a479-93b440211c73) is duplicated.
ERROR:  could not create unique index "settings_pkey"
DETAIL:  Key (id)=(1) is duplicated.
ERROR:  relation "host_details_by_host" already exists
ERROR:  relation "host_identifiers_by_host" already exists
ERROR:  relation "host_identifiers_by_value" already exists
ERROR:  relation "host_max_severities_by_host" already exists
ERROR:  relation "host_oss_by_host" already exists
ERROR:  relation "nvt_selectors_by_family_or_nvt" already exists
ERROR:  relation "nvt_selectors_by_name" already exists
ERROR:  relation "nvts_by_creation_time" already exists
ERROR:  relation "nvts_by_cvss_base" already exists
ERROR:  relation "nvts_by_family" already exists
ERROR:  relation "nvts_by_modification_time" already exists
ERROR:  relation "nvts_by_name" already exists
ERROR:  relation "nvts_by_solution_type" already exists
ERROR:  relation "permissions_by_name" already exists
ERROR:  relation "permissions_by_resource" already exists
ERROR:  relation "report_counts_by_report_and_override" already exists
ERROR:  relation "report_host_details_by_report_host_and_name" already exists
ERROR:  relation "report_hosts_by_report_and_host" already exists
ERROR:  relation "reports_by_task" already exists
ERROR:  relation "result_nvt_reports_by_report" already exists
ERROR:  relation "results_by_date" already exists
ERROR:  relation "results_by_host_and_qod" already exists
ERROR:  relation "results_by_nvt" already exists
ERROR:  relation "results_by_report" already exists
ERROR:  relation "results_by_task" already exists
ERROR:  relation "tag_resources_by_resource" already exists
ERROR:  relation "tag_resources_by_resource_uuid" already exists
ERROR:  relation "tag_resources_by_tag" already exists
ERROR:  relation "tag_resources_trash_by_tag" already exists
ERROR:  relation "tls_certificate_locations_by_host_ip" already exists
ERROR:  relation "tls_certificate_origins_by_origin_id_and_type" already exists
ERROR:  relation "vt_refs_by_vt_oid" already exists
ERROR:  relation "vt_severities_by_vt_oid" already exists
ERROR:  there is no unique constraint matching given keys for referenced table "roles"
NOTICE:  relation "vt_severities" already exists, skipping
Unpacking base feeds data from /usr/lib/var-lib.tar.xz
Base DB and feeds collected on:
Sun Aug 13 03:01:06 UTC 2023
root@vnode-0:~#

**Comment by immauss** [comment]
Well .. that's different. 
I just started it on a VM that has never run it at all before, and it worked fine. So ...I'm at a complete loss here. 

I'm going to need to think on this a bit ... 

-Scott

**Comment by immauss** [comment]
If you restart the container, does it work? 

Thanks,
Scott

**Comment by sgaravat** [comment]
This is the log [*] of the container after the run

I then tried a "docker restart openvas" and this is the relevant log [**]


[*]
***@***.***:/home/sgaravat# docker logs openvas --follow
starting container at: Mon Aug 28 09:23:03 UTC 2023
Setting up container filesystem
cp: cannot stat '/usr/local/var/lib/*': No such file or directory
cp: cannot stat '/var/lib/gvm/*': No such file or directory
cp: cannot stat '/var/lib/notus/*': No such file or directory
cp: cannot stat '/var/lib/openvas/*': No such file or directory
Using default gvm logging config
Using default gvm logging config
Using default openvas logging config
Choosing container start method from:

Starting gvmd & openvas in a single container !!
Wait for redis socket to be created...
Testing redis status...
Redis ready.
Creating postgresql.conf and pg_hba.conf
Starting PostgreSQL...
waiting for server to start....2023-08-28 09:23:08.735 UTC [100] LOG:
 redirecting log output to logging collector process
2023-08-28 09:23:08.735 UTC [100] HINT:  Future log output will appear in
directory "/data/var-log/postgresql".
. done
server started
pg exit with 0 .
Checking for existing DB
Loading Default Database
Running first start configuration...
Generating certs...
Using /tmp/tmp.Len5nUl3Vg to temporarily store files.
Creating new certificate infrastructure in automatic mode.
Generating private key.
Generated private key in /tmp/tmp.Len5nUl3Vg/cakey.pem.
Generating certificate.
  Generating self signed certificate.
Generated self signed certificate in /tmp/tmp.Len5nUl3Vg/cacert.pem.
  CA certificate generated.
Installing certificate and key.
Install destinations do not exist as directories, attempting to create them.
Setting up directories
Installed private key to /var/lib/gvm/private/CA/cakey.pem.
Installed certificate to /var/lib/gvm/CA/cacert.pem.
  CA certificate and key installed.
Generating private key.
Generated private key in /tmp/tmp.Len5nUl3Vg/serverkey.pem.
Generating certificate.
  Generating certificate request.
Generated certificate request in /tmp/tmp.Len5nUl3Vg/serverrequest.pem.
Signing certificate request.
Signed certificate request in /tmp/tmp.Len5nUl3Vg/serverrequest.pem with CA
certificate in /var/lib/gvm/CA/cacert.pem to generate certificate in
/tmp/tmp.Len5nUl3Vg/servercert.pem
  Server certificate generated.
Installing certificate and key.
Installed private key to /var/lib/gvm/private/CA/serverkey.pem.
Installed certificate to /var/lib/gvm/CA/servercert.pem.
  Server certificate and key installed.
Generating private key.
Generated private key in /tmp/tmp.Len5nUl3Vg/clientkey.pem.
Generating certificate.
  Generating certificate request.
Generated certificate request in /tmp/tmp.Len5nUl3Vg/clientrequest.pem.
Signing certificate request.
Signed certificate request in /tmp/tmp.Len5nUl3Vg/clientrequest.pem with CA
certificate in /var/lib/gvm/CA/cacert.pem to generate certificate in
/tmp/tmp.Len5nUl3Vg/clientcert.pem
  Client certificate generated.
Installing certificate and key.
Installed private key to /var/lib/gvm/private/CA/clientkey.pem.
Installed certificate to /var/lib/gvm/CA/clientcert.pem.
  Client certificate and key installed.
Removing temporary directory /tmp/tmp.Len5nUl3Vg.
NEWDB=false
LOADDEFAULT=true
########################################
Creating a base DB from /usr/lib/base-db.xz
########################################
ERROR:  could not create unique index "meta_name_key"
DETAIL:  Key (name)=(update_nvti_cache) is duplicated.
ERROR:  could not create unique index "meta_pkey"
DETAIL:  Key (id)=(2) is duplicated.
ERROR:  could not create unique index "nvt_selectors_pkey"
DETAIL:  Key (id)=(1) is duplicated.
ERROR:  could not create unique index "permissions_pkey"
DETAIL:  Key (id)=(74) is duplicated.
ERROR:  could not create unique index "permissions_uuid_key"
DETAIL:  Key (uuid)=(a9801074-6fe2-11e4-9d81-406186ea4fc5) is duplicated.
ERROR:  could not create unique index "roles_pkey"
DETAIL:  Key (id)=(1) is duplicated.
ERROR:  could not create unique index "roles_uuid_key"
DETAIL:  Key (uuid)=(7a8cb5b4-b74d-11e2-8187-406186ea4fc5) is duplicated.
ERROR:  could not create unique index "scanners_pkey"
DETAIL:  Key (id)=(1) is duplicated.
ERROR:  could not create unique index "scanners_uuid_key"
DETAIL:  Key (uuid)=(08b69003-5fc2-4037-a479-93b440211c73) is duplicated.
ERROR:  could not create unique index "settings_pkey"
DETAIL:  Key (id)=(1) is duplicated.
ERROR:  relation "host_details_by_host" already exists
ERROR:  relation "host_identifiers_by_host" already exists
ERROR:  relation "host_identifiers_by_value" already exists
ERROR:  relation "host_max_severities_by_host" already exists
ERROR:  relation "host_oss_by_host" already exists
ERROR:  relation "nvt_selectors_by_family_or_nvt" already exists
ERROR:  relation "nvt_selectors_by_name" already exists
ERROR:  relation "nvts_by_creation_time" already exists
ERROR:  relation "nvts_by_cvss_base" already exists
ERROR:  relation "nvts_by_family" already exists
ERROR:  relation "nvts_by_modification_time" already exists
ERROR:  relation "nvts_by_name" already exists
ERROR:  relation "nvts_by_solution_type" already exists
ERROR:  relation "permissions_by_name" already exists
ERROR:  relation "permissions_by_resource" already exists
ERROR:  relation "report_counts_by_report_and_override" already exists
ERROR:  relation "report_host_details_by_report_host_and_name" already
exists
ERROR:  relation "report_hosts_by_report_and_host" already exists
ERROR:  relation "reports_by_task" already exists
ERROR:  relation "result_nvt_reports_by_report" already exists
ERROR:  relation "results_by_date" already exists
ERROR:  relation "results_by_host_and_qod" already exists
ERROR:  relation "results_by_nvt" already exists
ERROR:  relation "results_by_report" already exists
ERROR:  relation "results_by_task" already exists
ERROR:  relation "tag_resources_by_resource" already exists
ERROR:  relation "tag_resources_by_resource_uuid" already exists
ERROR:  relation "tag_resources_by_tag" already exists
ERROR:  relation "tag_resources_trash_by_tag" already exists
ERROR:  relation "tls_certificate_locations_by_host_ip" already exists
ERROR:  relation "tls_certificate_origins_by_origin_id_and_type" already
exists
ERROR:  relation "vt_refs_by_vt_oid" already exists
ERROR:  relation "vt_severities_by_vt_oid" already exists
ERROR:  there is no unique constraint matching given keys for referenced
table "roles"
NOTICE:  relation "vt_severities" already exists, skipping
Unpacking base feeds data from /usr/lib/var-lib.tar.xz
Base DB and feeds collected on:
Sun Aug 13 03:01:06 UTC 2023
Checking DB Version
Current GVMd database version is  255
NOTICE:  relation "vt_severities" already exists, skipping
NOTICE:  relation "vt_severities" already exists, skipping
Migrate the database if needed.
***@***.***:/home/sgaravat#
***@***.***:/home/sgaravat#
***@***.***:/home/sgaravat#


[**]
server started
pg exit with 0 .
Checking for existing DB
Running first start configuration...
NEWDB=false
LOADDEFAULT=false
Checking DB Version
Current GVMd database version is  255
NOTICE:  relation "vt_severities" already exists, skipping
NOTICE:  relation "vt_severities" already exists, skipping
NOTICE:  relation "vt_severities" already exists, skipping
Migrate the database if needed.
Updating NVTs and other data
This could take a while if you are not using persistent storage for your
NVTs
 or this is the first time pulling to your persistent storage.
 the time will be mostly dependent on your available bandwidth.
 We sleep for 2 seconds between sync command to make sure everything closes
 and it doesnt' look like we are connecting more than once.
-rw-r--r-- 1 root root 96935364 Aug 25 23:11 /usr/lib/var-lib.tar.xz
Checking age of current data feeds from Greenbone.
ImageFeeds=1693005113
InstalledFeeds=1693215566
Updating local feeds with newer image feeds.
Syncing all feeds from GB
Trying to acquire lock on /var/lib/openvas/feed-update.lock
Acquired lock on /var/lib/openvas/feed-update.lock
⠋ Downloading Notus files from
rsync://
feed.community.greenbone.net/community/vulnerability-feed/22.04/vt-data/
notus/ to /var/lib/notus⠋ Downloading NASL files from
rsync://
feed.community.greenbone.net/community/vulnerability-feed/22.04/vt-data/
nasl/ to /var/lib/openvas/pluginsReleasing lock on
/var/lib/openvas/feed-update.lock

Trying to acquire lock on /var/lib/gvm/feed-update.lock
Acquired lock on /var/lib/gvm/feed-update.lock
⠋ Downloading SCAP data from
rsync://
feed.community.greenbone.net/community/vulnerability-feed/22.04/scap-dat
a/ to /var/lib/gvm/scap-data⠋ Downloading CERT-Bund data from
rsync://
feed.community.greenbone.net/community/vulnerability-feed/22.04/cert-dat
a/ to /var/lib/gvm/cert-data⠋ Downloading gvmd data from
rsync://feed.community.greenbone.net/community/data-feed/22.04/ to
/var/lib/gvm/data-objects/gvmd/22.04Releasing lock on
/var/lib/gvm/feed-update.lock

Starting Greenbone Vulnerability Manager...
***@***.***:/home/sgaravat#

**Comment by sgaravat** [comment]
After some restart, I was eventually able to have the container running
Cheers, Massimo

**Comment by immauss** [comment]
OK ...

Please try tag: beta

immauss/openvas:beta

There was a date conversion that was not working well. I fixed this elsewhere in the startup scripts, but must have missed the one causing you issues.

I "think" it will resolve the problem.

If it works for you, I'll push it out as 22.4.29 & latest ...

Thanks,
-Scott

**Comment by immauss** [comment]
@sgaravat Outstanding!!
Thank you!

I should have it pushed out a little later today.

-Scott

**Comment by immauss** [comment]
Looks like 22.4.29 has resolved this. 

Thank you,
Scott
