### ISSUE TITLE
Issue starting a container using RUN

### ISSUE THREAD

**Issue by dustinbird** [immauss/openvas#222]
31/08/23 I downloaded the latest image to a OpenSUSE Leap 15.4  box but the container fell over on each attempt within 15 seconds.  Using the following command after a system prune the container showed in Docker PS for a period of no more than 15 seconds:

docker run --detach --publish 8443:9392 -e PASSWORD="********" --volume openvas:/data -e HTTPS=true --name openvas immauss/openvas:latest

I attempted to get the GVM Version in this small window of the container running but failed on multiple times.  When I decided to use a START command on the container to get the GVM version then the container started correctly and stayed running.

Details of GVM-Versions for reference:

gvmd=v22.8.0
gvm_libs=v22.7.0
openvas=v22.7.4
openvas_scanner=v22.7.4
openvas_smb=v22.5.3
notus_scanner=v22.5.0
gsa=v22.6.0
gsad=v22.5.2
ospd=v21.4.4
ospd_openvas=v22.5.4
pg_gvm=v22.6.1
python_gvm=v23.5.1
gvm_tools=v23.4.0
greenbone_feed_sync=v23.7.0

**Comment by immauss** [comment]
This sounds like the same problem as #216  , which is fixed in the 22.4.29.  This version should be live and the latest within the next hour.  You can try the beta tag, which "should" be identical in all the ways that count if you like. 

-Scott

**Comment by dustinbird** [comment]
Thank you so much.  I will have another look at this and I also have another server to update with the latest image tomorrow which will also attempt this latest build

**Comment by dustinbird** [comment]
I have once again had the same issue when updating one of my images this morning.  Currently three boxes updated in the last week did not have this issue, but today's image again could only stay in place using START.

GVM-Versions as follows:

gvmd=v22.8.0
gvm_libs=v22.7.0
openvas=v22.7.4
openvas_scanner=v22.7.4
openvas_smb=v22.5.3
notus_scanner=v22.6.0
gsa=v22.6.0
gsad=v22.5.2
ospd=v21.4.4
ospd_openvas=v22.6.0
pg_gvm=v22.6.1
python_gvm=v23.5.1
gvm_tools=v23.4.0
greenbone_feed_sync=v23.8.0

**Comment by immauss** [comment]
Dustin,
     Thanks. What do you mean by “Using Start”? Can you provide the logs from the failure? and the hash of the container image?


Thanks,
-Scott

**Comment by dustinbird** [comment]
Thank you.  I will get the logs over to you shortly.  

In the meantime to clarify the process, normally I start with a **"docker system prune -a"** command to clear all old images.  Then I use **"docker run  --detach --publish 8443:9392 -e PASSWORD="redacted" --volume openvas:/data -e HTTPS=true --name openvas immauss/openvas:latest"** and monitor it with **"docker ps"**

In both the logged cases in this ticket the container falls over.  But then starting the container with **"docker start openvas"** seems to work.

**Comment by dustinbird** [comment]
Sorry I am having some issues getting the logs from the server for you at present.  I will get these to you when I can SCP them from the server.

**Comment by immauss** [comment]
New version dropped today. Please let me know if you are still seeing the same issue with the latest.
