### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by bagusfahmi07** [immauss/openvas#226]
root@vm1:~# docker exec -it openvas /scripts/sync.sh
 Pulling NVTs from greenbone
Trying to acquire lock on /var/lib/openvas/feed-update.lock
Acquired lock on /var/lib/openvas/feed-update.lock
⠙ Downloading Notus files from
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/vt-d
ata/notus/ to /var/lib/notus
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in
name resolution
rsync error: error in socket IO (code 10) at clientserver.c(137)
[Receiver=3.2.3]

⠋ Downloading NASL files from
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/vt-d
ata/nasl/ to /var/lib/openvas/plugins
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in
name resolution
rsync error: error in socket IO (code 10) at clientserver.c(137)
[Receiver=3.2.3]

Releasing lock on /var/lib/openvas/feed-update.lock

 Pulling scapdata from greenbone
Trying to acquire lock on /var/lib/gvm/feed-update.lock
Acquired lock on /var/lib/gvm/feed-update.lock
⠼ Downloading SCAP data from
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/scap
-data/ to /var/lib/gvm/scap-data
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in
name resolution
rsync error: error in socket IO (code 10) at clientserver.c(137)
[Receiver=3.2.3]

Releasing lock on /var/lib/gvm/feed-update.lock

 Pulling cert-data from greenbone
Trying to acquire lock on /var/lib/gvm/feed-update.lock
Acquired lock on /var/lib/gvm/feed-update.lock
⠙ Downloading CERT-Bund data from
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/cert
-data/ to /var/lib/gvm/cert-data
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in
name resolution
rsync error: error in socket IO (code 10) at clientserver.c(137)
[Receiver=3.2.3]

Releasing lock on /var/lib/gvm/feed-update.lock

 Pulling latest GVMD Data from Greenbone
Trying to acquire lock on /var/lib/gvm/feed-update.lock
Acquired lock on /var/lib/gvm/feed-update.lock
⠋ Downloading gvmd data from
rsync://feed.community.greenbone.net/community/data-feed/22.04/ to
/var/lib/gvm/data-objects/gvmd/22.04
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in
name resolution
rsync error: error in socket IO (code 10) at clientserver.c(137)
[Receiver=3.2.3]

Releasing lock on /var/lib/gvm/feed-update.lock
 
how to fix it?

**Comment by immauss** [comment]
This looks like it might be a problem with your docker setup. The container is either not getting DNS resolution, or it is not able to connect to the internet at all:

```
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in
name resolution
```

**Comment by SebaViana** [comment]
Had the same issue recently with a minikube deployment, sadly I cannot give a concret solution.
Solved by stopping and starting again minikube.
