### ISSUE TITLE
Getting this message on docker-compose log `Sleeping here for 1d to debug`

### ISSUE THREAD

**Issue by arshiamohammdii** [immauss/openvas#228]
single container "version: 22.4.16"
I initiated the container using 'docker-compose up -d' with 'debug=true' configured, resulting in the appearance of these logs and subsequent stalling. Despite setting the debug option to false, it still failed to start. Should I wait longer and be more patient, or could this issue be related to the version I'm using?

**Comment by immauss** [comment]
There is a much newer version availabe. The latest should 22.4.31 with .32 approaching fast. 

That message is exactly what it says. In the course of working with this, the most likely point of failure has been when gvmd starts. So I added that sleep to debug "why" gvmd would fail. 

If it's still failing to start with debug=false, please send the full output from the logs along with a copy of the docker-compose file and I'll see if I can help.

-Scott

**Comment by arshiamohammdii** [comment]
migrated to the latest version and it worked, thanks

**Comment by immauss** [comment]
Outstanding! Thank you
