### ISSUE TITLE
Local docker build is not working anymore :(

### ISSUE THREAD

**Issue by condef5** [immauss/openvas#238]
Hi, firstly, thank you for this incredible tool. 

I've been attempting to build the Docker image locally, just as I've done in the past. However, I'm encountering some errors this time around. I would greatly appreciate it if you could guide me in the right direction. 🙏

<img width="954" alt="image" src="https://github.com/immauss/openvas/assets/21107031/15241877-697d-4093-a6cf-9691ea8b660c">

**Comment by immauss** [comment]
OK ... So when building multi architecture, the longest part of the build is for the react code, the javascript. When building in emulation, IT IS REALLLLLLYYY SLOW.. So, i set that aside and only build it from the amd64, and then it is just copied into the other images. I'm also only rebuilding the react code when the gsa version updates. This saves me a ton of time on rebuilds. 

 Take a look at bin/base-rebuild.sh. It's kinda written for my system, but look at the "-g" option. 

Also ... just curious, but why are you building it yourself?  The image on docker hub is rebuilt with the latest NVTs weekly.  Unless you are actually adding or changing something in the build, there's not a lot to be gained by building it yourself. 

If you have an idea for a mod / addition, please let me know. I'm open to change. 

Thanks,
Scott

**Comment by abnerrizzi** [comment]
Hi immauss. I dont know why he is trying to compile, but would be good to be able to build in our own machine.
But at lease I love build things from zero to hero hahahahahahahah

**Comment by immauss** [comment]
@condef5 
Did that help?

**Comment by condef5** [comment]
@immauss sorry for the late reply, thank you so mach Immaus 🙏
