### ISSUE TITLE
Loading report times out (gives error)

### ISSUE THREAD

**Issue by infestdead** [immauss/openvas#24]
After a scan is finished and report is generated - when I click on it - I just see the green dragon? head (the logo of openvas) blinking for about 1 minute and then I get an error:

Error while loading Results for Report 234bda13-3464-4e26-944c-308646df306b
Please try again.

![Untitled](https://user-images.githubusercontent.com/2643517/106669220-01951c00-65b4-11eb-8918-dc5a4f3009d5.png)

While the report is trying to load I see in top "postgres: gvm gvmd [local] SELECT" at 100% CPU, the disk utilization is fine around 2%, the drive is SSD.

Any ideas what I can test, look into?

**Comment by infestdead** [comment]
OK, I found the issue. I installed an nginx instance as a proxy to more easily handle SSL, but the default proxy timeout was not enough, increased the following 

        proxy_read_timeout 600;
        proxy_connect_timeout 600;
        proxy_send_timeout 600;

And that fixed it. Sorry for spamming :)

**Comment by immauss** [comment]
No worries.  And thanks.
I was actually considering a reverse proxy just yesterday to simplify the SSL setup and management. Would you mind sharing your configuration?

**Comment by infestdead** [comment]
Sure - here's what I use, that's a file in /etc/nginx/conf.d/mydomain.conf - the rest is default nginx. The config is mostly from ssl-config.mozilla.org with modern browsers in mind, so TLSv1.3 support only, it gets you A+ on ssllabs.com/ssltest/, works great with firefox and chrome, haven't tested anything else. 

```
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    return 301 https://$host$request_uri;
}

server {
        listen 443 ssl http2;
        server_name #####;
	access_log /var/log/nginx/#####.access_log;
	error_log /var/log/nginx/#####.error_log;
        ssl_certificate /etc/letsencrypt/live/#####/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/#####/privkey.pem;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;

        ssl_protocols TLSv1.3;
        ssl_prefer_server_ciphers off;

        add_header Strict-Transport-Security max-age=15768000;
        ssl_stapling on;
        ssl_stapling_verify on;
        resolver ##your_prefered_resolver_Ip_here##;

	client_max_body_size 500M;

	proxy_read_timeout 600;
        proxy_connect_timeout 600;
        proxy_send_timeout 600; 

	location / {
		proxy_set_header X-Real-IP         $remote_addr;
		proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_set_header X-Forwarded-Host  $http_host;
		proxy_set_header Host              $http_host;
		proxy_max_temp_file_size           0;
		proxy_pass http://localhost:8080/;
		proxy_redirect                     http:// https://;
	}
}

```

**Comment by immauss** [comment]
Are you using a container for the nginx, or just running it on the host?

**Comment by infestdead** [comment]
Nginx running on the host, proxying to the docker port, I did it this way so I can update the docker image without having to backport anything.
