### ISSUE TITLE
VM server powering down when scheduled scan runs

### ISSUE THREAD

**Issue by dustinbird** [immauss/openvas#252]
I am running gvmd 23.2.0 (full details of versions below) on a hosted OpenSuse Leap 15.4 (patched 12/02/24 and again 15/02/24) I have had a recurring error since Wednesday 14/02/24 when a scheduled scan runs the server turns off.  On Wednesday 1 minutes into a scheduled scan the server powered off, the same on the same daily scan on Thursday, then twice as the same scan was manually triggered, finally once more on a nightly scan.

The scans are the same as have been running unedited for a year now and the docker image is updated each week last updated 12/02/24 and again 15/02/24.  We have three servers running in the similar fashion, but one crashes when the scan runs only recently.

Attached is the container json file and the server log, if you search the server log for "power key" you can see the point of the VM machine turning off as it manually powered down.  Could there be something with the image or the scan?

gvmd=v23.2.0
gvm_libs=v22.8.0
openvas=v22.7.9
openvas_smb=v22.5.6
notus_scanner=v22.6.2
gsa=v23.0.0
gsad=v22.9.0
ospd=v21.4.4
ospd_openvas=v22.6.2
pg_gvm=v22.6.4
python_gvm=v24.1.0
gvm_tools=v24.1.0
greenbone_feed_sync=v23.10.0

[Docker json.log](https://github.com/immauss/openvas/files/14307985/Docker.json.log)
[messages160224.log](https://github.com/immauss/openvas/files/14308001/messages160224.log)

**Comment by immauss** [comment]
This is probably an NVT from the local checks. 

Try this:

- Duplicate the scan config you are using. ( Ex. "Fast and Ultimate" )
- Edit the duplicated config and deselect the "Suse local checks"
- Duplicate the Task for the failing server
- edit the duplicated task and select the new duplicated Scan config. 
- Run the scan and see if it still causes the shutdown. 

If this resolves the problem, then you should bring this up over on the [Greenbone forums.](https://forum.greenbone.net) Unfortunately, there is not currently a way to enable/disable individual local checks. 

-Scott

**Comment by dustinbird** [comment]
I have just had a look at the scan being used and the scans it was running at the time was "Discovery" and in the scan config "Suse local checks" is already disabled.

**Comment by dustinbird** [comment]
I have decided to look into a possible issue with the DB on the server.  I have attached an older working backup as a volume to the server, grabbed the latest docker image and I am running scans now to see if this behaves in a different manner.  I will update this ticket as required.

**Comment by immauss** [comment]
I just re-read your initial post. Which server is shutting down? The target server or the docker host? 

Please let me know how the database switch goes?

-Scott

**Comment by dustinbird** [comment]
It was the docker host that was turning off at the time.  

It seems the rollback to a earlier backup volume of the docker data has now resolved this.  The server has been online since friday with no shutdowns and scans have worked as reuired.

**Comment by immauss** [comment]
Glad to hear you worked it out. And thanks for the follow up. I"m going to go ahead and close this. 

Thanks,
Scott
