### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by rkoosaar** [immauss/openvas#255]
I noticed that when redis starts up (when you start the single container), it gives the following warning.

`93:M 25 Feb 2024 23:25:37.632 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.`

Is this something that should be enabled?

**Comment by immauss** [comment]
Yes.... thought I've never had a problem with not enabling it. 
Since this is a kernel setting, It is something you would need to do on the host machine, it can not be handled via the container.  ( I tried... )

-Scott

**Comment by rkoosaar** [comment]
My problem with redis - during the scans I get this:

 HEALTHECHECK FAILED !
 These services failed:
 redis

and in another log this comes up:
"redis connection error to /run/redis/redis.sock: Connection refused"

And I cant work out yet why that happens.

**Comment by immauss** [comment]
Sorry for the delay ... 
But did you manage to work this out? 

If not, can you please share more details about your setup and how you are starting the container. 

Thanks,
Scott

**Comment by rkoosaar** [comment]
No, I'm still troubleshooting this.

**Comment by immauss** [comment]
Traefik shouldn't even see the redis server .. so 
Hmmm 
Are you using any exotic storage options? 
Is there  anything of value from the logs? 

I've never really had (nor seen anyone else have) problems with redis before. 
Can you please share how you are starting the container? If via docker run, please provide full command. If via docker-compose, please provide the docker-compose.yml.

-Scott

**Comment by immauss** [comment]
Also, even though I don't think it has anything to do with traefik, take a look at this thread too. #184 
There's some good info there on Traefik that I have not had time to incorporate into the docs.

**Comment by rkoosaar** [comment]
I may have fixed the issue. I'll see how it performs over the weekend. I have bunch of scans running then.

**Comment by immauss** [comment]
@rkoosaar That's great. Please let me know how it goes and if you can, how you managed to resolve the problem. 

Thanks,
Scott

**Comment by immauss** [comment]
Any updates @rkoosaar ?

**Comment by rkoosaar** [comment]
I'm not 100% sure it is working yet. I've been away on holiday and the machine thats running the container had some unexpected downtime.
