### ISSUE TITLE
Admin password not set

### ISSUE THREAD

**Issue by LoZio** [immauss/openvas#26]
Using 20.08.04.4.
Started with
`docker run --detach --publish 2939:9392 -e PASSWORD="xHya3Usi" --volume openvas:/data --name openvas immauss/openvas`
after creating the `openvas` volume.
It works but the password for the admin user is not set, it is the standard **admin** one.
Not a big deal since you can change it from the web interface, but maybe there's something wrong with the environment variables.

**Comment by immauss** [comment]
Yes. Sorry.... I should have documented that. This is a side effect of preloading the database. I have an idea of how to fix it but need a little more time to implement it.  Thanks for reminding me.  I'll keep this issue open until I can resolve it.

**Comment by immauss** [comment]
OK There's a new tag in docker now. 20.08.04.5. And that should be the "latest" as soon as docker is done building it. This should resolve the problem. 
Make sure you check out the update in the docs too. 
There are some caveats.

https://github.com/immauss/openvas/docs/

Thanks,
Scottt
