### ISSUE TITLE
Container will not run for longer than 1 minute after updating 25/03/24

### ISSUE THREAD

**Issue by dustinbird** [immauss/openvas#263]
I downloaded the latest Docker image this morning and applied it to our openSUSE 15.5 server but the image fails to start.  When looking at in docker PS then the status is starting for around 60 seconds then it stops and is no longer showing in docker PS.  

I have tried removing this and starting again using system prune and then running but the same issue.  The same also happens if I just try to run the container with the start command after it has stopped.

GVM versions are as follows:

gvmd=v23.5.1
gvm_libs=v22.9.0
openvas=v23.0.1
openvas_smb=v22.5.6
notus_scanner=v22.6.2
gsa=v23.0.0
gsad=v22.9.1
ospd=v21.4.4
ospd_openvas=v22.7.0
pg_gvm=v22.6.5
python_gvm=v24.3.0
gvm_tools=v24.3.0
greenbone_feed_sync=v24.3.0

**To Reproduce**
1. Old container was stopped: **docker stop openvas**
2. Docker containers removed: **docker system prune -a**
3. Docker image run: **docker run --detach --publish 8443:9392 -e PASSWORD="removed" --volume openvas:/data -e HTTPS=true --name openvas immauss/openvas:latest**
4. status of docker checked: **watch docker ps**

**Comment by dustinbird** [comment]
This is still not able to start after rolling back to an old snapshot.  Any thoughts?

**Comment by immauss** [comment]
Dustin,
     This is due to an ongoing issue with Greenbone’s community feeds. For the time, add “-e SKIPSYNC=true” to you start command and it should come up normally. (Without the quotes)

   I’ll make sure the latest is updated more frequently until they get it sorted out, but won’t be able to manage that until later today.


-Scott


G.E. Scott Knauss
***@***.***

**Comment by dustinbird** [comment]
thank you

**Comment by immauss** [comment]
https://github.com/immauss/openvas/discussions/264

And the latest should have today's feeds.

-Scott

**Comment by immauss** [comment]
Looks like the feed sync issues has been resolved, so I'm closing this issue out. 

Thanks,
Scott
