### ISSUE TITLE
email alert is not attaching report PDF

### ISSUE THREAD

**Issue by heinrichat** [immauss/openvas#27]
When mailing the reports in PDF form I get the following error in the report email:

"_This report exceeds the maximum length of 1048576 characters and thus was truncated._" The email has no attachments. This error occurs when scanning /26 IP range. /27 IP ranges work fine.

I've modified your your start start.sh script in line :253 from

`su -c "gvmd --osp-vt-update=/tmp/ospd.sock" gvm`

to

`su -c "gvmd --osp-vt-update=/tmp/ospd.sock --max-email-attachment-size=64000000 --max-email-include-size=64000000 --max-email-message-size=64000000" gvm`

and deleted the old container plus volume and build a new container with `$ docker-compose up -d`

...but it seems that this doesn't work. When scanning the /26 range again the error persists.

**Comment by immauss** [comment]
Try this again … but don’t delete the container. Just make the change, and then run:

Docker restart <container name>

When you delete the container, you deleted your changes. 


A docker restart will keep the changes you made and restart all the container processes. 

Let me know if that worked out. I’ve not done any testing with large attachments before. If that works, I can add it into the base build so it will be there the next time for you. 

-Scott

**Comment by immauss** [comment]
OR ... you could try out this image tag.
immauss/openvas:heinrichat

I'm pushing it now. 

You'll need to use that tag in your docker-compose.yaml

**Comment by immauss** [comment]
Were you able to test this? 
I may have time this weekend to test this if not. please let me know.

**Comment by heinrichat** [comment]
> Were you able to test this?
> I may have time this weekend to test this if not. please let me know.

I will try it Monday (UTC+1)

**Comment by heinrichat** [comment]
Nope. Same Error. I'm positive, that this is not an error with your docker container. It is a greenbone issue, but an unresolved one. I think I should post it in the Greenbone Forum or their repo hoster.
