### ISSUE TITLE
[BUG] Reference closed Bug #270

### ISSUE THREAD

**Issue by dustinbird** [immauss/openvas#271]
After the fixed docker image was uploaded to fix issue #270 last week I have had a similar issue on 2 of my watcher boxes where the scans are taking over 10x the time to run and then failing with "interrupted at 100%".

> Error exit, setting running task to Interrupted.

The configuration of the servers has not changed only the docker image which was updated over the weekend.

**Comment by immauss** [comment]
Hmmm, the image update is not what fixed #270 , it was correcting the feed generation. 

So this could be an issue with updates from GB. I pushed 22.4.45 & latest this morning with more minor updates from GB. Can you first try that. If that does not resolve, please provide full logs from the container. 

Thanks,
Scott

**Comment by dustinbird** [comment]
thank you i will pull this down now and test.

**Comment by dustinbird** [comment]
one of the two servers has now been updated and I am running a scan now to see.

**Comment by dustinbird** [comment]
Looking good so far.  My first test scan has worked since updating th e docker image.  I am awaiting another eon the other server to see if all are working as I would like.

Thank you again for the quick support.

**Comment by dustinbird** [comment]
The updating of the docker image has resolved my issues with the scans.  This incident can now be closed.  Thank you.

**Comment by immauss** [comment]
Good news!!

Thanks @dustinbird
