### ISSUE TITLE
image transfer algorithm

### ISSUE THREAD

**Issue by Funkishtein** [immauss/openvas#278]
image transfer algorithm. I do this: docker save openvas.tar. Then on another machine, I do load -i openvas.tar. then I do docker run --detach --publish 8080:9392 -e PASSWORD=admin --name openvas name of image, but the container is Exited
P.s. Another machine without internet connection.
docker log from Exited container:
starting container at: Tue May 28 10:12:01 UTC 2024
Setting up container filesystem
cp: cannot stat '/usr/local/var/lib/*': No such file or directory
chown: invalid user: ‘gvm:gvm’
cp: cannot stat '/var/lib/gvm/*': No such file or directory
cp: cannot stat '/var/lib/notus/*': No such file or directory
cp: cannot stat '/var/lib/openvas/*': No such file or directory
cp: cannot stat '/etc/gvm/*': No such file or directory
cp: cannot stat '/usr/local/etc/openvas/*': No such file or directory
Choosing container start method from:

Starting gvmd & openvas in a single container !!
Wait for redis socket to be created...
Testing redis status...
Redis ready.
Creating postgresql.conf and pg_hba.conf
Starting PostgreSQL...
waiting for server to start....2024-05-28 10:12:04.916 UTC [107] LOG:  redirecting log output to logging collector process
2024-05-28 10:12:04.916 UTC [107] HINT:  Future log output will appear in directory "/data/var-log/postgresql".
 done
server started
pg exit with 0 .
Checking for existing DB
Loading Default Database
Running first start configuration...
Generating certs...
Using /tmp/tmp.vr7wjiNokF to temporarily store files.
Creating new certificate infrastructure in automatic mode.
Generating private key.
Generated private key in /tmp/tmp.vr7wjiNokF/cakey.pem.
Generating certificate.
  Generating self signed certificate.
Generated self signed certificate in /tmp/tmp.vr7wjiNokF/cacert.pem.
  CA certificate generated.
Installing certificate and key.
Install destinations do not exist as directories, attempting to create them.
Setting up directories
Installed private key to /var/lib/gvm/private/CA/cakey.pem.
Installed certificate to /var/lib/gvm/CA/cacert.pem.
  CA certificate and key installed.
Generating private key.
Generated private key in /tmp/tmp.vr7wjiNokF/serverkey.pem.
Generating certificate.
  Generating certificate request.
Generated certificate request in /tmp/tmp.vr7wjiNokF/serverrequest.pem.
Signing certificate request.
Signed certificate request in /tmp/tmp.vr7wjiNokF/serverrequest.pem with CA certificate in /var/lib/gvm/CA/cacert.pem to generate certificate in /tmp/tmp.vr7wjiNokF/servercert.pem
  Server certificate generated.
Installing certificate and key.
Installed private key to /var/lib/gvm/private/CA/serverkey.pem.
Installed certificate to /var/lib/gvm/CA/servercert.pem.
  Server certificate and key installed.
Generating private key.
Generated private key in /tmp/tmp.vr7wjiNokF/clientkey.pem.
Generating certificate.
  Generating certificate request.
Generated certificate request in /tmp/tmp.vr7wjiNokF/clientrequest.pem.
Signing certificate request.
Signed certificate request in /tmp/tmp.vr7wjiNokF/clientrequest.pem with CA certificate in /var/lib/gvm/CA/cacert.pem to generate certificate in /tmp/tmp.vr7wjiNokF/clientcert.pem
  Client certificate generated.
Installing certificate and key.
Installed private key to /var/lib/gvm/private/CA/clientkey.pem.
Installed certificate to /var/lib/gvm/CA/clientcert.pem.
  Client certificate and key installed.
Removing temporary directory /tmp/tmp.vr7wjiNokF.
NEWDB=false
LOADDEFAULT=true
########################################
Creating a base DB from /usr/lib/base-db.xz
########################################
NOTICE:  relation "vt_severities" already exists, skipping
Unpacking base feeds data from /usr/lib/var-lib.tar.xz
Base DB and feeds collected on:
Sat May 18 02:22:39 UTC 2024
Checking DB Version
Current GVMd database version is  255
Migrate the database if needed.
Updating NVTs and other data
This could take a while if you are not using persistent storage for your NVTs
 or this is the first time pulling to your persistent storage.
 the time will be mostly dependent on your available bandwidth.
Checking age of current data feeds from Greenbone.
ImageFeeds=1715999411
InstalledFeeds=1715998959
Updating local feeds with newer image feeds.
Syncing all feeds from GB
Synchronizing the Notus feed from Immauss Cybersecurity
And all others from the GB Community feed
Running as root. Switching to user 'gvm' and group 'gvm'.
Trying to acquire lock on /var/lib/openvas/feed-update.lock
Acquired lock on /var/lib/openvas/feed-update.lock
⠋ Downloading Notus files from rsync://rsync.immauss.com/feeds/notus/ to 
rsync: getaddrinfo: rsync.immauss.com 873: Temporary failure in name resolution
rsync error: error in socket IO (code 10) at clientserver.c(139) 
[Receiver=3.2.7]

/var/lib/notus⠋ Downloading NASL files from 
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/vt-data/
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in name 
resolution
rsync error: error in socket IO (code 10) at clientserver.c(139) 
[Receiver=3.2.7]

nasl/ to /var/lib/openvas/pluginsReleasing lock on /var/lib/openvas/feed-update.lock
Trying to acquire lock on /var/lib/gvm/feed-update.lock
Acquired lock on /var/lib/gvm/feed-update.lock
⠋ Downloading SCAP data from 
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/scap-dat
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in name 
resolution
rsync error: error in socket IO (code 10) at clientserver.c(139) 
[Receiver=3.2.7]

a/ to /var/lib/gvm/scap-data⠋ Downloading CERT-Bund data from 
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/cert-dat
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in name 
resolution
rsync error: error in socket IO (code 10) at clientserver.c(139) 
[Receiver=3.2.7]

a/ to /var/lib/gvm/cert-data⠋ Downloading gvmd data from 
rsync://feed.community.greenbone.net/community/data-feed/22.04/ to 
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in name 
resolution
rsync error: error in socket IO (code 10) at clientserver.c(139) 
[Receiver=3.2.7]

/var/lib/gvm/data-objects/gvmd/22.04Releasing lock on /var/lib/gvm/feed-update.lock

**Comment by immauss** [comment]
I’m assuming, based on the log and the fact that you exported the image, that you are running this in an isolated environment. no Internet connection? 

That’s why it’s failing. 

Add this to your start command to prevent it from trying to sync the feeds. 

`-e SKIPSYNC=“false”`


Please let me know if that take care of it. 

-Scott

**Comment by Funkishtein** [comment]
Thank you. I add `-e SKIPSYNC=“true” ` in start command. Now running on an isolated network works fine
