### ISSUE TITLE
SSL Support?

### ISSUE THREAD

**Issue by gareth-johnstone** [immauss/openvas#28]
How can we use this with our own SSL certificate? is there an var we can pass into docker with the locations of our certificate files?

**Comment by immauss** [comment]
So there is a better way ....  
I've been working on it, but making it easy to setup ... is hard.  
For now. I've added an option to the latest build for HTTPS.  This will create self-signed certs and start gsad with the https options.  To use your own certs, first start the container with the ``` -e HTTPS=true ``` making sure to create a volume for the data as well. Once that container is up and running, you can copy your certs to replace the ones located in :

/data/var-lib/gvm/CA/ 

You'll need to use 
 ``` docker cp ```  
and possibly 
``` docker exec -it <container-name> bash ```
to get the files into /data/var/lib/gvm/CA  .

(If you aren't familiar with using those, let me know and I'll try to write up more details. )

This will put the certs in the attached volume, so they will remain even if you update the container image. You'll need to restart the container, and from then, as long as you always start with the  ``` -e HTTPS=true ``` option, you should start with your certs. 

Now ... that said, I don't have a set of certs handy I can test this with. So there's a good chance I may have missed something. If this doesn't work, please let me know and I'll do my best to help get it working. 

-Scott

**Comment by immauss** [comment]
OK ... I gave you the wrong location.
It should be:

/data/var-lib/gvm/private/CA

-Scott

**Comment by gareth-johnstone** [comment]
@immauss 
Just to clarify

`/data/var-lib/gvm/private/CA` - Private key Location
`/data/var-lib/gvm/CA` - Certificate Location

Worked a treat - thank you :)
