### ISSUE TITLE
[BUG] - Scanner is only reporting on ICMP timestamp, no other VTs

### ISSUE THREAD

**Issue by nitsewg** [immauss/openvas#280]
** Please attach large files to the report instead of pasting the contents into the report. **

**Describe the bug**
After pulling the latest container (22.4.47-full), the scanner is only reporting on "ICMP Timestamp Reply Information Disclosure".  No other vulnerabilities are being reported.  Prior to updating, we had at least a few SSL findings, among other things.

**To Reproduce**
1. Include how you started the container. 
   `docker run --detach --publish 444:9392 -e PASSWORD="REDACTED" -e HTTPS=true --volume openvas:/data --name openvas immauss/openvas`

2. When did the issue occur? 
Issue occurred after pulling the latest container version

**Expected behavior**
I expected to see the same vulnerabilities present that we had before updating.

**Screenshots**
![image](https://github.com/immauss/openvas/assets/60194541/31cbb1b3-ddf9-43bc-8bf1-577c466dedf2)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Memory available to OS:  16GB
 - Container environment used with version: Docker version 24.0.7, build 24.0.7-0ubuntu2~20.04.1

**logs** ( commands assume the container name is 'openvas' )
Please attach the output from one of the following commands:

# docker #

I have several pages of this in the log file:
```
==> /usr/local/var/log/gvm/ospd-openvas.log <==
OSPD[589] 2024-06-12 03:40:37,742: WARNING: (ospd_openvas.preferencehandler) The VT 1.3.6.1.4.1.25623.1.1.12.2024.6825.1 was not found and it will not be added to the plugin scheduler.
OSPD[589] 2024-06-12 03:40:37,743: WARNING: (ospd_openvas.preferencehandler) The VT 1.3.6.1.4.1.25623.1.1.12.2024.6824.1 was not found and it will not be added to the plugin scheduler.
OSPD[589] 2024-06-12 03:40:37,744: WARNING: (ospd_openvas.preferencehandler) The VT 1.3.6.1.4.1.25623.1.1.12.2024.6823.1 was not found and it will not be added to the plugin scheduler.
```

This was also in the logs:

```
==> /usr/local/var/log/gvm/gvmd.log <==
md manage:   INFO:2024-06-12 14h35.09 UTC:199: Updating placeholder CPEs
md manage:   INFO:2024-06-12 14h35.29 UTC:199: Updating Max CVSS for DFN-CERT
md manage:   INFO:2024-06-12 14h35.42 UTC:199: Updating DFN-CERT CVSS max succeeded.
md manage:   INFO:2024-06-12 14h35.42 UTC:199: Updating Max CVSS for CERT-Bund
md manage:   INFO:2024-06-12 14h35.46 UTC:199: Updating CERT-Bund CVSS max succeeded.
md manage:   INFO:2024-06-12 14h35.47 UTC:199: update_scap_end: Updating SCAP info succeeded
md manage:   INFO:2024-06-12 14h35.52 UTC:957: OSP service has different VT status (version 202406120607) from database (version 202406110605, 140692 VTs). Starting update ...
md manage:   INFO:2024-06-12 14h37.37 utc:957: Updating VTs in database ... 1 new VTs, 32 changed VTs
md manage:WARNING:2024-06-12 14h37.38 utc:957: update_nvts_from_vts: SHA-256 hash of the VTs in the database (cd3da73c23e3a2242c14165cf949a41cf2ae525a13aade08d87f65573e89989c) does not match the one from the scanner (a311dd053da5cde67974aa2bdc002a1173657a2267fc95a62a2d92278d0bf72e).
md   main:MESSAGE:2024-06-12 14h37.38 utc:957: Rebuilding all NVTs because of a hash value mismatch
md   main:MESSAGE:2024-06-12 14h39.28 utc:1065:    Greenbone Vulnerability Manager version 23.6.2 (DB revision 255)
md manage:   INFO:2024-06-12 14h39.28 utc:1065:    Getting scanners.
md   main:MESSAGE:2024-06-12 14h39.38 utc:1074:    Greenbone Vulnerability Manager version 23.6.2 (DB revision 255)
md manage:   INFO:2024-06-12 14h39.38 utc:1074:    Verifying scanner.
```
Any suggestions would be appreciated.  Thanks!

**Comment by immauss** [comment]
Can you please try running with a null volume or no volume and see if you get the same results? I've done quite a bit of testing on the latest image, and it doesn't appear to have any problems. 

-Scott

**Comment by netbix** [comment]
I have upgrade more and same problem !
scanning is very fast and nmap command does not start

**Comment by netbix** [comment]
000.2024.3755 was not found and it will not be added to the plugin scheduler.
openvas  | OSPD[534] 2024-10-16 12:45:10,458: WARNING: (ospd_openvas.preferencehandler) The VT 1.3.6.1.4.1.25623.1.0.305000.2024.3265 was not found and it will not be added to the plugin scheduler.
openvas  | OSPD[534] 2024-10-16 12:45:10,460: WARNING: (ospd_openvas.preferencehandler) The VT 1.3.6.1.4.1.25623.1.0.305000.2024.3346 was not found and it will not be added to the plugin scheduler.
openvas  | OSPD[534] 2024-10-16 12:45:10,470: WARNING: (ospd_openvas.preferencehandler) The VT 1.3.6.1.4.1.25623.1.0.305000.2024.2098 was not found and it will not be added to the plugin scheduler.
openvas  | 
openvas  | ==> /usr/local/var/log/gvm/openvas.log <==
openvas  | sd   main:MESSAGE:2024-10-16 12h45.29 utc:1132:14032d91-ce1f-4eab-8728-32b262d8a514: openvas 23.9.0 started
openvas  | sd   main:MESSAGE:2024-10-16 12h45.29 utc:1132:14032d91-ce1f-4eab-8728-32b262d8a514: attack_network_init: INIT MQTT: SUCCESS
openvas  | sd   main:MESSAGE:2024-10-16 12h45.33 utc:1132:14032d91-ce1f-4eab-8728-32b262d8a514: Vulnerability scan 14032d91-ce1f-4eab-8728-32b262d8a514 started: Target has 1 hosts: 192.168.0.35, with max_hosts = 20 and max_checks = 4
openvas  | libgvm boreas:MESSAGE:2024-10-16 12h45.33 utc:1132:14032d91-ce1f-4eab-8728-32b262d8a514: Alive scan 14032d91-ce1f-4eab-8728-32b262d8a514 started: Target has 1 hosts
openvas  | sd   main:MESSAGE:2024-10-16 12h45.34 utc:1174:14032d91-ce1f-4eab-8728-32b262d8a514: Vulnerability scan 14032d91-ce1f-4eab-8728-32b262d8a514 started for host: 192.168.0.35 (Vhosts: debian10zabbix.fritz.box)
openvas  | :WARNING:2024-10-16 12h45.34 utc:1177:14032d91-ce1f-4eab-8728-32b262d8a514: nasl_pread: Failed to close file descriptor for child process (Operation not permitted)
openvas  | libgvm boreas:MESSAGE:2024-10-16 12h45.36 utc:1132:14032d91-ce1f-4eab-8728-32b262d8a514: Alive scan 14032d91-ce1f-4eab-8728-32b262d8a514 finished in 3 seconds: 1 alive hosts of 1.
Failed to close file descriptor for child process (Operation not permitted)openvas  | sd   main:MESSAGE:2024-10-16 12h46.08 utc:1174:14032d91-ce1f-4eab-8728-32b262d8a514: Vulnerability scan 14032d91-ce1f-4eab-8728-32b262d8a514 finished for host 192.168.0.35 in 34.41 seconds
openvas  | sd   main:MESSAGE:2024-10-16 12h46.08 utc:1132:14032d91-ce1f-4eab-8728-32b262d8a514: Vulnerability scan 14032d91-ce1f-4eab-8728-32b262d8a514 finished in 39 seconds: 1 alive hosts of 1
openvas  | 
openvas  | ==> /usr/local/var/log/gvm/ospd-openvas.log <==
openvas  | OSPD[534] 2024-10-16 12:46:10,340: INFO: (ospd.ospd) 14032d91-ce1f-4eab-8728-32b262d8a514: Host scan finished.
openvas  | OSPD[534] 2024-10-16 12:46:10,343: INFO: (ospd.ospd) 14032d91-ce1f-4eab-8728-32b262d8a514: Scan finished.
openvas  | 
openvas  | ==> /usr/local/var/log/gvm/gvmd.log <==
openvas  | event task:MESSAGE:2024-10-16 12h46.15 utc:855: Status of task Zabbix (38e10cee-628a-4f0b-b734-9169308a43b1) has changed to Processing
openvas  | event task:MESSAGE:2024-10-16 12h46.15 utc:855: Status of task Zabbix (38e10cee-628a-4f0b-b734-9169308a43b1) has changed to Done
openvas  | md   main:MESSAGE:2024-10-16 12h46.16 utc:1429:    Greenbone Vulnerability Manager version 23.10.0 (DB revision 256)
openvas  | md manage:   INFO:2024-10-16 12h46.16 utc:1429:    Getting scanners.
openvas  | md   main:MESSAGE:2024-10-16 12h46.22 utc:1439:    Greenbone Vulnerability Manager version 23.10.0 (DB revision 256)
openvas  | md manage:   INFO:2024-10-16 12h46.22 utc:1439:    Verifying scanner.

**Comment by netbix** [comment]
With this work !

version: "3"
services:
  openvas:
    ports:
      - "8082:9392"
     
    **security_opt:
      - seccomp:unconfined**

    environment:
      - "PASSWORD=admin"
      - "USERNAME=admin"
.....
..
...
