### ISSUE TITLE
Does it really work?

### ISSUE THREAD

**Issue by soyoeml** [immauss/openvas#282]
I used latest version to deploy that docker on a local machine. I also use default docker configuration and doesn't change anything except set admin password. Then I setup a task of port 22 and target to my EC2 instance which has critical openssh CVEs. But after scanned, OpenVas reported zero results of CVEs. The EC2 port 22 is open to all IPs and IPv6. Can I count on immauss/openvas?

**Comment by immauss** [comment]
Yes.
It does work.
![image](https://github.com/immauss/openvas/assets/3965511/02edaee2-86c0-421d-84c8-71306c7c93e7)

That's results from my testing environment. It runs against various containers running different linux distros. 

I'll try to do a little more testing over the next few days (I'm currently on vacation), but as far as I know, everything works fine. 

There are quite a few people, including myself, using it in production environments. 

Tips:

- You will get best results when you have an authenticated scan.  
- Try to ssh from inside the container to the target host and verify the credentials

I'll let you know if I find any problems. 

-Scott

**Comment by immauss** [comment]
I've done some more testing, and there are no issues with running scans. Everything does work. 

Thanks,
Scott
