### ISSUE TITLE
WTF？？？

### ISSUE THREAD

**Issue by ShuBo6** [immauss/openvas#290]
<img width="1452" alt="image" src="https://github.com/user-attachments/assets/6f97859e-12e2-40f9-b927-f286a6296fb8">

<img width="1422" alt="image" src="https://github.com/user-attachments/assets/43292c56-db4b-420f-9d43-9821d1bfd7a5">

**Comment by immauss** [comment]
That’s why odd. 

I didn’t think git would commit files with unresolved merge conflicts. 

But I have not been using that file for the build process now for a while ….

I’ll make sure it is removed before the next commit. 

Thanks,
Scott
