### ISSUE TITLE
Scan interrupted -  failed to connect to /var/run/ospd/ospd-openvas.sock

### ISSUE THREAD

**Issue by McA797** [immauss/openvas#291]
I am experiencing scan interrupted error messages midway through my scans (aprox 300 hosts, 20 concurrently scanned hosts, 4 concurrently executed NVT's).

There seems to be a problem connecting to the ospd-openvas.sock, as I am getting 'osp_scanner_feed_version: failed to connect to /var/run/ospd/ospd-openvas.sock' in my gvmd.log file constantly. 
<img width="910" alt="Screenshot 2024-08-13 at 6 00 02 PM" src="https://github.com/user-attachments/assets/d1ac97e8-d433-47ef-a152-555fd93c14bd">
<img width="610" alt="Screenshot 2024-08-13 at 5 58 18 PM" src="https://github.com/user-attachments/assets/2a55ef81-7af6-468a-b2e6-5757a89849f5">

Around the time this scan failed I got 'redis connection error to /run/redis/redis.sock: Connection refused' in my openvas.log file.
Subsequent manual scans fail instantly, interupted at 0%. 

It is worth noting this is the second time this has happened - I had an all-in-one container v22.4.0 fail in this way, I created a new container with the most recent image and I am getting the same errors. 

Start up command is:
docker run --detach -e PASSWORD="REDACTED" --volume openvasVolume:/data --network host --name openvas immauss/openvas

I have referred to https://github.com/immauss/openvas/issues/269 for guidance, but I seem to be in the same position as the author. 
Any help would be brilliant

**Comment by immauss** [comment]
McA797,
         How much memory have you allocated. This will usually happen when the container runs out of memory. If you have the available memory, try doubling it. If not, try scanning fewer hosts.  If neither of those works, let me know and we'll try to dig deeper. 

-Scott

**Comment by McA797** [comment]
The container was running with 8GB memory, that of the VM. I have allocated the VM an additional 8GB, bringing it up to 16 and I have doubled the CPU count. I will provide an update after the scan runs in the next few days.

Thanks

**Comment by immauss** [comment]
I'm hoping this resolved you issue. If not, please open a new issue.

Thank you,
Scott
