### ISSUE TITLE
[BUG]  OpenVas GSAD restart in loop (docker compose - multi container)

### ISSUE THREAD

**Issue by Izual750** [immauss/openvas#292]
**Describe the bug**
Gvmd conainer restart in loop

**To Reproduce**
1. Contains has been started by using `docker compose up -d`
2. The healtcheck for `ovas_gsad` never manage to be healthy. It always output : `Output": "cat: /usr/local/etc/running-as: No such file or directory\n` visible with `docker inspect ovas_gsad` 

**Expected behavior**
- I think `gvmd` should not restart in loop.

**Environment (please complete the following information):**
 - OS: Debian 12 - Bookworm
 - Memory available to OS:  3.5G 
 - vCPU: 2 @ 2.4GHZ
 - Container environment used with version: `docker 27.1.1,` with `docker compose`

**logs** 
# docker-compose #
docker-compose logs > logfile.log (in attachment, be aware the file i around 10mb of text )
[logfile.log](https://github.com/user-attachments/files/16707500/logfile.log)

**Additional context**
- I already tried once to run `docker compose down -v` in order to remove also the content of the volume. 
- I just upgrade to the version `22.4.48` - Multicontainer, before that i was in `22.4.46`

**Comment by immauss** [comment]
@Izual750 
Careful using the `-v`as it will remove your database. But if that didn't get things running, there could have been an issue with that version. I tested the multi container with the latest, 22.4.49, and it started right up with no issues, so maybe give that a try and please let me know. 

I did a little (very little) testing wtih 22.4.46, and it seems to be a bug there, so please try with the latest. Please let me know if this resolves your issues. 

Thanks,
Scott
