### ISSUE TITLE
 Host details not showing 

### ISSUE THREAD

**Issue by s0vandey** [immauss/openvas#293]
Hi immauss
When scanning any host, details of that host are not displayed. I can ping the host from the server. 

![openvas](https://github.com/user-attachments/assets/1549a5a9-75d3-4e39-98a5-f6ed54c66e8e)

![image](https://github.com/user-attachments/assets/5adecf62-7f19-4f8f-a14c-44ff9447add4)

** Please attach large files to the report instead of pasting the contents into the report. **

**Describe the bug**

**To Reproduce**
1. Include how you started the container. 
   - docker-compose.yml or command used to start the container with all options.
2. When did the issue occur? 
  - the container failed to start? 
  - Container stopped when performing some action? What was the action? 
  - Some other error in the GUI or the logs ? 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.10]
 - Memory available to OS:  [ 4G ]
 - Container environment used with version: [ docker , podman, kubernets, etc ]

**logs** ( commands assume the container name is 'openvas' )
Please attach the output from one of the following commands:

# docker #
docker logs openvas > logfile.log 

# Podman #
podman logs openvas > logfile.log

# docker-compose #
docker-compose logs > logfile.log

Please "attach" the file instead of pasting the conents to the issue. 

**Additional context**

**Comment by immauss** [comment]
You said you can ping the host from the server, can you connect to the host from inside the container? 
```
docker exec -it <container name> bash
```
This will give you shell from inside the container. See if you can ping/ssh to the host you are trying to scan from here. If not, it is likely a docker configuration or firewall issue. 

-Scott
