### ISSUE TITLE
[BUG] Login section dwarfed by splashscreen and advertising

### ISSUE THREAD

**Issue by gooseleggs** [immauss/openvas#299]
**Issue**
Just noticed this on my laptop.  It is set to 1920x1080.
As can be seen, then login section is almost missing.

![image](https://github.com/user-attachments/assets/dcfb507d-e840-4c0d-91b0-955f74af6094)

Any chance you can shrink the banner and advertising a bit and make the login section return to the middle of the screen?

**Comment by immauss** [comment]
It looks WAY better if you have an SSL connection. 
:)

But I'll see what I can do.

**Comment by immauss** [comment]
![image](https://github.com/user-attachments/assets/2068c78b-91d4-474d-843a-5702e1e380cb)

It's in the latest beta:

immauss/openvas:beta


better?

**Comment by immauss** [comment]
And here it is with the now moved and smaller unencrrypted warning:
![image](https://github.com/user-attachments/assets/f9ef4c5e-48e9-4c70-b079-869a09d2a813)
