### ISSUE TITLE
tls listener for gvmd

### ISSUE THREAD

**Issue by hoboristi** [immauss/openvas#30]
Is there any way to configure gvmd with tls? I really need it for my remote operations..

**Comment by immauss** [comment]
Yes. It was added on the most recent update last week. 
You can use the HTTPS environment variable.
-e HTTPS=true
This will use TLS, but with a self signed certificate.
If you want to use your own certs, you'll need to use the -e HTTPS=true and after initially running the container once, replace your certs with the self signed ones. They should be located:

/data/var-lib/gvm/private/CA - Private key Location
/data/var-lib/gvm/CA - Certificate Location

Now.... that said .... I've not done this myself.  I'm actually working on a setting up a reverse nginx proxy to handle the TLS that will be able to use letsencrypt, but that is not quite ready yet.  Please let me know if you have any issues though, and I'll do my best to help.

**Comment by hoboristi** [comment]
thanks, my other concern that gmp is not enabled, if its true, could you please enable it?

**Comment by immauss** [comment]
Done! 
Check the Readme on the front page.

https://github.com/immauss/openva

**Comment by immauss** [comment]
As I've no cause to use gmp in this way (And no good idea on how to test that what I did actually works for what you inteded.)  could you please let me know:
1. Did it work? 
2. Maybe give me an idea what you are doing with it. 


THanks,
Scott

**Comment by hoboristi** [comment]
Hi!
Unfortunately I didnt manage to connect by gvm-cli, my aim is to fetch data from gvm with a python script.

Istvan

**Comment by felimwhiteley** [comment]
In case this is of use this works (usually - not tried the latest versions since DB upgrade)

` sudo docker exec -u gvm -it openvas \
        /usr/local/bin/gvm-pyshell \
            --gmp-username admin --gmp-password admin socket

 sudo docker exec -u gvm -it openvas \
        /usr/local/bin/gvm-script --gmp-username admin --gmp-password admin\
            socket /usr/local/share/scripts/list-tasks.gmp.py`

**Comment by hoboristi** [comment]
Unfortunately my actual setup expects tls or ssh connection only, because of ' docker stack' setup, the python script what I mentioned runs inside in another container, so I'm not sure that the socket way can work :/

**Comment by immauss** [comment]
It "can" work ..... 
I've done some testing with putting the sockets in a share volume, and it does work. I was working with postgres and gmvd in separate containers. I put the socket in a dedicated volume, then mounted that volume to both contianers. It does work, but for what I was trying to do, I just didn't like it. I would rather use TCP, but gvmd doesn't really support that yet.

**Comment by hoboristi** [comment]
my last try, could you please change at start.sh
`GMP="-a 127.0.0.1 -p $GMP"` to `GMP="-a 0.0.0.0 -p $GMP"` ? thanks in advance :)

**Comment by immauss** [comment]
> my last try, could you please change at start.sh
> `GMP="-a 127.0.0.1 -p $GMP"` to `GMP="-a 0.0.0.0 -p $GMP"` ? thanks in advance :)

@hoboristi

Oh ... yeah that makes sense. 

Will do. 

-Scott

**Comment by immauss** [comment]
Done!

**Comment by hoboristi** [comment]
Thanks, finally I started using sockets, and share them with volumes, so we can close that case :)
