### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mnaismith** [immauss/openvas#302]
Hi, 

All my scanners pulled in the latest version of the openvas container today and now all fail to start with the error below.

ERROR:  relation "meta" does not exist
LINE 1: select value from meta where name like 'database_version';
                          ^
Container stopped, performing shutdown
waiting for server to shut down.... done

I can reproduce by running the below.  

docker pull immauss/openvas
docker rm openvas
docker volume rm openvas 
docker volume create openvas 
docker run --detach --publish 127.0.0.1:8080:9392 --publish 127.0.0.1:9390:9390 -e SKIPSYNC=true -e PASSWORD="PASSWORD" --volume openvas:/data --name openvas immauss/openvas

I run this on Intel NUCS.  8GB RAM, M2 SSD. 
[openvascontainerissue.txt](https://github.com/user-attachments/files/17277176/openvascontainerissue.txt)

I have not yet looked into this but thought I'd better raise. 

Cheers

Matt

**Comment by immauss** [comment]
@mnaismith 
Thanks for the heads up. Please pull the new latest and let me know if that resolves the issue. 

Thanks,
Scott

**Comment by mnaismith** [comment]
@immauss 
Yep all good thanks Scott and appreciate the speedy reply. 

Matt

**Comment by immauss** [comment]
@mnaismith Thank you for finding that.

-Scott

**Comment by TotalGriffLock** [comment]
Just ran into this issue having followed the same steps as the OP

**Comment by TotalGriffLock** [comment]
Forcing 24.11.2 seems to work (as _latest_ points to 24.11.1 still)
