### ISSUE TITLE
[BUG] Docker Container Keeps Exiting after intialise Exited (1)

### ISSUE THREAD

**Issue by GAVGARGuardian** [immauss/openvas#303]
### The OpenVAS container fails to start properly due to multiple issues:

Missing Directories and Files: The setup process is unable to locate essential directories and files, leading to errors such as cannot stat and invalid user: 'gvm:gvm'.

PostgreSQL Database Initialization Errors: The database setup attempts to create existing relations, resulting in errors like relation "config_preferences_by_config" already exists. This indicates a failed previous initialization or a corrupted state.

Container Exit: As a result of the above issues, the container exits with status code 1 shortly after attempting to start, preventing OpenVAS from running successfully.

### **To Reproduce**
1. Include how you started the container. 
   - docker-compose.yml or command used to start the container with all options.
2. When did the issue occur? 
  - the container failed to start? 
  - Container stopped when performing some action? What was the action? 
  - Some other error in the GUI or the logs ? 

**Expected behavior**
When starting the OpenVAS container, the following issues occur:

Database Connection Failure: The error sql_open: PQconnectStart to 'gvmd' failed: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory indicates that the PostgreSQL server is not running or accessible, preventing the OpenVAS service from connecting to the database.

Service Initialization Issues: The process fails to migrate the database due to the missing PostgreSQL server, leading to the termination of the OpenVAS services.

PostgreSQL Not Running: Despite attempts to start the PostgreSQL server, errors related to existing database relations (e.g., ERROR: relation "config_preferences_by_config" already exists) suggest that the initialization is encountering conflicts with the existing database schema, which leads to unexpected behavior.

Container Exit: The OpenVAS container exits with a status of Exited (1) due to the failure in starting the necessary services, preventing any further interactions or functionalities from being available.

_____________________________________________________________________________

**Screenshots**

![image](https://github.com/user-attachments/assets/9b4fdd4b-e9a1-4f86-919e-ee7eff243757)

![image](https://github.com/user-attachments/assets/0aa5a7a7-3c66-45c6-9d1e-b7cd16f89ab1)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - Memory available to OS:  [ 16GB ]
 - 
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O         PIDS
d151bf5e73ac   openvas   1.72%     375.2MiB / 13.27GiB   2.76%     2.7MB / 1.55MB   28.1MB / 57.4MB   21

 - Container environment used with version:Docker version 24.0.5, build ced0996

**Additional context**
[Troubleshooting with Chatgpt and Previous Bugs.txt](https://github.com/user-attachments/files/17355727/Troubleshooting.with.Chatgpt.and.Previous.Bugs.txt)

**Comment by GAVGARGuardian** [comment]
I have tried adding SKIPSYNC=true and -e NEWDB, the container still fails to start.

I tried referencing error #283 and have not been able to get it up. 

I have tested on the following OS: Ubuntu Desktop 22.04, Ubuntu Server 20.04 and 22.04, ParrotOS 
I am still getting the exited (1)


[BUG] Container exits when starting #283

Additonal Logs:

[openvas.logs.txt](https://github.com/user-attachments/files/17355759/openvas.logs.txt)

**Comment by GAVGARGuardian** [comment]
After a few restarts it was still failing on the  mmauss/openvas:latest  I tried pulling immauss/openvas:22.4.49 and failed at first. After 2 restarts it came right.

==> /usr/local/var/log/gvm/ospd-openvas.log <==
OSPD[885] 2024-10-13 13:30:18,864: INFO: (ospd.main) Starting OSPd OpenVAS version 22.7.1.
OSPD[885] 2024-10-13 13:30:19,161: INFO: (ospd_openvas.messaging.mqtt) Successfully connected to MQTT broker

==> /usr/local/var/log/gvm/redis-server.log <==
96:C 13 Oct 2024 12:32:45.135 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
96:C 13 Oct 2024 12:32:45.136 # Redis version=7.0.15, bits=64, commit=00000000, modified=0, pid=96, just started
96:C 13 Oct 2024 12:32:45.136 # Configuration loaded
96:M 13 Oct 2024 12:32:45.140 # Server initialized
96:M 13 Oct 2024 12:32:45.140 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
13:C 13 Oct 2024 13:08:11.604 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
13:C 13 Oct 2024 13:08:11.645 # Redis version=7.0.15, bits=64, commit=00000000, modified=0, pid=13, just started
13:C 13 Oct 2024 13:08:11.645 # Configuration loaded
13:M 13 Oct 2024 13:08:11.648 # Server initialized
13:M 13 Oct 2024 13:08:11.648 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

==> /usr/local/var/log/gvm/ospd-openvas.log <==
OSPD[885] 2024-10-13 13:30:29,160: INFO: (ospd_openvas.daemon) Loading VTs. Scans will be [requested|queued] until VTs are loaded. This may take a few minutes, please wait...
OSPD[885] 2024-10-13 13:30:29,838: INFO: (ospd_openvas.notus) hashsum verification is disabled

==> /usr/local/var/log/gvm/gvmd.log <==
md   main:MESSAGE:2024-10-13 13h32.06 utc:950:    Greenbone Vulnerability Manager version 23.8.1 (DB revision 256)
md manage:   INFO:2024-10-13 13h32.06 utc:950:    Getting scanners.
md   main:MESSAGE:2024-10-13 13h32.30 utc:957:    Greenbone Vulnerability Manager version 23.8.1 (DB revision 256)
md manage:   INFO:2024-10-13 13h32.30 utc:957:    Verifying scanner.

==> /usr/local/var/log/gvm/healthchecks.log <==
 Healthchecks completed with no issues.

==> /usr/local/var/log/gvm/gvmd.log <==
md   main:MESSAGE:2024-10-13 13h37.54 utc:1024:    Greenbone Vulnerability Manager version 23.8.1 (DB revision 256)
md manage:   INFO:2024-10-13 13h37.54 utc:1024:    Getting scanners.
md   main:MESSAGE:2024-10-13 13h38.32 utc:1031:    Greenbone Vulnerability Manager version 23.8.1 (DB revision 256)
md manage:   INFO:2024-10-13 13h38.32 utc:1031:    Verifying scanner.

**Comment by immauss** [comment]
Can you please provide the exact command you used to start the container? 

Also, please make sure you have pulled  "latest" in the last 6 days, the most recent is actually 22.4.51. There were a number of bugs resolved that caused this sort of problem in that version. 

Thank you,
Scott

**Comment by GAVGARGuardian** [comment]
Yes I pulled the latest this morning. Still the same thing. Only on the 22.4.49 did it stay stable and I was able to access the web interface:


The various commands I have tried to get the Container to start:
docker run -d -p 9392:9392 --name openvas01 immauss/openvas
docker run -d -p 9392:9392 --name openvas01 immauss/openvas:latest
docker run -d -p 443:9392 --name openvas01 immauss/openvas
docker run -d -p 9392:9392 -e SKIP_SYNC=true -e SKIP_NEW_DB=true immauss/openvas

**Comment by immauss** [comment]
OK ... You've done a lot, and I appreciate that. 
But there's something confusing ...
You say you pulled the latest today, but the log file you sent is not from a run with the latest image. The DB loads differently in the latest image. 

Please make sure you have removed the existing container, try the basic start with 22.4.51 and send me the log file, and I'll see if I can figure out what is going on. 

FWIW, I just ran a basic start ``` docker run -d --name openvas immauss/openvas:22.4.51 ```

And it started fine. I'll spin up my VMs of Ubuntu, and see if those are having issues, but that rarely makes a difference.

**Comment by GAVGARGuardian** [comment]
So I did try that command:
docker run -d --name openvas immauss/openvas:22.4.51
The immauss/openvas:22.4.49 docker container remained up and is still accessible at the moment.
It was up for about an hour and then exited with the below:

starting container at: Sun Oct 13 17:59:55 UTC 2024
Setting up container filesystem
Creating needed Directories
Validating other directories
Create gvm user
Setting up soft links
Database
/usr/local/var/lib
/usr/local/var/log
/var/log
Setting up logs
Fixing local/share
Fixing run
Fixing /var/lib/gvm
Fixing /var/lib/notus
Fixing /var/lib/openvas
Handling config files
cp: cannot stat '/etc/gvm/*': No such file or directory
cp: cannot stat '/usr/local/etc/openvas/*': No such file or directory
Fixing some permissions
All done ... mark the container as setup and ready
Choosing container start method from:

Starting gvmd & openvas in a single container !!
Wait for redis socket to be created...
Testing redis status...
Redis ready.
Creating postgresql.conf and pg_hba.conf
Starting PostgreSQL...
waiting for server to start......2024-10-13 18:23:59.324 UTC [199] LOG:  redirecting log output to logging collector process
2024-10-13 18:23:59.324 UTC [199] HINT:  Future log output will appear in directory "/data/var-log/postgresql".
...... done
server started
pg exit with 0 .
Checking for existing DB
Loading Default Database
Running first start configuration...
Generating certs...
Using /tmp/tmp.knym3qGo6J to temporarily store files.
Creating new certificate infrastructure in automatic mode.
Generating private key.
Generated private key in /tmp/tmp.knym3qGo6J/cakey.pem.
Generating certificate.
  Generating self signed certificate.
Generated self signed certificate in /tmp/tmp.knym3qGo6J/cacert.pem.
  CA certificate generated.
Installing certificate and key.
Install destinations do not exist as directories, attempting to create them.
Setting up directories
Installed private key to /var/lib/gvm/private/CA/cakey.pem.
Installed certificate to /var/lib/gvm/CA/cacert.pem.
  CA certificate and key installed.
Generating private key.
Generated private key in /tmp/tmp.knym3qGo6J/serverkey.pem.
Generating certificate.
  Generating certificate request.
Generated certificate request in /tmp/tmp.knym3qGo6J/serverrequest.pem.
Signing certificate request.
Signed certificate request in /tmp/tmp.knym3qGo6J/serverrequest.pem with CA certificate in /var/lib/gvm/CA/cacert.pem to generate certificate in /tmp/tmp.knym3qGo6J/servercert.pem
  Server certificate generated.
Installing certificate and key.
Installed private key to /var/lib/gvm/private/CA/serverkey.pem.
Installed certificate to /var/lib/gvm/CA/servercert.pem.
  Server certificate and key installed.
Generating private key.
Generated private key in /tmp/tmp.knym3qGo6J/clientkey.pem.
Generating certificate.
  Generating certificate request.
Generated certificate request in /tmp/tmp.knym3qGo6J/clientrequest.pem.
Signing certificate request.
Signed certificate request in /tmp/tmp.knym3qGo6J/clientrequest.pem with CA certificate in /var/lib/gvm/CA/cacert.pem to generate certificate in /tmp/tmp.knym3qGo6J/clientcert.pem
  Client certificate generated.
Installing certificate and key.
Installed private key to /var/lib/gvm/private/CA/clientkey.pem.
Installed certificate to /var/lib/gvm/CA/clientcert.pem.
  Client certificate and key installed.
Removing temporary directory /tmp/tmp.knym3qGo6J.
NEWDB=false
LOADDEFAULT=true
########################################
Creating a base DB from /usr/lib/base-db.xz
########################################
Restoring Globals.
ERROR:  role "postgres" already exists
Creating gvmd Database.
Restoring gvmd database.
Unpacking base feeds data from /usr/lib/var-lib.tar.xz
Base DB and feeds collected on:
Thu Oct  3 02:31:54 UTC 2024
Checking DB Version
Current GVMd database version is  256
Migrate the database if needed.
Updating NVTs and other data
This could take a while if you are not using persistent storage for your NVTs
 or this is the first time pulling to your persistent storage.
 the time will be mostly dependent on your available bandwidth.
Checking age of current data feeds from Greenbone.
ImageFeeds=1727923194
InstalledFeeds=1727922714
Updating local feeds with newer image feeds.
Syncing all feeds from GB
Synchronizing the Notus feed from Immauss Cybersecurity
And all others from the GB Community feed
Running as root. Switching to user 'gvm' and group 'gvm'.
Trying to acquire lock on /var/lib/openvas/feed-update.lock
Acquired lock on /var/lib/openvas/feed-update.lock
⠋ Downloading Notus files from rsync://rsync.immauss.com/feeds/notus/ to
/var/lib/notus⠋ Downloading NASL files from
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/vt-data/
nasl/ to /var/lib/openvas/pluginsReleasing lock on /var/lib/openvas/feed-update.lock
Trying to acquire lock on /var/lib/gvm/feed-update.lock
Acquired lock on /var/lib/gvm/feed-update.lock
⠋ Downloading SCAP data from
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/scap-dat
 io timeout after 10 seconds -- exiting
rsync error: timeout in data send/receive (code 30) at io.c(200)
rsync error: received SIGUSR1 (code 19) at main.c(1613)

a/ to /var/lib/gvm/scap-data⠋ Downloading CERT-Bund data from
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/cert-dat
rsync:  read error: Connection reset by peer (104)
rsync error: error in socket IO (code 10) at io.c(806)
rsync: connection unexpectedly closed (726 bytes received so far)
rsync error: error in rsync protocol data stream (code 12) at io.c(231)

a/ to /var/lib/gvm/cert-data⠋ Downloading gvmd data from
rsync://feed.community.greenbone.net/community/data-feed/22.04/ to
/var/lib/gvm/data-objects/gvmd/22.04Releasing lock on /var/lib/gvm/feed-update.lock
Container stopped, performing shutdown
waiting for server to shut down................................ done
server stopped

**Comment by GAVGARGuardian** [comment]
Both Versions started fine this morning but now exited at 11:02am.

I have tried restarting but they exit. Please see logs below:

cc05b6ef87a1   immauss/openvas:22.4.51   "/scripts/start.sh"   15 hours ago   Up 9 minutes (health: starting)   0.0.0.0:8080->9392/tcp, :::8080->9392/tcp   openvas03
d151bf5e73ac   immauss/openvas:22.4.49   "/scripts/start.sh"   20 hours ago   Up 9 minutes (health: starting)   0.0.0.0:80->9392/tcp, :::80->9392/tcp       openvas

Version:22.4.49
[logs14102024.txt](https://github.com/user-attachments/files/17361540/logs14102024.txt)

Version:22.4.51:
[logs-version22.4.51.txt](https://github.com/user-attachments/files/17361546/logs-version22.4.51.txt)

**Comment by GAVGARGuardian** [comment]
cc05b6ef87a1 immauss/openvas:22.4.51 "/scripts/start.sh" 15 hours ago Up 15 minutes (health: unhealthy) 0.0.0.0:8080->9392/tcp, :::8080->9392/tcp openvas03

I got an unhealthy but they have been staying up for a while but go into a unhealthy state.

I tried the following commands:
pkill gvmd
gvmd
pkill gsad
gsad
pkill openvas
openvas -u

root@cc05b6ef87a1:/# tail -f /var/log/gvm/gvmd.log
md   main:MESSAGE:2024-10-14 11h11.50 utc:8778:    Greenbone Vulnerability Manager version 23.10.0 (DB revision 256)
md manage:   INFO:2024-10-14 11h11.50 utc:8778:    Verifying scanner.
md   main:MESSAGE:2024-10-14 19h09.08 utc:71:    Greenbone Vulnerability Manager version 23.10.0 (DB revision 256)
md   main:   INFO:2024-10-14 19h09.09 utc:71:    Migrating database.
md   main:   INFO:2024-10-14 19h09.09 utc:71: gvmd: databases are already at the supported version
md   main:WARNING:2024-10-14 19h34.38 utc:307: init_semaphore_set: error getting semaphore set: Permission denied
md   main:MESSAGE:2024-10-14 19h34.38 utc:307:    Greenbone Vulnerability Manager version 23.10.0 (DB revision 256)
md manage:WARNING:2024-10-14 19h34.39 utc:308: sql_open: PQconnectPoll failed
md manage:WARNING:2024-10-14 19h34.39 utc:308: sql_open: PQerrorMessage (conn): connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "root" does not exist
md manage:WARNING:2024-10-14 19h34.39 utc:308: init_manage_open_db: sql_open failed
^C


root@cc05b6ef87a1:/# tail -f /var/log/gvm/gsad.log
gsad main:MESSAGE:2024-10-14 09h01.17 utc:880: Starting GSAD version 22.12.0
gsad  gmp:MESSAGE:2024-10-14 09h04.45 utc:881: Authentication success for 'admin' from 10.200.200.199
gsad  gmp:MESSAGE:2024-10-14 09h30.14 GMT:881: Authentication success for 'admin' from 10.200.200.199
gsad  gmp:MESSAGE:2024-10-14 09h30.14 UTC:881: Authentication success for 'admin' from 10.200.200.199
gsad  gmp:MESSAGE:2024-10-14 09h30.20 GMT:881: Authentication success for 'admin' from 10.200.200.199
gsad  gmp:MESSAGE:2024-10-14 09h53.28 GMT:881: Authentication success for 'admin' from 10.200.200.199
gsad  gmp:WARNING:2024-10-14 10h56.56 GMT:881: Authentication failure for 'admin' from 10.200.200.199. Status was 2.
gsad  gmp:MESSAGE:2024-10-14 10h57.00 GMT:881: Authentication success for 'admin' from 10.200.200.199
gsad main:MESSAGE:2024-10-14 19h35.20 utc:313: Starting GSAD version 22.12.0

After running these I get:
greenbone-nvt-sync
greenbone-certdata-sync
greenbone-scapdata-sync

quire lock on /var/lib/openvas/feed-update.lock
/var/lib/openvas/feed-update.lock is locked by another process. Waiting 5 seconds before next try.
Trying to acquire lock on /var/lib/openvas/feed-update.lock
/var/lib/openvas/feed-update.lock is locked by another process. Waiting 5 seconds before next try.
Trying to acquire lock on /var/lib/openvas/feed-update.lock
/var/lib/openvas/feed-update.lock is locked by another process. Waiting 5 seconds before next try.
Trying to acquire lock on /var/lib/openvas/feed-update.lock
/var/lib/openvas/feed-update.lock is locked by another process. Waiting 5 seconds before next try.
Trying to acquire lock on /var/lib/openvas/feed-update.lock
/var/lib/openvas/feed-update.lock is locked by another process. Waiting 5 seconds before next try.
Trying to acquire lock on /var/lib/openvas/feed-update.lock
/var/lib/openvas/feed-update.lock is locked by another process. Waiting 5 seconds before next try.
Trying to acquire lock on /var/lib/openvas/feed-update.lock
/var/lib/openvas/feed-update.lock is locked by another process. Waiting 5 seconds before next try.
Trying to acquire lock on /var/lib/openvas/feed-update.lock
/var/lib/openvas/feed-update.lock is locked by another process. Waiting 5 seconds before next try.
Trying to acquire lock on /var/lib/openvas/feed-update.lock
/var/lib/openvas/feed-update.lock is locked by another process. Waiting 5 seconds before next try.
^CRunning as root. Switching to user 'gvm' and group 'gvm'.

**Comment by immauss** [comment]
In general ... if a process dies in a container, it's best to just restart the container. Killing and restarting in the container is more likely to cause new issues than resolve them. 


At least one of the logs you provided included the following:

```
rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/cert-dat
rsync: read error: Connection reset by peer (104)
rsync error: error in socket IO (code 10) at io.c(806)
rsync: connection unexpectedly closed (726 bytes received so far)
rsync error: error in rsync protocol data stream (code 12) at io.c(231)
```
This is indicative or either a problem with the greenbone feed sync servers (which does happen from time to time) or a connectivity problem with your host.  

This error:
```
Trying to acquire lock on /var/lib/openvas/feed-update.lock
/var/lib/openvas/feed-update.lock is locked by another process. Waiting 5 seconds before next try.
Trying to acquire lock on /var/lib/openvas/feed-update.lock
/var/lib/openvas/feed-update.lock is locked by another process. Waiting 5 seconds before next try.
```

is most likely due to killing processes in the contianer. 

It is still not clear to me what is causing the container to crash. If you could, please do the following:

Remove all currently running instances of the immauss/openvas container. 

start the container with the following:
```
docker run -d -p 9392:9392 -e SKIPSYNC=true --name openvas immauss/openvas:22.4.52 
```
( note 22.4.52 is changed from 22.4.51 in only that it logs the version number of the container in the docker logs.) 

monitor the logs with 
```
docker logs -f openvas
```

Once the container has completed it's startup, noted by repeated entries similar to:
```
==> /usr/local/var/log/gvm/healthchecks.log <==
 Healthchecks completed with no issues.

==> /usr/local/var/log/gvm/gvmd.log <==
md   main:MESSAGE:2024-10-15 07h59.36 utc:63206:    Greenbone Vulnerability Manager version 23.10.0 (DB revision 256)
md manage:   INFO:2024-10-15 07h59.36 utc:63206:    Getting scanners.
md   main:MESSAGE:2024-10-15 07h59.44 utc:63215:    Greenbone Vulnerability Manager version 23.10.0 (DB revision 256)
md manage:   INFO:2024-10-15 07h59.44 utc:63215:    Verifying scanner.
```


Attempt to login to the GSA interface with a web browsers:

http://<ip of host running docker>:9392
username: admin
password: admin

If any of this fails, please provide the output of the following:
```
docker  exec -it openvas bash -c "cat /var/log/gvm/*; cat /var/log/postgresql/*"  
```
You will need to restart the container if it crashes to run the previous command.

Thanks,
Scott

**Comment by GAVGARGuardian** [comment]
Looking this morning it has remained healthy. It looks like the 22.4.52 has been stable
  17 hours (healthy)   0.0.0.0:9392->9392/tcp, :::9392->9392/tcp   openvas
