### ISSUE TITLE
Feed sync issues with new install on Kali

### ISSUE THREAD

**Issue by immauss** [immauss/openvas#306]
Hi I’m new to the openvas and  I want to fully  understand a few things 
I downloaded open as in Kali and with a successful installation but I’m having issues it says ”no scap database found” in the log I have updated it so many times with some successful and others not but it still persists 
 I successfully got the scan config options in the web but when I scan it queues and still no scab data in CVE and other options 
How do I solve the issue ?

_Originally posted by @Mxlkommarz in https://github.com/immauss/openvas/discussions/264#discussioncomment-11050688_

**Comment by immauss** [comment]
@Mxlkommarz
Welcome. 
I must first ask though, are you using docker for you Openvas setup on Kali, or are you using the installation from Kali? 

Thanks,
Scott

**Comment by Mxlkommarz** [comment]
Hello 
Thanks do the fast response I am using the installation from kali but I just found out about the dicker installation I would appreciate your guidance on this

**Comment by immauss** [comment]
Well ... Start here:

[https://immauss.github.io/openvas/](https://immauss.github.io/openvas/)

If you run into any issues there, let me know. 

-Scott

**Comment by Mxlkommarz** [comment]
Okay so I just installed it but not all pull was successful for some reason but it has been created  how do I use it ?

**Comment by immauss** [comment]
I'm not sure what you mean. 
Can you send some screen shots or logs? 

-Scott
