### ISSUE TITLE
[BUG] Docker container exited right after start sql_exec_internal failed

### ISSUE THREAD

**Issue by bsusta** [immauss/openvas#309]
**Describe the bug**
Docker container exited right after start.

**docker logs openvas**

Migrate the database if needed.

(gvmd:234): md manage-WARNING **: 14:08:52.074: sql_exec_internal: PQexec failed: ERROR:  role "dba" does not exist
 (7)

(gvmd:234): md manage-WARNING **: 14:08:52.074: sql_exec_internal: SQL: SET ROLE "dba";

(gvmd:234): md manage-WARNING **: 14:08:52.074: sqlv: sql_exec_internal failed
Container stopped, performing shutdown
waiting for server to shut down.... done
server stopped

**To Reproduce**
docker run --detach --publish 8080:9392 -e PASSWORD="Your admin password here" --name openvas immauss/openvas
docker restart openvas

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04.1 LST, Latest Kali Linux
 - Memory available to OS:   8G 
 - Container environment used with version:  Docker version 24.0.7, build 24.0.7-0ubuntu4.1

**Comment by immauss** [comment]
Please see here:

https://github.com/immauss/openvas/discussions/311


Thanks,
Scott
