### ISSUE TITLE
Error on container start: gpg: can't open '/etc/GBCommunitySigningKey.asc': No such file or directory

### ISSUE THREAD

**Issue by kimberlymcm** [immauss/openvas#310]
I'm trying to run this and I'm getting the below error on finding the GBCommunitySigningKey. How do I fix this?

I am just running
`docker volume create openvas10`
And then the error is in the container start-up from the below command
`docker run --detach --publish 8080:9392 -e PASSWORD="<MY PASSWORD>" --volume openvas10:/data --name openvas10 immauss/openvas`

End of error logs:
/var/lib/gvm/data-objects/gvmd/22.04Releasing lock on /var/lib/gvm/feed-update.lock
Starting Greenbone Vulnerability Manager...
Waiting for gvmd
Waiting for gvmd
Waiting for gvmd
Waiting for gvmd
Waiting for gvmd
Waiting for gvmd
Waiting for gvmd
Waiting for gvmd
Waiting for gvmd
Waiting for gvmd
admin
Time to fixup the gvm accounts.
Setting admin password
reset 
 set Report Lines to 1000
Starting Postfix for report delivery by email
.
Sleeping for mosquitto
 Get the Greenbone public Key
Setup environment
Import the key 
gpg: can't open '/etc/GBCommunitySigningKey.asc': No such file or directory
gpg: Total number processed: 0
Container stopped, performing shutdown
waiting for server to shut down.... done
server stopped

**Comment by immauss** [comment]
Please see here:

https://github.com/immauss/openvas/discussions/311


Thanks,
Scott

**Comment by kimberlymcm** [comment]
Thank you - working now!
