### ISSUE TITLE
New Build of server and Docker on OpenSuse 15.6 container will not start

### ISSUE THREAD

**Issue by dustinbird** [immauss/openvas#312]
**Describe the bug**
I have built three new OpenSUE Leap servers using 15.6 and used zypper to update them.  Docker is installed and running and when I run a test docker image (hello world) the docker container works.  When trying to run openvas on each server the container starts then stops in less than ten seconds.

**To Reproduce**
1.    The container was started using Docker run as follows:  docker run --detach --publish 8443:9392 -e PASSWORD="REDACTED" --volume openvas:/data -e HTTPS=true --name openvas immauss/openvas:latest
2. 
3. When did the issue occur? 
  -
  - Container stopped when performing some action? What was the action?  - seems to be when cleaning up shim
  - Some other error in the GUI or the logs  - I cannot access the docker logs as the container does not stay up long enough but the server logs say the following:

2024-11-25T10:47:12.018355+00:00 localhost systemd[1]: docker-bc12176d88a1c541e5a47a258983dac9ca2e0e98bcdfbf4b93c59ded6d9e80b5.scope: Deactivated successfully.
2024-11-25T10:47:12.033769+00:00 localhost systemd[1]: docker-bc12176d88a1c541e5a47a258983dac9ca2e0e98bcdfbf4b93c59ded6d9e80b5.scope: Consumed 1.214s CPU time.
2024-11-25T10:47:12.044140+00:00 localhost dockerd[1550]: time="2024-11-25T10:47:12.043441845Z" level=warning msg="cleaning up after shim disconnected" id=bc12176d88a1c541e5a47a258983dac9ca2e0e98bcdfbf4b93c59ded6d9e80b5 namespace=moby

**Expected behavior**
Container to start and enter a state of "Healthy" as per the other 3 machines running this in the same manner.

**Environment (please complete the following information):**
 - OS: OpenSuse Leap 15.6
 - Memory available to OS:  8G 
 - Container environment used with version: Docker

**logs** ( commands assume the container name is 'openvas' )
Please attach the output from one of the following commands:

# docker #
docker logs openvas > logfile.log 
- ERROR:  relation "meta" does not exist
LINE 1: select value from meta where name like 'database_version';

[Docker log.txt](https://github.com/user-attachments/files/17901919/Docker.log.txt)

**Comment by immauss** [comment]
Question 
this is not the first time this image has started. Can you describe anything before this ? 

Thanks,
Scott

**Comment by dustinbird** [comment]
This is not the first attempt to start the image that is correct, however the image has not started correctly one single attempt across the three boxes I have this installed on.  As these were fresh builds I was not aware where the start up error may have been (in my server build, docker or elsewhere, so I was less worried about the failure and didnt log the error.  However this is the most recent case.

Shall I try this across the other two servers to see if I get different results or logs for you?

**Comment by dustinbird** [comment]
how can I obtain those?  Is it a case of system prune -a then run again or will this be further back in the existing logs I have access to?

**Comment by immauss** [comment]
It should show with just ``` docker logs ```
But you would need to start with a new clean volume. 
Just pull the logs right after the first start failure. 

-Scott

**Comment by dustinbird** [comment]
sorry for so many questions  Will a new volume be created from a system prune -a or do I need to remove docker and start again?

**Comment by immauss** [comment]
Easiest way is to just change the name of the volume in your start command. Docker will create a new one. 


```
docker run --detach --publish 8443:9392 -e PASSWORD="REDACTED" --volume openvas-new:/data -e HTTPS=true --name openvas immauss/openvas:latest
```

**Comment by dustinbird** [comment]
Seems to be running ok now with a new volume.  It has got past the first minute of start-up.  Could it be caused by the fact when I started it the first time I had an incorrect password in the docker run command?

**Comment by dustinbird** [comment]
Thank you now working on all three boxes.  I have used a new volume name and deleted the old volume from the system

**Comment by immauss** [comment]
That fixed it? 

-Scott

**Comment by dustinbird** [comment]
yes I am logged into the web ui now with no issues.  This can be closed and I think it was just the incorrect password used once

**Comment by immauss** [comment]
Thanks !
