### ISSUE TITLE
[BUG] GSAD could not be started with the latest Image

### ISSUE THREAD

**Issue by righter83** [immauss/openvas#317]
**Describe the bug**
The Container starts but I'm not able to access the WebUI

**To Reproduce**
1. Include how you started the container. 
   - docker start openvas
2. When did the issue occur? 
- after fetching the latest image it will not start all subprocesses correctly

**Environment (please complete the following information):**
 - OS: Debian 12.8
 - Memory available to OS:  64GB
 - Container environment used with version: docker

** Full Logs **
[openvas-logfile.log](https://github.com/user-attachments/files/18148934/openvas-logfile.log)

** Effective Problem in Logs **
This seems to be the problem:
`Starting Open Scanner Protocol daemon for OpenVAS...
Traceback (most recent call last):
  File "/usr/local/bin/notus-scanner", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/notus/scanner/daemon.py", line 134, in main
    run_daemon(
  File "/usr/local/lib/python3.11/dist-packages/notus/scanner/daemon.py", line 80, in run_daemon
    verifier = hashsum_verificator(
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/notus/scanner/daemon.py", line 58, in hashsum_verificator
    sums = reload_sha256sums(sha_sum_reload_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/notus/scanner/loader/gpg_sha_verifier.py", line 62, in reload_sha256sums
    config.gpg = __default_gpg_home()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/notus/scanner/loader/gpg_sha_verifier.py", line 41, in __default_gpg_home
    return GPG(gnupghome=f"{home.absolute()}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gnupg.py", line 1119, in __init__
    raise ValueError('gnupghome should be a directory (it isn\'t): %s' % gnupghome)
ValueError: gnupghome should be a directory (it isn't): /etc/openvas-gnupg
Exception ignored in atexit callback: <function exit_cleanup at 0x7fa8f8850180>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/notus/scanner/utils.py", line 101, in exit_cleanup
    sys.exit()
SystemExit: 
Skipping GSAD start because SKIPGSAD=false
`

**Comment by dustinbird** [comment]
I have the same issue on 2 boxes here.  The status of the docker image on both says running (unhealthy).  Same end result webUI not working.

**Comment by immauss** [comment]
Ugh .... 
Missing a "$" in an if statement.  (I'm blaming a bad copy-paste maneuver.... ) 

I'm rebuilding now. Should be an updated image shortly. 

applogies. 

-Scott

**Comment by immauss** [comment]
OK ..

New tag: 24.12.03 and updated latest to 24.12.03. 

Thanks @righter83

**Comment by righter83** [comment]
Great, thanks for that blazing fast fix! 
It is working now

**Comment by dustinbird** [comment]
Do we have the same issue again?  I am trying to download a new image to a server today and I have the same unhealthy container.

**Comment by immauss** [comment]
So I tested and if you are seeing similar issue, then it's a new problem. The image has not change and the fix for this is still in latest. 
Please open a new issue and include all the normal info. 

Thanks,
-Scott
