### ISSUE TITLE
Container doesn't start 

### ISSUE THREAD

**Issue by radiusmk** [immauss/openvas#32]
I tried to run the "docker run" command shown in the documentation, but the container did not start with the following errors: 

`
# docker run  --publish 8080:9392 -e PASSWORD="adminXXX" --name openvas immauss/openvas
Unable to find image 'immauss/openvas:latest' locally
Trying to pull repository registry.access.redhat.com/immauss/openvas ...
Pulling repository registry.access.redhat.com/immauss/openvas
Trying to pull repository registry.redhat.io/immauss/openvas ...
Trying to pull repository docker.io/immauss/openvas ...
latest: Pulling from docker.io/immauss/openvas
83ee3a23efb7: Pull complete
db98fc6f11f0: Pull complete
f611acd52c6c: Pull complete
dc16d3b591b7: Pull complete
ec379549505f: Pull complete
047a862b2705: Pull complete
60960b44262f: Pull complete
f12e12d18794: Pull complete
Digest: sha256:f57903eb437a45fdbfb9b9646a2d0235196cf10d9e0ef2f71d1108e828c08be5
Status: Downloaded newer image for docker.io/immauss/openvas:latest
9:C 23 Mar 2021 15:21:11.243 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
9:C 23 Mar 2021 15:21:11.243 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=9, just started
9:C 23 Mar 2021 15:21:11.243 # Configuration loaded
Wait for redis socket to be created...
Testing redis status...
Redis ready.
Creating Data and database folder...
mv: cannot remove '/var/lib/postgresql/12/main/base/1/112': No such file or directory
mv: cannot remove '/var/lib/postgresql/12/main/base/1/113': No such file or directory
mv: cannot remove '/var/lib/postgresql/12/main/base/1/1247': No such file or directory
mv: cannot remove '/var/lib/postgresql/12/main/base/1/1247_fsm': No such file or directory
mv: cannot remove '/var/lib/postgresql/12/main/base/1/1247_vm': No such file or directory
...
`

What I did wrong?

Tks.
Marco Aurélio

**Comment by immauss** [comment]
That is unusual. I pasted exactly what you have here, and it worked just fine. Can you give me some details on your environment?  Though you should have either "-d" or "--detach" in your command line.

**Comment by radiusmk** [comment]
Ok, thanks for replay.

I think the problem is the version of the docker package available on RH7. I ran the same command on an RH8 with podman and the container started successfully.

**Comment by radiusmk** [comment]
Container started successfully with podman.
