### ISSUE TITLE
issue with latest image PostgreSQL version

### ISSUE THREAD

**Issue by cybermcm** [immauss/openvas#33]
Using latest tag I'm receiving a startup error since  today:
```
DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 11.11 (Ubuntu 11.11-1.pgdg20.04+1)
```
Was there a downgrade (seems so) but why?

**Comment by cybermcm** [comment]
just found https://github.com/immauss/openvas/issues/31, it seems you are testing a new approach, reverting to 20.08.04.6, working again

**Comment by immauss** [comment]
@#$!@# 
Thanks.
 Looks like a goofed up the git branching. 
I'm trying to straighten it out now.

**Comment by immauss** [comment]
Please let me know if you have any other issues. I'm closing this one.
