### ISSUE TITLE
Docker Container seems to exit immediately upon running

### ISSUE THREAD

**Issue by quentinkhoo** [immauss/openvas#34]
Hi, for some reason when I run the suggested command to start the container as shown below, the docker image immediately exits. Is there something Im missing out? Thanks!

![image](https://user-images.githubusercontent.com/33711159/112976506-88670f00-9187-11eb-81b2-b647cd542391.png)

**Comment by quentinkhoo** [comment]
So i opened the logs and this was what I got:
![image](https://user-images.githubusercontent.com/33711159/113025376-78b4ee00-91ba-11eb-9b14-86eb09395fd1.png)

**Comment by immauss** [comment]
Looks like something went wrong with the DB refresh Monday morning. I've pull the most recent image back as the latest. If you remove and  then pull the image again, it should work. Thanks for letting me know.

-Scott

**Comment by quentinkhoo** [comment]
Looks good to me now! Thanks for the quick fix :)
