### ISSUE TITLE
gvmd feed update

### ISSUE THREAD

**Issue by hoboristi** [immauss/openvas#37]
Hi,
Is it normal, that feed version from https://community.greenbone.net/ stucked at 202104060959 ? Also, is it sufficient to restart the docker image for the nvt upgrades, or new image pull is a must?

Thanks, 
Istvan

**Comment by immauss** [comment]
Yes. Currently the NVTs only update when you restart the image.
An no. No reason to pull the new image unless you see there is an update. I haven’t made any serious changes in a few weeks though.

-Scott

**Comment by immauss** [comment]
Let me know if you have any other questions.
