### ISSUE TITLE
Usage of NEWDB environment variable

### ISSUE THREAD

**Issue by fansari** [immauss/openvas#38]
The NEWDB environment variable is initially set to "false". This means if I don't set it explicitly to "true" in the container environment the code block in /start.sh creating a base DB from /usr/lib/base-db.xz is executed.

Is this intended? The normal case is that the database already exists.

**Comment by immauss** [comment]
Thanks. Yes. I was looking at this last night and trying to decide what was wrong with it and how to fix it. 

I think I've  resolved it. I'm doing some testing now.  I'll let you know once it's pushed. 

It really needed a second variable to track what I wanted to do.

**Comment by immauss** [comment]
OK .. It looks better now. Pushing the new image to latest now.

**Comment by immauss** [comment]
I'm going to go ahead and close this out. Thanks for bringing it up and let me know if you have any other issues. 

-Scott
