### ISSUE TITLE
No ports exposed in image

### ISSUE THREAD

**Issue by gooseleggs** [immauss/openvas#4]
You cannot use this image with Dockergen, as the image is not exposing any ports.  Can you please add to the Dockerfile

```EXPOSE 9392```

Then, dockergen can create a configuration for it when it is behind a reverse proxy.  It should have this in the Dockerfile anyway.

**Comment by immauss** [comment]
Hmm you have me at a disadvantage. I'm not familiar with this use case.  The "EXPOSE" directive, as I understand it, doesn't actually do anything. (https://docs.docker.com/engine/reference/builder/#expose). Can you give me a better idea what you are trying to do? I'm happy to add it the Dockerfile, I'd just like to be able to document fully why and possibly add anything else that may better support the use case. 

Thanks,
Scott

**Comment by gooseleggs** [comment]
In regards to EXPOSE, from the Documentation: The EXPOSE instruction does not actually publish the port. It functions as a **type of documentation between the person who builds the image and the person who runs the container**, about which ports are intended to be published.  So, If you didn't tell me in the documentation what ports to connect to, I can inspect the image and find it out.  This command doesn't do anything in the image, other than add metadata to it.

As for the use case.  I, and others use NGINX in front of containerized web services.  This allows many websites to be run on HTTP/HTTPS.  Dockergen is a script that creates NGINX configuration files against containers and reloads NGINX when a container starts and stops.  So with it, I can run many (containerized) applications on a port, ie 443, but it will connect to the containers IP and port on the backend.  Dockergen looks at the containers exposed ports to build a config, and because it is not documented, assumes that there is nothing to connect to so wont add it.

To confirm, I created a Dockerfile with the Expose command and worked.

**Comment by immauss** [comment]
Sorry for the delay. I added it today.

**Comment by immauss** [comment]
I'm going to go ahead and close this issue.
Please let me know if you have any other ideas or suggestions for improvment.

Thanks,
Scott
