### ISSUE TITLE
Can't save scan configs

### ISSUE THREAD

**Issue by LoZio** [immauss/openvas#45]
Using latest, after I try to modify a cloned scan config I get
Whole-only families must include entire family and be growing

![image](https://user-images.githubusercontent.com/869890/121694859-ce671a00-caca-11eb-991c-964c905ea55a.png)
Is seems a solved issue in OpenVAS (https://community.greenbone.net/t/error-whole-only-families-must-include-entire-family-and-be-growing/9169)
After the error not all scan configs are saved, for example the selection of active families is not.

**Comment by immauss** [comment]
Unfortunately, this is beyond my ability to fix at the moment as it is not available in the released code yet.  As soon as the greenbone team updates the release, I'll add this in. 


Thanks,
Scott

**Comment by immauss** [comment]
So Greenbone released updates last week. I'm doing some testing on the latest images before pushing to latest. There should be a 21.04.03 tag in the near future. (buildx is chewing on it now) that will have the fix. If you have the cycles, please give it a test. This is still beta though .... so YMMV. 

-Scott

**Comment by immauss** [comment]
I believe this was fixed in the most recent release from Greenbone, so it should. be live now with the latest image.

**Comment by LoZio** [comment]
I confirm latest image is fine, can be closed
