### ISSUE TITLE
Login-Loop

### ISSUE THREAD

**Issue by threechord82** [immauss/openvas#50]
After entering the correct user data I see briefly (1 second) flash the interface, 
I am redirected back to the login screen and should enter my password again. 
I can’t get into the user interface of GVM.

**Comment by immauss** [comment]
Can you send me the last part of a the docker logs for your contianer?

**Comment by immauss** [comment]
This may have been during the brief period there was a problem with gsa that has been resolved now. Can you try the latest container image and see if you are having the same issue.

**Comment by immauss** [comment]
Haven't heard anything back. If this is still a problem with the latest image, please open a new issue. 
-Scott

**Comment by jonny190** [comment]
IVe got the same issue, the log shows:
==> /usr/local/var/log/gvm/gsad.log <==
gsad  gmp:MESSAGE:2021-08-24 08h50.22 utc:1132: Authentication success for 'admin' from 10.0.0.211

**Comment by immauss** [comment]
@jonny190 What tag are using? 
Please provide the entire contents of:
docker logs <container name>

**Comment by jonny190** [comment]
@immauss i'm using latest tag
How many logs are you wanting as there are a fair few pages

++++++++++++++++
+ Tailing logs +
++++++++++++++++
==> /usr/local/var/log/gvm/gsad.log <==
gsad main:MESSAGE:2021-08-24 09h31.52 utc:1132: Starting GSAD version 21.4.1~dev1
gsad  gmp:MESSAGE:2021-08-24 09h37.27 utc:1133: Authentication success for 'admin' from 10.0.0.211
gsad main:MESSAGE:2021-08-24 09h39.30 utc:849: Starting GSAD version 21.4.1~dev1

==> /usr/local/var/log/gvm/gvmd.log <==
md   main:WARNING:2021-08-24 09h38.04 utc:42: gvmd: databases are already at the supported version
md   main:MESSAGE:2021-08-24 09h39.21 utc:146:    Greenbone Vulnerability Manager version 21.4.2 (DB revision 242)
md   main:MESSAGE:2021-08-24 09h39.21 utc:151:    Greenbone Vulnerability Manager version 21.4.2 (DB revision 242)
md   main:WARNING:2021-08-24 09h39.21 utc:151: gvmd: Another process is busy starting up
md   main:MESSAGE:2021-08-24 09h39.22 utc:171:    Greenbone Vulnerability Manager version 21.4.2 (DB revision 242)
md   main:WARNING:2021-08-24 09h39.22 utc:171: gvmd: Another process is busy starting up
md manage:   INFO:2021-08-24 09h39.23 UTC:177: update_scap: Updating data from feed
md manage:   INFO:2021-08-24 09h39.23 UTC:177: Updating CPEs
md   main:MESSAGE:2021-08-24 09h39.23 utc:185:    Greenbone Vulnerability Manager version 21.4.2 (DB revision 242)
md manage:   INFO:2021-08-24 09h39.23 utc:185:    Getting users.

==> /usr/local/var/log/gvm/openvas.log <==
libgvm util:MESSAGE:2021-08-24 09h33.32 utc:1141: Updated NVT cache from version 0 to 202108231021

==> /usr/local/var/log/gvm/ospd-openvas.log <==
OSPD[1114] 2021-08-24 09:31:52,536: INFO: (ospd.main) Starting OSPd OpenVAS version 21.4.1.
OSPD[834] 2021-08-24 09:39:29,897: INFO: (ospd.main) Starting OSPd OpenVAS version 21.4.1.

==> /usr/local/var/log/gvm/gsad.log <==
gsad  gmp:MESSAGE:2021-08-24 09h40.00 utc:850: Authentication success for 'admin' from 10.0.0.211

==> /usr/local/var/log/gvm/openvas.log <==
libgvm util:MESSAGE:2021-08-24 09h40.34 utc:858: Updated NVT cache from version 0 to 202108231021

**Comment by jonny190** [comment]
[OpenVAS.Log](https://github.com/immauss/openvas/files/7038229/OpenVAS.Log)

**Comment by jonny190** [comment]
Looking in the chrome debug i'm getting auth issues 
![image](https://user-images.githubusercontent.com/8059327/130612187-984b564c-5161-46b9-8b71-4f7efe567c50.png)

**Comment by jonny190** [comment]
Cleared Cookies and fixed it

**Comment by immauss** [comment]
Awesome! Thanks for the follow up.
