### ISSUE TITLE
Update gvm-tools inside the container

### ISSUE THREAD

**Issue by dmlae** [immauss/openvas#51]
Hello

I was just testing the gvm-cli tools and found a bug that was solved: https://community.greenbone.net/t/authentication-failed-with-gvm-cli-same-creds-work-on-the-web-ui/9424

Just `pip3 install gvm-tools --upgrade` and it will be fixed.

Regards

**Comment by immauss** [comment]
Yes. Greenbone released new versions of everything late last week. I've built a new image already, just working on doing a little testing before I make it the latest. 

-Scott

**Comment by dmlae** [comment]
@immauss perfect, was just to let you know! 

Cheers and thank you for the good work!
