### ISSUE TITLE
[arm] Ubuntu Server  20.04

### ISSUE THREAD

**Issue by arthur4ires** [immauss/openvas#53]
My Raspberry pi report this error:

```
ubuntu@ubuntu:~$ sudo docker run --detach --publish 8080:9392 -e PASSWORD="9132059091320590" --volume openvas:/data --name openvas immauss/openvas
Unable to find image 'immauss/openvas:latest' locally
latest: Pulling from immauss/openvas
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'.
```

There is no support for raspberry?

**Comment by immauss** [comment]
Only on the arm64/aarch64 at the moment. The arm/v7 build fails because of dependencies.  I have a few ideas on how to work it out, but have not had the time to try them.

**Comment by arthur4ires** [comment]
What ideas? Can I help you! I would like OpenVAS on my PI.

**Comment by immauss** [comment]
Well, last night I tried to build it on a Pi running the armv7 kernel instead of using buildx, and it still failed spectacularly. So I'm back to the drawing board really. :(
I'm headed out on vacation today, I'll have an RPi with me, so maybe I can come up with something on my break.

**Comment by arthur4ires** [comment]
Alright then, if I can help with anything my email is me@arthurair.es, just send me.  I'm interested in this port!

**Comment by immauss** [comment]
Please see latest comment on:
https://github.com/immauss/openvas/blob/master/Readme.md

**Comment by arthur4ires** [comment]
Ok, thank you for the info.

**Comment by immauss** [comment]
OK. The new "armv7" tag is available and seems to be operational. It seems to work on hardware, but it took me a while to realize that postgres just does not like to be run with qemu on the armv7.  
I'm closing all of the current armv7 issues since since this is basically a complete rebuild. If you have new (or the same ) problems, please open a new issue. 

Thanks,
Scott
