### ISSUE TITLE
SMB for Windows scanning

### ISSUE THREAD

**Issue by arcreigh** [immauss/openvas#56]
Hello!
I was wondering if this container has the SMB requirements in order to scan Windows hosts?

See
https://greenbone.github.io/docs/gvm-21.04/index.html#openvas-smb

I am in the process of deploying this image now but wanted to ask just in case it wasn't in here yet.

**Comment by jeandoyon** [comment]
Yes. The info is in the source files too.

**Comment by immauss** [comment]
Sorry.. Thought I answered this. 
Yes. It does.
