### ISSUE TITLE
[BUG] Latest tag points to an older release.

### ISSUE THREAD

**Issue by gaby** [immauss/openvas#58]
There seems to be a bug tagging the latest tag, currently it points to 21.4.1 instead of 21.4.3

Latest:

```
immauss/openvas:latest
DIGEST:sha256:55eac39bce168a1a7400bd3cd79cfaf7e79b17c71c34df33ba31cce0dcd12f12
```

Tag 21.4.1
```
immauss/openvas:21.4.1
DIGEST:sha256:55eac39bce168a1a7400bd3cd79cfaf7e79b17c71c34df33ba31cce0dcd12f12
```

Tag 21.4.3
```
immauss/openvas:21.4.3
DIGEST:sha256:11872ad0c9919a903c11ed6338063bfb067b8cd01c01a4df22967397ddf53f11
```

**Comment by immauss** [comment]
Not a bug. 
21.4.3 is broken. And it's kicking my but. I switched latest back so if someone pulls latest, they get a working image.
