### ISSUE TITLE
current latest image breaks things

### ISSUE THREAD

**Issue by cybermcm** [immauss/openvas#62]
Updated by watchtower ;-( using latest image, reverting to 21.4.3 for now
Trying 'latest' image (33f5854b20e4) breaks things:
```
openvas                     | 8:C 01 Sep 2021 17:47:24.991 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
openvas                     | 8:C 01 Sep 2021 17:47:24.991 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=8, just started
openvas                     | 8:C 01 Sep 2021 17:47:24.991 # Configuration loaded
openvas                     | Wait for redis socket to be created...
openvas                     | Testing redis status...
openvas                     | Redis ready.
openvas                     | Fixing Database folder...
openvas                     | ln: failed to create symbolic link '/var/lib/postgresql/12/main': No such file or directory
```

**Comment by immauss** [comment]
Yeah. There was an old cron I thought was disabled that rebuilt the image on the wrong branch.

21.4.3 and latest are now the same.

-Scott

**Comment by cybermcm** [comment]
@immauss thx for the fast reply. Can you initiate a push for `latest` to get it to hub.docker.com?

**Comment by immauss** [comment]
Done.

I think I have the rebuild automation almost ready. Building the arm64 via qemu takes ~ 2 hours, so I let it build, now I need to op test the results and push to docker.

**Comment by immauss** [comment]
BTW ....... 
the branch it built from is set up to run everything in its own container .... as containers should be using docker-compose. 
It's all working, but there are some bits that are still a little kludgy and need to be cleaned up.

**Comment by dkade** [comment]
Just tested a couple of hours ago, and can confirm it's happening.

**Comment by cybermcm** [comment]
Just tested latest image (55eac39bce16), everything seems fine now, thx...
Noticed that it is version 21.4.1, shouldn't it be 21.4.3, just being confused?

**Comment by immauss** [comment]
There is now a new 21.4.3 tag.  It seems to work for me. If you have a chance to verify, I'll flip it to the latest. 
@cybermcm

**Comment by cybermcm** [comment]
@immauss image with TAG 21.4.3 seems to work, but 21.4.2 is shown in the web interface? That's confusing at least ;-)

**Comment by immauss** [comment]
Talk to Greenbone on that  one. Some of the components, gvmd, ospd , are versioned at 21.4.3 and other are at 21.4.2  I was going with the gvmd version. 
 For reference:

gvmd=v21.4.3
openvas=v21.4.2
openvas_smb=v21.4.0
gvm_libs=v21.4.2
openvas_scanner=v21.4.2
gsa=v21.4.2
ospd=v21.4.3
ospd_openvas=v21.4.2
python_gvm=v21.6.0
gvm_tools=v21.6.1

**Comment by immauss** [comment]
@dkade Would you mind sharing your scripts? On my 'todo' list is coming up with a method to automate the testing of new images and that sounds like it would give me a good start.

**Comment by cybermcm** [comment]
@immauss: Thx for clarification on version numbers, didn't know that. Just my 2cent: Maybe you should stick to the openvas version number, this is probably the first thing a user will check if there is an issue (at least I did check the version number there and not in the log)
another thing: in this image (bf0839347317) there is the problem, that no gvmd socket is available, so if you push to latest then it conflicts with https://github.com/immauss/openvas/issues/63
@dkade: I'd be interested too in these scripts, currently I manually add hosts and tasks all the time. Not very efficient ;-)

**Comment by dkade** [comment]
Hi @immauss @cybermcm 

I will eventually release them in the open, but I have created them to use them on the company I work for. I will eventually release them and let you guys know. 

But I use the following as my starting point: https://github.com/greenbone/gvm-tools/blob/master/scripts/scan-new-system.gmp.py

You can run that inside the container. That is expecting command line arguments but you can easily change to self contained.

I also advise to update the python gvm-tools inside the container: `pip3 install gvm-tools --upgrade` .

**Comment by immauss** [comment]
@dkade Thank you! 
The version of gvm-tools in the 21.4.3 container should be the latest (21.6.1). If not, please let me know. 

-Scott

**Comment by cybermcm** [comment]
I'll close this one, issue from OP is already solved, thx @immauss
