### ISSUE TITLE
Not finding any vulnerabilities but logs.

### ISSUE THREAD

**Issue by c0y0te-git** [immauss/openvas#69]
Running a Full and Fast default scan on targets only produces logs, no actual vulnerabilities. Tested on VM with known vulnerabilities, and none were even able to be detected besides 0.0 (Log) severity ones.

**Comment by lpingree** [comment]
I had the same results. Ultimately the scan is saying terminated early. I did not see any logs that indicated what error message was thrown in any of the /var/local/gvm directory that indicated anything beyond a simple error message and that the task quit.

**Comment by immauss** [comment]
That is odd... 
It's working fine for me in test and my production.
![image](https://user-images.githubusercontent.com/3965511/137601979-1bf962be-11fd-44b6-b19e-779afc67cb29.png)

**Comment by lpingree** [comment]
I am using the latest version. Could it be something to do with network config?

**Comment by immauss** [comment]
Sorry, that went early. 
I was going to ask if you were certain you are using the latest image. (It was updated 19 days ago.) 
Can you tell me how you are starting it? 
If you are using the docker-compose.yml from the github repo, it had a bug I fixed last week, so make sure you have the most recent.

**Comment by c0y0te-git** [comment]
> Same here. I'm scanning a whole /24 network and finding logs only. Tested with (really) older image (mikesplain/openvas) and lots of vulns found. ![image](https://user-images.githubusercontent.com/164008/137403616-309ce940-7f26-4281-b0fd-aeaae5e86a30.png)



> I had the same results. Ultimately the scan is saying terminated early. I did not see any logs that indicated what error message was thrown in any of the /var/local/gvm directory that indicated anything beyond a simple error message and that the task quit.

Check out the settings on default Full and Fast scan config. Clone it, and then click "Edit" to look through them, see if Port Scanner is unchecked.

**Comment by jsuelwald** [comment]
I'd like to re-open this as this shoudn't be the default.

(Installed the docker image yesterday and it's still the case)

**Comment by immauss** [comment]
First ... this is a REALLY old issue. Best to open a new one if you have a problem and reference this one. 
Second, the problem from this issue was actually with the Greenbone scanning config, unfortunately nothing I can do about that. The latest image is being used in multiple places, so i know it's good. I haven't tweaked it in weeks.  If you still see an issue though, please open a new issue. 

Thanks,
Scott
