### ISSUE TITLE
Authentication failure for 'admin'

### ISSUE THREAD

**Issue by LiohMoeller** [immauss/openvas#70]
I am using the latest image (on date: 20211019) and got the following error message while trying to login to the gui:

Authentication failure for 'admin' from ...

The password is set within the docker-compose.yml like:

    environment:
      - "PASSWORD=mysecretpassword"
      - "USERNAME=admin"

**Comment by teddue** [comment]
I have the same issue. 

I left the credentials the same as in the compose file your offer. 

The log says: 

Authentication failure for 'admin' from 127.0.0.1
