### ISSUE TITLE
Can't Open Report that downloaded

### ISSUE THREAD

**Issue by Roooodie** [immauss/openvas#71]
we installing Openvas 21.4.2
when we try to download the report, it downloaded but cannot be opened as the downloaded report is having 0 bytes in PDF (also other type cannot be opened)
![image](https://user-images.githubusercontent.com/50097679/138208916-a94555a5-1e0e-48cf-acfa-278667533152.png)

![image](https://user-images.githubusercontent.com/50097679/138208891-8197168a-d704-4963-8032-84c6463cb9c4.png)

**Comment by immauss** [comment]
Please let me know i this is still an issue in the latest image.

**Comment by cybermcm** [comment]
@immauss: I'm experiencing this as well with latest image (`sha256:bd33cdd13e93563323f0116509f7eec22fda2b8ec953d9d02c06093f57091d8d`)
error message in log file:
`md manage:WARNING:2021-10-30 10h31.40 CEST:5817: run_report_format_script: system failed with ret 256, 1, /var/lib/gvm/gvmd/report_formats/8282ba3d-66e8-4971-859b-745b76a3a65e/c402cc3e-b531-11e1-9163-406186ea4fc5/generate /tmp/gvmd_ALmP9Q/report.xml '<files><basedir>/tmp/gvmd_ALmP9Q</basedir></files>' > /tmp/gvmd_ALmP9Q/c402cc3e-b531-11e1-9163-406186ea4fc5-Nrk7TP.pdf 2> /dev/null
`
I didn't do any extensive tests, just use your image with "autoupdate" via watchtower (using latest tag)...

**Comment by immauss** [comment]
Looks like everything works except PDF..... 
Probably a dependency missing somewhere ....
ReOpened this...

**Comment by immauss** [comment]
OK .... not sure how I missed it.... but 


From gvmd's install.md:
Prerequisites for generating PDF reports:

pdflatex

On Debian GNU/Linux 'Stretch' 9 the following packages can be installed to fulfill this prerequisite:

apt-get install texlive-latex-extra --no-install-recommends
apt-get install texlive-fonts-recommended


Looks like I missed the fonts ...

**Comment by cybermcm** [comment]
I can confirm this. After issuing commands within the container:
```
mkdir /var/lib/dpkg
touch /var/lib/dpkg/status
mkdir /var/lib/dpkg/updates
mkdir /var/lib/dpkg/info
mkdir /var/lib/dpkg/alternatives
apt install texlive-latex-extra --no-install-recommends
apt install texlive-fonts-recommended
```
pdf reports work again

**Comment by immauss** [comment]
OK ... I'm at loss on explaining this one .... 
Those packages are and have been in the base build image forever .... 
I rebuilt everything from scratch with no-cache and the packages are there. 
So I'm  pushing a new tag now .. 21.4.4-03 
Let's see if it get mysteriously removed ..... 

-Scott

**Comment by immauss** [comment]
Faster than I expected. 
There is now a 21.4.4-03 tag. 

Can anyone else verify it and I'll make it the latest. 
For me .... it looks good.

**Comment by cybermcm** [comment]
@immauss: I can confirm, that with 21.4.4-03 pdf report is working again "out of the box".
I didn't check anything else, so hopefully nothing else got mysteriously broken ;-)

**Comment by immauss** [comment]
@cybermcm  Thanks !!
again
:)
