### ISSUE TITLE
The scan only takes place in the docker host subnet!

### ISSUE THREAD

**Issue by itkroplis** [immauss/openvas#77]
Hi!
The scan only takes place in the docker host subnet! Is this normal for openvas? If I scan subnet or single IP address where is docker host IP address. I get a scan with found severity. But if I scan other my local subnets, scanning happened but there is no analysis or demonstration of vulnerabilities. I don't understand this is a mistake or so it works. And other subnets are blocked in openvas code? I try to add multiple network cards that look at each in their vlan, but that didn't help.

**Comment by itkroplis** [comment]
I found how resolve this. I clone scan config Full and fast. I edit  it and  enable Port scanners.  vualla

**Comment by immauss** [comment]
Glad you worked it out!
