### ISSUE TITLE
NVT:    Report outdated / end-of-life Scan Engine / Environment (local)  : ( on beta)

### ISSUE THREAD

**Issue by timscotland** [immauss/openvas#86]
Having hit the disk issue in :Latest we applied Fridays beta version 21.4.4-05 and I can confirm that resolves the disk issue.

The down side is that every scan now says that the NVT DB is outdated

NVT:  Report outdated / end-of-life Scan Engine / Environment (local)
Threat: High (CVSS: 10.0)

Thanks

Tim

EDIT - Looks like this might be a Greenbone / OSS version issue
https://community.greenbone.net/t/community-feed-problem/8306

**Comment by immauss** [comment]
<sigh>
Thanks

**Comment by immauss** [comment]
I think this is something with the latest NVTs. I'm seeing it as well in my latest build, but the container definetly has the latest release of gvmlibs.

**Comment by immauss** [comment]
Tracking in: 
https://github.com/immauss/openvas/issues/87

**Comment by immauss** [comment]
Resolved in 21.4.4-06
