### ISSUE TITLE
postfix doesn't start because of wrong owernship of /var/lib/postfix

### ISSUE THREAD

**Issue by sgaravat** [immauss/openvas#88]
In latest version (DIGEST:sha256:254132af30f9c572f08ecb024f37beafba3b5b8c9e183689d3b1191e38f64d6c) postfix doesn't start.
As far as we can see this is because the ownerhip of /var/lib/postfix is gvm: changing the ownership to postfix fixes the problem
Thanks, Massimo

**Comment by immauss** [comment]
Ooofa !
I didn't even notice that. 
Thank you! I'll fix that up in the fs-setup.sh .... that's what it's for. 

 I really appreciate the debuggin. 

-Scott

**Comment by immauss** [comment]
It will be fixed in the final update for 21.4.4-06 in the next day or so. 

Thanks again.

**Comment by sgaravat** [comment]
Thanks a lot !

**Comment by immauss** [comment]
Resolved in 21.4.4-06
