### ISSUE TITLE
Docker image after 21.4.1 don't contain /var/run/gvmd.sock

### ISSUE THREAD

**Issue by gquittet** [immauss/openvas#89]
I encountered a problem when working with newer images.

They do not contain the unixsocket file /var/run/gvmd.sock

At first, I thought the issue was with my in Dockerfile, but after testing everything, I came to the idea that the issue was not in my code.

Then, I tested previous versions of immauss/openvas and noticed that version 21.4.1 contained this socket file.

To test if the file was in the container, I ran the following command: 

     find / -name "gmvd.sock"

If I can help you in some case, ask, I'm glad to help open sources projects like yours.

**Comment by immauss** [comment]
Yes. This was buy design. I had a ton of problems with the container and sockets, and in preperation for moving everything into seperate containers, I switched the communication from to gvmd to a TCP socket. If you are using scripts, you'll need to have them use the ssl option. ( At least I think that's right .... I've not done much scripting with gvmd) When I was working on this, I couldn't find a way to have it listen on both the socket and the TCP ...

**Comment by immauss** [comment]
Ah ...  found it in some of my test scripts. Not ssl option ... tls

example:

gvm-script --gmp-password admin --gmp-username admin tls  ./scantest.py
