### ISSUE TITLE
OpenVAS Scanner failed to load VTs. Command

### ISSUE THREAD

**Issue by harshalgithub** [immauss/openvas#91]
Hi Team,

# Issue 1: 
I am able to start the container and able to access GSA, but getting the below error while initiating the scan from Dashboard.

I am using Windows Docker Desktop  Version 4.3.1 (72247)

==> /usr/local/var/log/gvm/openvas.log <==

lib  nasl:MESSAGE:2021-12-20 13h38.52 utc:781: /var/lib/openvas/plugins/plugin_feed_info.inc: Not able to open nor to locate it in include paths

==> /usr/local/var/log/gvm/ospd-openvas.log <==

OSPD[274] 2021-12-21 10:09:03,223: ERROR: (ospd_openvas.openvas) OpenVAS Scanner failed to load VTs. Command '['openvas', '--update-vt-info']' returned non-zero exit status 1.

Did anybody got same error, or any help ?

Thanks in Advance

**Comment by immauss** [comment]
It sounds like you might not be giving it long enough to update the VTs. It can take 20-30 minutes depending on you hardware and bandwidth. 

Alternatively, you can start the container with  "-e SKIPSYNC=true"
This will cause the container to use only the existing DB and not sync with Greenbone. Consequently, it is ready much quicker, but will not have the most updated VTs. 

-Scott

**Comment by fventurini** [comment]
Hi Scott
same problem no VT list.
Waiting for long time do not seem to affect the issue.
Also tried to restart, but OpenVAS Scanner failed to load VTs remain.
Any suggestion???

**Comment by immauss** [comment]
@fventurini & @harshalgithub    Which tag are you using?

**Comment by harshalgithub** [comment]
> @fventurini & @harshalgithub Which tag are you using?

Please find below image tag for reference.
![image](https://user-images.githubusercontent.com/9278569/148570007-f547f20e-93f0-4db2-9458-14805ede84e3.png)

**Comment by fventurini** [comment]
Hi for me problem is closed.
Simply taking a look at processes in run I understand that some process needed tobe completed,
 I only need to wait a bit more.

Thanls for your beatiful job!

**Comment by immauss** [comment]
Thanks!

**Comment by harshalgithub** [comment]
> > @fventurini & @harshalgithub Which tag are you using?
> 
> Please find below image tag for reference. ![image](https://user-images.githubusercontent.com/9278569/148570007-f547f20e-93f0-4db2-9458-14805ede84e3.png)
> 
> ==========================
> 
> @immauss Sir,
> 
> If Possible, Please check below architecture diagram, Also Request you to find below kind of setup for MultiContainer ( mc ) build so it will be kind of Master-Slave ( Master will be Administrator GUI of GVM and Slave will be remote scanner only which is reachable via SSH connections) architecture,
> 
> https://securecompliance.gitbook.io/projects/gvm_image
> 
> https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker
> 
> ![image](https://user-images.githubusercontent.com/9278569/148571575-dcf82388-886a-467a-b4e0-cc66bda883ea.png)
> 
> Will it be possible to make above kind of setup for your "mc" build, single Docker file/docker compose file.
> 
> ==========================

@immauss any update or guidance here please

**Comment by harshalgithub** [comment]
> > > @fventurini & @harshalgithub Which tag are you using?
> > 
> > 
> > Please find below image tag for reference. ![image](https://user-images.githubusercontent.com/9278569/148570007-f547f20e-93f0-4db2-9458-14805ede84e3.png)
> > ==========================
> > @immauss Sir,
> > If Possible, Please check below architecture diagram, Also Request you to find below kind of setup for MultiContainer ( mc ) build so it will be kind of Master-Slave ( Master will be Administrator GUI of GVM and Slave will be remote scanner only which is reachable via SSH connections) architecture,
> > https://securecompliance.gitbook.io/projects/gvm_image
> > https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker
> > ![image](https://user-images.githubusercontent.com/9278569/148571575-dcf82388-886a-467a-b4e0-cc66bda883ea.png)
> > Will it be possible to make above kind of setup for your "mc" build, single Docker file/docker compose file.
> > ==========================
> 
> @immauss any update or guidance here please

@immauss any update on architecture mentioned above?
