### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by aretsmarvin** [immauss/openvas#92]
Hi,

I was looking into the docker image, and it looks nice. However, I think (not sure), that it is slower, then when I ran openvas in a Ubuntu VM.
It looks like it stucks sometimes. 
Are there any ways the performance can be optimized?

**Comment by immauss** [comment]
I haven't seen any noticeable performance issues, but I've not really measured the performance either. (except in startup time and image size.) 

There "shouldn't" be any difference. However, it could greatly depend on your setup. 

The biggest advantage to using a container is not having to deal with the build and setup of GVM/Openvas on every machine you may need it and of course the portability of that build. 

What is your docker environment like?

**Comment by aretsmarvin** [comment]
I know the advantages of docker, that's why I am using it :)

I run it for now on my laptop. 32gb's RAM, Ryzen 7, gigabit ethernet on the whole local network (that I was scanning).

I can't exactly "prove" that it was slow. But I think it felt slower than running it in the ubuntu VM.

**Comment by dschinnerl** [comment]
You may check https://community.greenbone.net/t/everything-works-but-i-cant-see-any-report/5875/22. I need to do that fix/workaround (`jit=off`). Otherwise it "killed" my machine. (I had exactly the issue that `postgres` would burn the CPU endless.)

**Comment by immauss** [comment]
@dschinnerl That's pretty old. The current code from Greenbone has been optimzed to better support the newer versions of Postgres without the mods.

**Comment by recalmer** [comment]
Hey. Here the same issue. I have a fresh Debian11 (only with Docker and Portainer) and the latest immauss/openvas-Image. The Docker-Host run as a VMWare-VM with 12 Cores for the test. If i scan some subnetworks, the cpu-utilization goes endless. If i try the workaround "jit=off" in the /var/lib/docker/volumes/openvas/_data/database/postgresql.conf,  the cpu-utilization run now smoothly. 
![image](https://user-images.githubusercontent.com/45655990/153829438-90b780a2-1eae-49fd-8b3a-8e073be57067.png)

**Comment by immauss** [comment]
Interesting. That was "supposed" to be fixed a while ago. 
I can certainly add that to the default build though. 

Thanks!

**Comment by immauss** [comment]
This is now in the default build. 

Thanks!
