### ISSUE TITLE
Task hangs on 0%

### ISSUE THREAD

**Issue by jonahbohlmann** [immauss/openvas#96]
Hello,

does someone had the same issue that the application hangs after some hours of uptime processing new tasks?

Normally I define a task and click run - works. After some hours and some rescans new tasks started and I see healthy hosts in logs.
But then the tasks stucks for hours in 0%.

After restarting the gvm container, it is working again.

I see no problems in logs... any idea?

Thanks!

**Comment by sgaravat** [comment]
I see the same, but in my case I see something in the logs:

Could not connect to Scanner at /var/run/ospd/ospd.sock

**Comment by immauss** [comment]
@sgaravat based on that, it sounds like openvas-scanner has died. That tracks with what you are seeing too. Could it be possible you are running on low on memory? Are there any OOM Killer messages in the system logs ? How many hosts are you scanning?

**Comment by sgaravat** [comment]
@immauss: in my case there is indeed a memory problem. Thanks !

**Comment by immauss** [comment]
Please reopen if you are still having issues.
