### ISSUE TITLE
GOS configuration

### ISSUE THREAD

**Issue by michalp007** [immauss/openvas#97]
Hi, I like your work it's great to be able to run this system in docker, but I'd like to ask few question:

Is there any option how to access the GOS management interface where I'd be able to put the trial key and also setup couple of other options which I'm unable to do via web interface?

I can ssh into a docker, but that obviously does not run the GOS management interface.

Cheers

**Comment by immauss** [comment]
To my knowledge, there's no way to go from Community to GOS and I doubt Greenbone will support that. Maybe ask on the community forum. 
https://community.greenbone.net/
